{
  "hash": "a57bf34ef7d1c7f804b211bbda68faa8",
  "result": {
    "markdown": "---\naliases:\n  - ejercicio-semana6.html\n---\n\n\n\n\n# Comparación de grupos\n\n- El objetivo de esta sesión es aplicar la técnica de ANOVA en R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#getwd() \n#setwd(\"\") # Indicar el directorio de trabajo\n#dir()\n\nlibrary(rio)\nlapop = import(\"./data/s6/LAPOP20172016.sav\") # Abrir la base de datos\n#names(datalapop)\n#str(datalapop)\n#class(datalapop) \n```\n:::\n\n\n\n## **<b style = 'color : #50D050;'>PASO 1: Formato</b>**\n\n  - `PEconomica`:\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nlapop$PEconomica = as.factor(lapop$q10e)\nlevels(lapop$PEconomica)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"1\" \"2\" \"3\"\n```\n:::\n\n```{.r .cell-code}\nlevels(lapop$PEconomica) <- c(\"Aumento\", \"Igual\", \"Disminuyó\")\nlapop <- lapop[!is.na(lapop$PEconomica), ]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(lapop$PEconomica)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  Aumento     Igual Disminuyó \n      578      1366       685 \n```\n:::\n:::\n\n\n  - `ing4`: Apoyo a la democracia -> Variable ordinal de 7 categorias tambien la podemos tratar como numerica (per se no lo es), pues va a tener cierta variabilidad.\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nlapop$ing4 = as.numeric(lapop$ing4)\nlapop <- lapop[!is.na(lapop$ing4), ] # Eliminando NA\n\nsummary(lapop$ing4) # Resumen\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   4.000   5.000   4.503   6.000   7.000 \n```\n:::\n:::\n\n\n## **<b style = 'color : #50D050;'>PASO 2: Medias en los grupos</b>**\n\n  - Para ver por grupos\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(psych)\ndescribeBy(lapop$ing4, group = lapop$PEconomica)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Descriptive statistics by group \ngroup: Aumento\n   vars   n mean   sd median trimmed  mad min max range  skew kurtosis   se\nX1    1 576 4.81 1.52      5    4.89 1.48   1   7     6 -0.41    -0.14 0.06\n------------------------------------------------------------ \ngroup: Igual\n   vars    n mean   sd median trimmed  mad min max range  skew kurtosis   se\nX1    1 1341 4.52 1.55      5    4.58 1.48   1   7     6 -0.31    -0.41 0.04\n------------------------------------------------------------ \ngroup: Disminuyó\n   vars   n mean   sd median trimmed  mad min max range  skew kurtosis   se\nX1    1 665 4.21 1.65      4    4.24 1.48   1   7     6 -0.17    -0.59 0.06\n```\n:::\n:::\n\n\n  - Otra alternativa al descriBy, pero solo para obtener la Media y la desviacion estandar:\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nwith(lapop, do.call(rbind, tapply \n                    (ing4, PEconomica, function(x) \n                      c(Media = mean(x), \n                        SD = sd(x)))))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Media       SD\nAumento   4.805556 1.516416\nIgual     4.516779 1.553732\nDisminuyó 4.212030 1.647883\n```\n:::\n:::\n\n\n  - Parece que el apoyo a la democracia en promedio es mayor en las personas que consideran que aumentó\n\n  - Parece que el apoyo a la democracia en promedio es menor en aquellas personas que consideran que disminuyó\n\nPero en suma: promedios similares, es decir, no podemos garantizar si son diferentes signifcativamente.  La dispersion es baja. \n\n\n## **<b style = 'color : #50D050;'>PASO 3: REQUISITOS</b>**\n\n  - ***NORMALIDAD DE LA VARIABLE NUMÉRICA***\n\nCuando tengo un n menor a 50 casos (Fijarnos en las observaciones de la data), usamos la prueba de normalidad Shapiro-Wilk \n\n  - Hipotesis para ambas pruebas:\n(H0 = La variable se distribuye normalmente)\n\n  - Entonces, debemos utilizar la prueba Kolmogorov-Smirnov (mayor a 50 casos)\n   \n   - **Prueba Shapiro-Wilk**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nortest)\n#by(lapop$ing4, lapop$PEconomica, shapiro.test) # Menor a 50 casos\n```\n:::\n\n\n  Interpretacion en caso sea menor a 50 casos:\n  \n  - De acuerdo con el criterio del p-value menor a 0.05, rechazamos la H0.\nEntpnces, parece que esta variable no se comporta de manera normal en ninguno de los 3 grupos.\n\n\n  - **Prueba Kolmogorov-Smirnov**\n  \n\n::: {.cell}\n\n```{.r .cell-code}\n#library(nortest)\nby(lapop$ing4, lapop$PEconomica, lillie.test) # Mayor a 50 casos\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlapop$PEconomica: Aumento\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  dd[x, ]\nD = 0.13965, p-value < 2.2e-16\n\n------------------------------------------------------------ \nlapop$PEconomica: Igual\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  dd[x, ]\nD = 0.14634, p-value < 2.2e-16\n\n------------------------------------------------------------ \nlapop$PEconomica: Disminuyó\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  dd[x, ]\nD = 0.14204, p-value < 2.2e-16\n```\n:::\n:::\n\n\nInterpretacion:\n  \n  - De acuerdo con el criterio del p-value menor a 0.05, rechazamos la H0.\nEntpnces, parece que esta variable no se comporta de manera normal en ninguno de los 3 grupos. o La variable no se distribuye normalmente.\n\n\n  - ***PRUEBA DE HOMOGENEIDAD DE VARIANZA***\n\nPrueba de igualdad de varianzas (Homocedasticidad). La prueba de Levene tiene como \n\n  - H0 =  las varianzas son iguales\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nleveneTest(lapop$ing4, lapop$PEconomica) #Prueba de Levene, Pr es igual al Pvalue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLevene's Test for Homogeneity of Variance (center = median)\n        Df F value Pr(>F)\ngroup    2  2.2859 0.1019\n      2579               \n```\n:::\n:::\n\n\n  - Fijarnos en el Pr(>F): En este caso, aceptamos la H0, es probable que las varianzas sean iguales o similares.\n  \n**Interpretacion:**\n  \n  - El p-valor sale 0.1019 que es mayor a 0.05, entonces no rechazo la hipotesis nula. Conclusion es que las varianzas son iguales.\n \n\n***Hasta aquí, advertimos que la variable no ha cumplido con el supuesto de normalidad (prueba Kolgomorov), pero sí la prueba de varianza (Levene). Es decir, ya no se puede continuar con la prueba ANOVA, Sino con otras pruebas de Estadistica no parametrica.***\n\n***A menos que la pregunta solo pida la prueba Anova, asumiendo que hay normalidad (Estadistica parametrica) se continuara con Anova.***\n\n  - Entonces, asumiremos que sí hay normalidad y continuaremos con la prueba ANOVA:\n\n## **<b style = 'color : #50D050;'>PASO 4: ANOVA</b>**\n\n  - H0: Las medias son iguales \n  \n  - HA: Al menos una media es diferente\n\n::: {.cell}\n\n```{.r .cell-code}\nanova <- aov(lapop$ing4 ~ lapop$PEconomica)\nsummary(anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                   Df Sum Sq Mean Sq F value   Pr(>F)    \nlapop$PEconomica    2    109   54.64   22.16 2.88e-10 ***\nResiduals        2579   6360    2.47                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n  - Df: Grados de Libertad\n  - Sum Sq: suma de cuadrados\n  - Mean Sq: promedio de suma de cuadrados\n  - F value: Estadistico F\n  - Pr(>F): P-value del estadistico F <- ***Ayuda a determinar si rechazamos o no la hipotesis nula***\n   \n   \nEntonces, rechazamos la hipotesis nula, 2.88e-10 es menor a 0.05. Es decir, al menos una de las medias es diferente (de los 3 grupos). Además el estadistico F (22.16) es muy alto \n\n  - Para comprobar qué grupos son iguales o no\n   \n  Prueba TukeyHSD: comparacion multiple de promedios\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(anova) # H0: las medias son iguales / No son diferentes\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = lapop$ing4 ~ lapop$PEconomica)\n\n$`lapop$PEconomica`\n                        diff        lwr        upr     p adj\nIgual-Aumento     -0.2887770 -0.4722400 -0.1053140 0.0006666\nDisminuyó-Aumento -0.5935255 -0.8031427 -0.3839083 0.0000000\nDisminuyó-Igual   -0.3047484 -0.4794124 -0.1300845 0.0001307\n```\n:::\n:::\n\n\n  Se lee así:\n  \n  - La diferencia entre los promedios de (`Igual-Aumento`) es signficativa, ya que el (`p adj`) es menor a 0.05 (`0.0006666`). Además, a un 95% del nivel de confianza, el intervalo de confianza en el que oscila esta diferencia está entre 47% y el 10%\n\nEn el caso de esta variable (`ing4`), advertimos que todas la diferencias de promedios son signficativas.\n\n  ENTONCES, sí hay relacion entre la autopercepción economica y el apoyo a la democracia. se evidencia que los promedios dentro de los grupos nos anuncian que mientras que el apoyo a la democracia en promedio es alto la perpecion economica tambien lo es en el grupo de las personas que consideran que aumentó.\n\nSí impacta el apoyo a la democracia en la autopercepción economica. Es decir, si la gente considera que sus ingresos hayn disminuido, su apoyo a la democracia va a tender a disminuir.\n\nEste es un indicador importante, aun más que medir el PBI y el apoyo a la democracia.\n\n## **<b style = 'color : #50D050;'>GRAFICO</b>**\n\n  - `ing4`\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(plotly)\n\nboxplot <- ggplot(lapop, aes(y = ing4, x = PEconomica, \n                             fill = factor(PEconomica))) + \n  geom_boxplot() + \n  xlab(\"Percepción económica\") + \n  ylab(\"Apoyo a la democracia\")\n\nggplotly(boxplot)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-84faed9d9b3762f4d3ed\" style=\"width:100%;height:532.8px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-84faed9d9b3762f4d3ed\">{\"x\":{\"data\":[{\"x\":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],\"y\":[5,7,4,7,4,4,6,5,5,4,1,2,7,3,5,4,5,4,4,6,1,2,7,4,3,4,5,5,2,4,7,6,1,6,4,7,4,6,5,6,2,5,3,4,4,4,1,7,3,7,4,5,4,6,2,7,5,5,6,4,7,6,5,5,4,3,7,7,4,6,4,4,5,6,6,6,4,5,3,5,4,6,5,6,5,3,6,7,6,4,5,6,3,2,5,5,5,3,3,7,2,4,1,5,5,7,6,5,4,5,4,5,6,5,4,4,7,3,4,5,4,5,6,5,3,7,1,5,4,6,7,2,3,1,6,4,7,5,5,5,3,5,5,6,5,6,7,7,4,5,6,4,6,5,3,5,4,3,4,4,3,7,5,6,5,6,3,7,3,4,7,4,3,5,5,5,5,7,4,4,1,4,1,2,4,6,5,5,6,5,4,4,7,6,4,5,5,5,6,5,2,4,5,3,3,6,4,4,4,5,7,7,5,7,5,4,6,4,5,3,6,1,4,4,6,2,5,4,5,5,6,7,5,1,3,4,5,7,4,6,7,5,5,4,4,5,7,4,6,7,4,4,5,3,7,5,4,5,5,3,4,4,6,4,1,4,4,1,1,4,5,4,5,6,5,7,7,6,4,7,4,6,5,4,6,3,6,4,5,7,4,6,5,5,6,5,1,6,7,3,5,5,5,4,2,3,7,4,5,7,6,3,4,5,5,5,7,6,4,4,4,6,4,6,7,2,5,4,7,4,3,4,5,3,6,7,5,2,3,4,4,2,5,4,7,6,7,6,7,2,5,5,4,4,4,7,6,3,5,2,5,4,5,4,7,7,7,6,5,6,4,6,7,4,5,7,5,5,7,7,6,4,4,6,3,5,7,3,3,7,7,4,6,7,5,5,5,1,4,4,6,3,4,7,6,3,5,4,6,7,5,7,4,2,7,6,7,4,7,3,5,4,4,4,6,1,3,5,5,4,5,5,4,5,7,6,4,4,4,4,5,4,7,7,4,3,4,4,5,6,5,7,5,4,5,5,5,4,5,6,1,4,4,5,6,6,4,7,3,5,7,4,4,4,5,4,4,7,1,6,6,5,5,4,7,5,7,3,4,5,7,4,5,5,6,5,7,5,7,5,3,5,5,5,3,5,6,4,5,5,4,5,2,7,6,7,4,4,7,6,5,2,7,4,6,7,4,4,6,7,6,5,4,6,5,3,4,6,3,6,5,2,4,5,7,4,7,7,4,6,4,7,6,7,6,6,4,4,5,7,5,5,5,6,7,1,5,4,7,5,4,7,1,7,7,3],\"hoverinfo\":\"y\",\"type\":\"box\",\"fillcolor\":\"rgba(248,118,109,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.6692913385826778},\"line\":{\"color\":\"rgba(51,51,51,1)\",\"width\":1.8897637795275593},\"name\":\"Aumento\",\"legendgroup\":\"Aumento\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],\"y\":[7,7,6,2,4,6,5,4,7,6,5,5,5,2,4,4,3,5,4,5,7,7,6,6,3,5,4,4,6,1,4,5,4,6,4,2,5,5,2,6,4,6,6,4,3,7,6,3,3,4,7,4,5,5,4,7,5,6,5,4,5,2,4,7,5,4,5,4,4,4,5,5,5,4,3,4,4,3,3,6,5,6,4,3,4,5,5,1,5,4,5,7,3,7,4,6,5,7,4,3,5,5,4,2,5,7,5,5,6,6,5,3,5,5,4,6,3,2,7,4,7,1,6,4,6,5,3,5,5,5,4,3,4,5,4,4,4,2,5,5,7,4,2,3,1,6,4,4,2,6,6,4,1,3,5,2,2,6,4,6,6,5,5,1,4,5,6,7,1,4,5,2,4,3,2,4,4,4,6,7,3,3,6,4,5,4,3,3,4,4,7,7,7,3,5,2,5,6,5,5,2,3,4,5,4,4,7,7,7,7,5,2,4,4,7,6,3,6,1,3,3,5,4,7,3,7,5,4,4,5,6,5,5,6,4,5,6,7,5,4,5,6,5,6,7,6,4,2,3,4,2,6,7,5,5,3,2,6,5,5,6,3,5,3,5,4,3,2,1,4,3,4,1,7,5,7,5,3,1,4,6,7,6,7,4,4,5,6,4,6,3,5,7,4,4,6,3,7,4,5,3,6,4,7,5,4,1,4,1,5,5,3,6,7,3,4,1,6,3,4,4,6,5,3,4,6,2,3,6,3,5,2,1,3,7,7,6,6,5,6,5,7,5,6,5,3,1,7,5,5,4,3,6,3,4,5,3,5,7,6,7,3,3,4,3,3,4,6,6,3,2,7,5,5,5,6,5,4,1,5,7,5,4,3,6,5,4,5,7,3,5,4,5,1,6,3,5,7,7,5,4,5,6,6,5,4,4,5,4,3,5,4,5,3,3,7,1,4,3,3,2,6,4,4,1,3,4,1,4,5,5,5,5,3,2,3,5,4,7,4,6,4,3,1,5,5,5,5,7,5,5,7,6,5,6,6,4,2,1,3,5,5,3,5,3,1,7,2,7,6,5,5,3,2,3,6,5,7,6,5,5,5,5,5,3,4,7,7,4,4,4,3,4,5,3,4,6,6,7,4,6,7,4,6,5,4,7,7,7,4,7,5,5,4,6,4,1,5,3,4,6,7,4,5,7,6,5,5,2,4,7,3,7,4,5,4,5,4,1,6,4,1,6,6,3,4,5,4,3,7,5,5,4,4,6,4,5,6,5,4,4,7,3,4,4,3,4,7,4,6,4,5,4,4,6,5,2,5,5,1,4,7,4,4,4,6,6,6,6,5,2,5,1,4,1,4,4,6,7,5,6,4,6,5,5,5,6,4,5,6,4,2,4,3,6,7,7,5,3,5,1,3,3,7,7,4,4,4,4,1,2,6,3,4,4,4,7,3,5,4,5,5,5,3,5,5,5,3,6,7,6,3,4,5,3,2,2,1,6,3,4,4,5,7,6,4,2,4,3,3,5,2,5,4,4,4,5,7,3,5,6,2,6,6,7,5,4,3,4,4,7,2,5,1,2,6,6,5,5,7,7,5,3,5,6,7,6,6,6,5,4,5,7,4,3,4,4,3,4,5,2,3,4,4,4,5,6,6,5,4,5,5,5,3,1,6,4,7,3,3,7,4,4,7,5,4,5,4,5,7,4,7,5,4,2,3,3,5,5,6,5,3,2,4,7,5,7,7,6,4,5,5,4,4,7,1,1,4,6,6,6,7,2,7,2,6,7,7,6,4,4,6,6,4,4,5,3,6,3,5,4,5,6,4,2,2,4,7,4,6,5,5,7,4,4,5,6,6,4,6,5,5,6,4,7,5,6,5,4,5,3,7,1,2,5,7,6,4,4,6,4,6,5,5,4,6,3,3,6,3,4,5,5,6,1,5,2,5,5,4,1,7,6,5,4,3,6,3,7,4,6,3,4,6,6,6,5,6,3,5,3,5,7,5,5,4,4,6,6,2,6,6,1,5,3,6,3,5,4,3,4,5,5,5,6,5,5,5,2,2,4,3,5,4,6,5,5,3,5,4,1,7,4,4,4,6,5,4,4,5,6,4,7,3,7,6,7,4,7,5,5,5,5,6,4,6,7,6,4,7,3,2,7,3,6,3,6,5,6,6,6,5,5,5,4,7,7,3,5,7,4,4,2,3,5,4,4,6,5,2,6,6,4,6,5,6,5,5,6,6,4,4,4,4,6,6,4,4,4,3,3,7,5,6,5,3,4,4,4,5,6,4,5,5,3,2,4,5,4,6,7,7,7,4,7,4,3,2,3,3,4,4,6,6,4,3,3,1,4,1,2,4,6,5,4,5,7,5,5,2,5,3,6,4,4,6,5,5,5,5,5,6,5,5,2,5,7,4,4,3,7,5,5,1,4,5,5,4,6,5,2,4,1,5,4,3,2,4,2,3,6,2,4,3,4,1,1,1,7,3,3,3,3,3,3,4,6,7,4,7,6,5,3,5,7,6,5,4,4,6,6,3,4,5,6,4,6,1,4,5,4,2,4,4,3,4,2,3,7,5,7,3,4,3,5,5,7,5,1,5,5,5,6,5,5,5,2,5,4,6,5,1,7,3,3,3,6,3,5,5,4,6,4,5,5,5,5,6,1,4,2,6,1,5,6,5,2,2,6,7,6,4,7,6,4,4,6,4,4,4,3,3,5,5,1,4,5,3,5,7,3,2,5,2,4,5,4,7,2,2,4,3,5,5,3,6,5,1,4,4,4,3,7,5,5,5,3,6,5,5,7,5,3,4,5,4,3,6,3,1,5,6,1,5,4,3,6,6,2,4,6,2,5,4,5,4,4,7,3,3,4,5,3,7,4,1,1,7,3,3,5,4,3,6,5,3,7,5,6,4,4,3,6,4,5,7,4,2,4,5,4,5,5,7,7,5,6,5,2,4,5,5,4,3,5,6,4,5,5,5,3,3,3,5,1,5,5,3,4,4,5,5,5,3,4,6,5,5,6,7,5],\"hoverinfo\":\"y\",\"type\":\"box\",\"fillcolor\":\"rgba(0,186,56,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.6692913385826778},\"line\":{\"color\":\"rgba(51,51,51,1)\",\"width\":1.8897637795275593},\"name\":\"Igual\",\"legendgroup\":\"Igual\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3],\"y\":[3,7,7,5,6,5,5,4,4,5,4,5,4,5,7,6,6,4,4,5,2,7,5,4,4,3,4,2,5,5,2,1,7,4,1,5,1,5,5,5,4,6,6,3,2,1,2,5,3,1,7,5,3,4,5,6,3,6,4,6,3,7,3,4,3,4,5,4,4,3,7,1,4,6,4,3,3,4,3,7,6,4,4,6,4,7,5,6,7,4,4,3,3,4,3,3,2,2,5,4,4,2,3,3,5,5,3,6,6,6,5,5,6,4,4,5,4,7,6,6,2,6,5,4,7,4,2,4,5,4,1,5,4,3,4,3,5,1,5,3,2,5,5,3,7,3,4,3,4,2,7,6,7,3,6,4,4,3,3,5,1,4,4,5,6,6,2,4,6,6,2,6,5,5,5,5,5,3,7,6,7,5,7,1,1,3,7,4,2,5,3,3,5,7,5,1,1,4,5,4,5,6,7,4,3,5,6,7,5,7,2,4,4,6,4,5,6,5,4,3,4,4,2,4,7,1,4,5,5,7,5,4,5,6,2,3,6,3,5,3,4,4,4,5,5,5,2,5,1,7,5,4,5,5,4,4,4,5,5,1,5,5,5,5,4,7,4,6,7,2,6,5,4,5,4,4,4,1,4,2,1,6,4,7,4,4,4,5,5,4,2,4,1,6,5,5,5,1,5,1,7,5,4,4,6,3,4,1,6,2,7,4,5,6,1,5,5,3,6,2,1,5,4,4,5,4,5,4,2,5,1,5,3,7,1,3,3,4,4,7,5,5,5,5,5,6,5,7,5,2,3,6,4,2,6,7,6,6,4,4,6,4,3,4,3,5,3,1,1,4,2,5,7,4,6,5,4,4,5,5,7,3,3,4,1,1,6,5,4,2,7,3,7,5,7,5,6,7,5,3,5,6,3,6,1,4,4,7,7,4,1,5,4,5,6,7,5,6,2,2,6,3,5,2,6,5,2,4,2,6,3,4,1,5,3,5,5,7,2,4,4,5,4,6,7,3,3,5,4,4,5,4,7,4,5,6,4,4,5,3,1,4,3,4,5,5,4,3,4,6,4,5,5,7,5,3,7,7,5,5,7,4,2,2,4,5,4,3,5,4,1,6,3,1,2,4,3,5,1,4,7,1,5,2,7,2,5,6,1,3,4,5,4,3,3,5,6,1,7,4,1,3,4,1,4,3,3,4,3,4,4,2,6,5,4,7,7,7,3,4,2,1,2,1,6,1,6,4,6,4,7,5,4,3,1,2,3,2,1,3,5,3,4,6,4,3,4,4,6,4,5,4,4,6,5,3,7,6,4,3,4,3,4,3,6,4,4,1,4,4,7,7,4,4,5,4,5,2,6,3,4,3,5,5,2,2,3,6,3,3,2,3,4,6,7,5,3,7,4,3,4,4,4,3,3,3,6,3,6,4,5,2,4,3,2,6,4,3,4,4,5,4,4,4,2,7,2,5,4,6,7,2,1,1,5,5,5,5,1,2,3,3,4,5,3],\"hoverinfo\":\"y\",\"type\":\"box\",\"fillcolor\":\"rgba(97,156,255,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.6692913385826778},\"line\":{\"color\":\"rgba(51,51,51,1)\",\"width\":1.8897637795275593},\"name\":\"Disminuyó\",\"legendgroup\":\"Disminuyó\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":28.512701781465047,\"r\":7.3059360730593621,\"b\":42.46703968100843,\"l\":31.415525114155258},\"plot_bgcolor\":\"rgba(235,235,235,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,3.6000000000000001],\"tickmode\":\"array\",\"ticktext\":[\"Aumento\",\"Igual\",\"Disminuyó\"],\"tickvals\":[1,2,3],\"categoryorder\":\"array\",\"categoryarray\":[\"Aumento\",\"Igual\",\"Disminuyó\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716894984},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Percepción económica\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.69999999999999996,7.2999999999999998],\"tickmode\":\"array\",\"ticktext\":[\"2\",\"4\",\"6\"],\"tickvals\":[2,4,6],\"categoryorder\":\"array\",\"categoryarray\":[\"2\",\"4\",\"6\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716894984},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Apoyo a la democracia\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716894984},\"title\":{\"text\":\"factor(PEconomica)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"54e04fb17159\":{\"x\":{},\"y\":{},\"fill\":{},\"type\":\"box\"}},\"cur_data\":\"54e04fb17159\",\"visdat\":{\"54e04fb17159\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nFigure 1: Docentes según sexo (ENDO 2020).\n:::\n:::\n\n\n  - Advertimos rapidamente que la distribucion es similar y quizas la mediana tambien en los boxplots de `aumento` e `igual`.\n\n  - En este caso, si queremos ver promedios es mejor advertirlas en las barras de error. No recomendable un boxplot.\n\n  - **BARRAS DE ERROR**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(gplots)\nplotmeans(lapop$ing4 ~ lapop$PEconomica, p = 0.95,\n          main = \"Mean Plot \\n with 95% CI\")\n```\n\n::: {.cell-output-display}\n![Figure 1: Docentes según sexo (ENDO 2020).](s6-ejercicio-semana6_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Interpretación**:\n  - En este caso no se traslapan. son diferentes signficativamente\n\nsi se traslapan la diferencia podria ser 0.\n",
    "supporting": [
      "s6-ejercicio-semana6_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\r\n<script src=\"site_libs/plotly-binding-4.10.4/plotly.js\"></script>\r\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\r\n<link href=\"site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}