{
  "hash": "9648b326d7e009b37ed46484fdbf9136",
  "result": {
    "markdown": "---\naliases:\n  - ejercicio-parcial-semana8.html\n---\n\n\n\n\n-   Importar la base de datos\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rio)\nperu_data = import(\"./data/s7/Peru_Latinobarometro2020.sav\")\n```\n:::\n\n\nSe requiere analizar la cultura política del Perú sobre la confianza.\n\n### Pregunta 1 (3 puntos)\n•\t¿Cuál es la institución (P13STGBS) en la que más confían  (mucha confianza) los peruanos y peruanas? Calcule su intervalo de confianza al 95% de nivel de confianza.\n\n# Ir al cuestionario (o diccionario) –> encontramos 9 instituciones y son variables Ordinales: están codificados como (mucha, algo, poca, ninguna) \n#Darle Formato a las variables\n\n  - Renombrando:\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(peru_data) [41] <- \"FuerzasArmadas\"\ncolnames(peru_data) [42] <- \"LaPolicia\"\ncolnames(peru_data) [43] <- \"LaIglesia\"\ncolnames(peru_data) [44] <- \"Congreso\"\ncolnames(peru_data) [45] <- \"Gobierno\"\ncolnames(peru_data) [46] <- \"PoderJudicial\"\ncolnames(peru_data) [47] <- \"PartidosPoliticos\"\ncolnames(peru_data) [48] <- \"JNE\"\ncolnames(peru_data) [49] <- \"ElPresidente\"\n```\n:::\n\n\n#Entonces, calcularemos una tabla por cada una de las variables ordinales\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(peru_data$FuerzasArmadas)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n201 361 420 200 \n```\n:::\n\n```{.r .cell-code}\ntable(peru_data$LaPolicia)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n 91 278 499 317 \n```\n:::\n\n```{.r .cell-code}\ntable(peru_data$LaIglesia)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n420 339 286 141 \n```\n:::\n\n```{.r .cell-code}\ntable(peru_data$Congreso)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n 18  70 329 765 \n```\n:::\n\n```{.r .cell-code}\ntable(peru_data$PoderJudicial)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n 35 161 394 581 \n```\n:::\n\n```{.r .cell-code}\ntable(peru_data$PartidosPoliticos)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n 14  72 311 783 \n```\n:::\n\n```{.r .cell-code}\ntable(peru_data$JNE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n 68 312 467 330 \n```\n:::\n\n```{.r .cell-code}\ntable(peru_data$ElPresidente)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n 96 273 373 417 \n```\n:::\n:::\n\n#identicados los casos, Al observar las tablas determinamos esto:\n\nComando describe para ver a las 9 varaibles:\n\n::: {.cell}\n\n```{.r .cell-code}\n#install \n# library(Hmisc)\n# describe(peru_data)[41:49]\n```\n:::\n\n\n\n  - calculamos lo que nos pide la pregunta 1: (todo es respecto a los datoa de iglesia en el describe)\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x=c(420), n = c(1186), conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  c(420) out of c(1186), null probability 0.5\nX-squared = 100.36, df = 1, p-value < 2.2e-16\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.3270112 0.3822083\nsample estimates:\n        p \n0.3541315 \n```\n:::\n:::\n\n\n## **INTERPRETACIÓN**:\n\n  + La iglesia es la institución en la que más confían los peruanos y peruanas. El 35% confía mucho en esta institución. A un 95% de nivel de confianza, el porcentaje oscila entre el 32.7% y el 38.2%.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n### Pregunta 2 (3 puntos)\n\n#•\t¿Cuál es la institución en la que menos confían (confían nada) los peruanos y peruanas? Calcule si existe una diferencia de proporciones entre quienes no confían nada según su sexo. Al 95% de nivel de confianza . ¿Qué se puede concluir acerca de las diferencias entre hombres y mujeres?\n\n#Observamos las tablas que hemos hecho. Advertimos que son los partidos políticos en los que menos confían.\n\n#Pide un prop.test \n#pero antes, defino como factor (es una variable nominal) y darle su formato a las variables (sexo)\n#luego calculamos su tabla\n\n  - Formato:\n\n::: {.cell}\n\n```{.r .cell-code}\nperu_data$SEXO = as.factor(peru_data$SEXO)\nperu_data$SEXO = factor(peru_data$SEXO,\n                   levels = levels(peru_data$SEXO),  \n                   labels = c(\"Hombre\",\"Mujer\"), \n                   ordered = F)\ntable(peru_data$SEXO)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nHombre  Mujer \n   600    600 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(peru_data$SEXO)) # No hay NA's\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(peru_data$PartidosPoliticos)) # Sí hay 20 NA's\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 20\n```\n:::\n\n```{.r .cell-code}\nperu_data = peru_data[complete.cases(peru_data$PartidosPoliticos), ] # Borramos NA´s\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(peru_data$PartidosPoliticos, peru_data$SEXO) # Tabla de contigencia cruzada:\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   \n    Hombre Mujer\n  1      9     5\n  2     43    29\n  3    176   135\n  4    362   421\n```\n:::\n\n```{.r .cell-code}\naddmargins(table(peru_data$PartidosPoliticos, peru_data$SEXO)) # Para observar las tablas marginales y condicionadas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     \n      Hombre Mujer  Sum\n  1        9     5   14\n  2       43    29   72\n  3      176   135  311\n  4      362   421  783\n  Sum    590   590 1180\n```\n:::\n:::\n\n\n  - Tabla de proporciones: calculando LAS PROPORICONES CON RESPECTO A LAS COLUMNAS. Las Columnas suman 1, en este caso 100 % (*100):\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(peru_data$PartidosPoliticos,peru_data$SEXO),2)*100\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   \n        Hombre      Mujer\n  1  1.5254237  0.8474576\n  2  7.2881356  4.9152542\n  3 29.8305085 22.8813559\n  4 61.3559322 71.3559322\n```\n:::\n:::\n\n\n  - ahora procedemos con prop.test (lo que nos pide la pregunta): (en este caso, coinciden la cantidad de hombres y mujeres):\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(421,362), n = c(590,590), conf.level = 0.95) #Diferencia de confían nada entre mujeres y hombres\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(421, 362) out of c(590, 590)\nX-squared = 12.77, df = 1, p-value = 0.0003523\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.04469015 0.15530985\nsample estimates:\n   prop 1    prop 2 \n0.7135593 0.6135593 \n```\n:::\n:::\n\n\n  - HIPOTESIS NULA: No hay diferencia de proporciones entre quienes no confían nada en los partidos políticos de acuerdo al sexo de las personas / Las proporciones son iguales.\n  \n  - p-value = 0.0003523. De acuerdo con el criterio del 0.05. Podemos señalar que el p-value es menor, por tanto rechazamos la H0. Es decir, hay diferencia estadisticamente significativa.\n\n## **INTERPRETACIÓN**:\n\n  + La institución en la que menos confían los peruanos y las peruanas son los partidos políticos. \n  \n  + A un nivel de confianza del 95%, el porcentaje de mujeres que confían menos (`nada`) en partidos politicos es significativamente diferente que el porcentaje de sus pares que tienen la misma percepción. \n  \n  + En efecto, se observó que el porcentaje de mujeres (`71 %`) es mayor que el porcentajes de hombres (`61 %`) que comparten la misma sensión sobre los partidos politicos. \n  \n  + Además, la diferencia de porcentajes oscila entre el 4% y el 15%. \n  \n  + Por tanto, se concluye que sí existe diferencia significativa entre quienes no confían nada en los partidos políticos de acuerdo al sexo de las personas.\n  \n  \n    ***NOTA***: Cuando el intervalo de confianza de la diferencia de dos medias o dos proporciones incluye al cero , no hay diferencias significativas.#\n\n## **GRAFICA**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\np <- ggplot(data = peru_data, \n            mapping = aes(x = factor(PartidosPoliticos), \n                          fill = factor(SEXO)))\np + geom_bar(position = 'fill', stat = 'count')\n```\n\n::: {.cell-output-display}\n![Figure 1: Diferencia de medias (Latinobarometro 2020).](s8-ejercicio-parcial-semana8_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\nPregunta 3 (3 puntos)\n============================================================\n\n•\tConstruya un indicador (0 a 100) sobre la CONFIANZA INSTITUCIONAL DE ORGANIZACIONES DE LA SOCIEDAD CIVIL (ONGs, Sindicatos, Medios de Comunicación y Organismos multilaterales) . Informe sobre el comportamiento de dicha variable (P15ST). Calcule el intervalo de confianza al 95% de nivel de confianza.\n\n#Entonces, vamos al cuestionario/diccionario de datos\n#Indicador (Mínimo (Falta de confianza))  - (Máximo (Mayor de confianza)). \n#Por ejemplo: #Indicador (Pobreza)\n#Menor puntaje – Menos Pobreza\n#Mayor puntaje – Mayor Pobreza\n\n#El problema es que El sentido está al reves, e enefecto, si se suma 1 (mucha) 4 veces obtienes 4, pero con 4 (nada) se obtedría 16.\n##Siendo 1 (Mucha), 2 (Algo),3 (Poco) y 4 (Nada). 8 No sabe 0 No responde\n\n    -   ONG: P15ST.A\n\n    -   Sindicatos: P15ST.C\n\n    -   Medios de comunicación:P15ST.D\n\n    -   Organismos multilaterales: P15ST.G \n\n#Entonces, TENEMOS QUE RECODIFICAR:\n\n#Recodificación\n\n  - 1 Mucho --- 4\n  - 2 Algo ---- 3\n3 Poco ---2\n4 Ninguno ---1\n\nCambiar el sentido de las 4 variables:\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(peru_data$P15ST.A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n107 353 417 234 \n```\n:::\n\n```{.r .cell-code}\nlibrary(car)\nperu_data$ONG=recode(peru_data$P15ST.A,\"1=4; 2=3; 3=2; 4=1\")\ntable(peru_data$ONG)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n234 417 353 107 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(peru_data$P15ST.C)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n 40 254 429 383 \n```\n:::\n\n```{.r .cell-code}\nlibrary(car)\nperu_data$Sindicatos = recode(peru_data$P15ST.C,\"1=4;2=3;3=2;4=1\")\ntable(peru_data$Sindicatos)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n383 429 254  40 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(peru_data$P15ST.D)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n 98 308 442 311 \n```\n:::\n\n```{.r .cell-code}\nlibrary(car)\nperu_data$Media = recode(peru_data$P15ST.D,\"1=4;2=3;3=2;4=1\")\ntable(peru_data$Media)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n311 442 308  98 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(peru_data$P15ST.G)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n 24 234 426 302 \n```\n:::\n\n```{.r .cell-code}\nlibrary(car)\nperu_data$Multi=recode(peru_data$P15ST.G ,\"1=4;2=3;3=2;4=1\")\ntable(peru_data$Multi)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n302 426 234  24 \n```\n:::\n:::\n\n\n#Luego, con la construccion del indice aditivo (sumar):\n\n::: {.cell}\n\n```{.r .cell-code}\nperu_data$suma=(peru_data$ONG+peru_data$Sindicatos+peru_data$Media+peru_data$Multi)\nsummary(peru_data$suma)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  4.000   7.000   8.000   8.435  10.000  16.000     246 \n```\n:::\n:::\n\nminimo 4\nmaximo 16\n\n#luego de sumar, continuamos según lo que nos pide:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convertir del 0 al 100\nperu_data$restado=peru_data$suma-4 # resto por el mínimo\nperu_data$indicador=(peru_data$restado/12)*100 #divido entre el nuevo máximo\nsummary(peru_data$indicador)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n   0.00   25.00   33.33   36.96   50.00  100.00     246 \n```\n:::\n:::\n\ny ahora sí podemos hacer summary pues ya es una variable numerica\n\n  - Advertimos NA's y borramos:\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(peru_data$indicador))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 246\n```\n:::\n\n```{.r .cell-code}\nperu_data = peru_data[complete.cases(peru_data$indicador), ]\n```\n:::\n\n\n\n## **GRAFICO DE CAJAS (BOXPLOT) E HISTOGRAMA (HIST)**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#boxplot(peru_data$indicador)\n#hist(peru_data$indicador)\n\nlibrary(ggplot2)\nlibrary(plotly)\np1 <- ggplot(peru_data, aes(x = \"\", y = indicador, color =\"\")) + \n  geom_boxplot() + coord_flip() +\n  theme(legend.position = \"top\", axis.text.y = element_blank(), panel.background=element_rect(fill = \"white\", colour = \"white\")) + \n  geom_jitter(shape = 16, position = position_jitter(0.2)) + \n  labs(title = \"Indicador\", x = \"\", y =\"Index\", subtitle = \"\", caption = \"Fuente: Latinobarometro 2020. Elaboración propia.\")\nggplotly(p1)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-4bf104be86f5619a5917\" style=\"width:100%;height:532.8px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-4bf104be86f5619a5917\">{\"x\":{\"data\":[{\"x\":[41.666666666666671,0,66.666666666666657,8.3333333333333321,33.333333333333329,33.333333333333329,8.3333333333333321,75,75,33.333333333333329,33.333333333333329,33.333333333333329,83.333333333333343,25,50,41.666666666666671,33.333333333333329,58.333333333333336,16.666666666666664,41.666666666666671,41.666666666666671,33.333333333333329,41.666666666666671,8.3333333333333321,25,66.666666666666657,0,41.666666666666671,83.333333333333343,33.333333333333329,50,83.333333333333343,25,8.3333333333333321,8.3333333333333321,41.666666666666671,25,50,8.3333333333333321,8.3333333333333321,58.333333333333336,25,0,50,50,33.333333333333329,0,41.666666666666671,58.333333333333336,41.666666666666671,50,41.666666666666671,50,16.666666666666664,16.666666666666664,0,41.666666666666671,66.666666666666657,41.666666666666671,50,0,50,58.333333333333336,16.666666666666664,16.666666666666664,0,33.333333333333329,16.666666666666664,50,50,66.666666666666657,33.333333333333329,75,50,41.666666666666671,41.666666666666671,0,33.333333333333329,25,58.333333333333336,41.666666666666671,33.333333333333329,33.333333333333329,33.333333333333329,66.666666666666657,41.666666666666671,0,25,41.666666666666671,16.666666666666664,41.666666666666671,50,25,16.666666666666664,0,33.333333333333329,25,41.666666666666671,58.333333333333336,33.333333333333329,33.333333333333329,33.333333333333329,50,16.666666666666664,25,41.666666666666671,33.333333333333329,83.333333333333343,16.666666666666664,66.666666666666657,25,25,33.333333333333329,33.333333333333329,0,66.666666666666657,41.666666666666671,33.333333333333329,66.666666666666657,25,33.333333333333329,25,0,58.333333333333336,66.666666666666657,25,0,16.666666666666664,16.666666666666664,8.3333333333333321,41.666666666666671,50,50,66.666666666666657,8.3333333333333321,33.333333333333329,25,25,66.666666666666657,66.666666666666657,16.666666666666664,66.666666666666657,41.666666666666671,33.333333333333329,58.333333333333336,41.666666666666671,66.666666666666657,33.333333333333329,58.333333333333336,25,16.666666666666664,33.333333333333329,0,25,0,16.666666666666664,58.333333333333336,0,66.666666666666657,41.666666666666671,33.333333333333329,41.666666666666671,25,41.666666666666671,8.3333333333333321,50,41.666666666666671,25,8.3333333333333321,50,0,16.666666666666664,16.666666666666664,33.333333333333329,50,50,41.666666666666671,0,58.333333333333336,33.333333333333329,33.333333333333329,50,33.333333333333329,50,25,8.3333333333333321,25,66.666666666666657,58.333333333333336,16.666666666666664,75,0,50,33.333333333333329,16.666666666666664,8.3333333333333321,75,83.333333333333343,50,33.333333333333329,83.333333333333343,58.333333333333336,0,66.666666666666657,33.333333333333329,16.666666666666664,16.666666666666664,16.666666666666664,25,50,75,16.666666666666664,25,41.666666666666671,25,25,25,50,0,16.666666666666664,66.666666666666657,66.666666666666657,16.666666666666664,83.333333333333343,50,25,33.333333333333329,33.333333333333329,33.333333333333329,16.666666666666664,16.666666666666664,66.666666666666657,33.333333333333329,41.666666666666671,33.333333333333329,8.3333333333333321,33.333333333333329,50,33.333333333333329,33.333333333333329,41.666666666666671,25,33.333333333333329,66.666666666666657,25,66.666666666666657,8.3333333333333321,0,33.333333333333329,25,16.666666666666664,50,83.333333333333343,66.666666666666657,0,16.666666666666664,25,83.333333333333343,0,0,50,25,75,41.666666666666671,33.333333333333329,41.666666666666671,0,66.666666666666657,16.666666666666664,33.333333333333329,50,16.666666666666664,41.666666666666671,50,66.666666666666657,66.666666666666657,50,75,16.666666666666664,50,8.3333333333333321,41.666666666666671,50,41.666666666666671,58.333333333333336,41.666666666666671,33.333333333333329,25,16.666666666666664,50,100,41.666666666666671,33.333333333333329,50,16.666666666666664,58.333333333333336,75,50,33.333333333333329,33.333333333333329,66.666666666666657,41.666666666666671,50,66.666666666666657,41.666666666666671,33.333333333333329,16.666666666666664,25,66.666666666666657,50,83.333333333333343,50,33.333333333333329,41.666666666666671,33.333333333333329,41.666666666666671,50,58.333333333333336,33.333333333333329,0,33.333333333333329,83.333333333333343,25,25,25,16.666666666666664,58.333333333333336,50,50,16.666666666666664,33.333333333333329,25,25,8.3333333333333321,33.333333333333329,0,50,25,50,41.666666666666671,58.333333333333336,50,41.666666666666671,75,50,16.666666666666664,25,50,16.666666666666664,8.3333333333333321,25,25,50,16.666666666666664,41.666666666666671,50,33.333333333333329,58.333333333333336,58.333333333333336,66.666666666666657,8.3333333333333321,50,33.333333333333329,41.666666666666671,0,50,25,41.666666666666671,0,33.333333333333329,41.666666666666671,33.333333333333329,50,25,33.333333333333329,33.333333333333329,25,16.666666666666664,25,75,41.666666666666671,50,33.333333333333329,16.666666666666664,25,16.666666666666664,25,66.666666666666657,33.333333333333329,25,66.666666666666657,41.666666666666671,41.666666666666671,50,33.333333333333329,50,33.333333333333329,8.3333333333333321,16.666666666666664,25,83.333333333333343,58.333333333333336,0,41.666666666666671,50,8.3333333333333321,41.666666666666671,50,75,41.666666666666671,33.333333333333329,16.666666666666664,41.666666666666671,83.333333333333343,66.666666666666657,41.666666666666671,58.333333333333336,33.333333333333329,66.666666666666657,50,66.666666666666657,41.666666666666671,8.3333333333333321,41.666666666666671,50,83.333333333333343,66.666666666666657,16.666666666666664,58.333333333333336,25,25,25,33.333333333333329,33.333333333333329,33.333333333333329,25,66.666666666666657,41.666666666666671,66.666666666666657,33.333333333333329,50,25,33.333333333333329,100,16.666666666666664,25,75,33.333333333333329,25,41.666666666666671,33.333333333333329,66.666666666666657,58.333333333333336,66.666666666666657,50,8.3333333333333321,33.333333333333329,58.333333333333336,25,50,33.333333333333329,33.333333333333329,41.666666666666671,33.333333333333329,16.666666666666664,50,41.666666666666671,16.666666666666664,33.333333333333329,41.666666666666671,0,16.666666666666664,50,33.333333333333329,58.333333333333336,75,58.333333333333336,58.333333333333336,33.333333333333329,0,25,41.666666666666671,50,33.333333333333329,50,8.3333333333333321,0,41.666666666666671,0,50,0,33.333333333333329,50,58.333333333333336,58.333333333333336,91.666666666666657,41.666666666666671,75,41.666666666666671,50,50,33.333333333333329,41.666666666666671,25,16.666666666666664,16.666666666666664,58.333333333333336,50,50,8.3333333333333321,16.666666666666664,58.333333333333336,0,8.3333333333333321,25,41.666666666666671,33.333333333333329,58.333333333333336,25,25,16.666666666666664,0,58.333333333333336,16.666666666666664,33.333333333333329,83.333333333333343,8.3333333333333321,0,25,33.333333333333329,50,50,25,0,66.666666666666657,41.666666666666671,75,0,0,16.666666666666664,25,0,25,8.3333333333333321,33.333333333333329,41.666666666666671,16.666666666666664,33.333333333333329,8.3333333333333321,33.333333333333329,16.666666666666664,33.333333333333329,66.666666666666657,50,58.333333333333336,58.333333333333336,66.666666666666657,8.3333333333333321,16.666666666666664,33.333333333333329,33.333333333333329,0,41.666666666666671,50,41.666666666666671,25,33.333333333333329,66.666666666666657,33.333333333333329,41.666666666666671,8.3333333333333321,41.666666666666671,41.666666666666671,16.666666666666664,25,33.333333333333329,66.666666666666657,25,25,50,25,50,41.666666666666671,66.666666666666657,25,33.333333333333329,66.666666666666657,33.333333333333329,91.666666666666657,33.333333333333329,8.3333333333333321,25,33.333333333333329,58.333333333333336,41.666666666666671,50,0,66.666666666666657,33.333333333333329,50,25,58.333333333333336,25,16.666666666666664,0,75,41.666666666666671,41.666666666666671,16.666666666666664,33.333333333333329,0,41.666666666666671,50,25,33.333333333333329,25,33.333333333333329,66.666666666666657,41.666666666666671,66.666666666666657,33.333333333333329,41.666666666666671,41.666666666666671,41.666666666666671,50,33.333333333333329,41.666666666666671,16.666666666666664,0,33.333333333333329,50,25,50,16.666666666666664,50,41.666666666666671,25,16.666666666666664,50,33.333333333333329,33.333333333333329,25,25,33.333333333333329,33.333333333333329,33.333333333333329,50,33.333333333333329,33.333333333333329,8.3333333333333321,16.666666666666664,50,33.333333333333329,50,33.333333333333329,50,0,0,50,41.666666666666671,75,41.666666666666671,25,33.333333333333329,0,58.333333333333336,33.333333333333329,66.666666666666657,16.666666666666664,16.666666666666664,0,58.333333333333336,16.666666666666664,33.333333333333329,50,41.666666666666671,33.333333333333329,33.333333333333329,41.666666666666671,75,58.333333333333336,66.666666666666657,25,41.666666666666671,58.333333333333336,16.666666666666664,41.666666666666671,58.333333333333336,75,50,41.666666666666671,41.666666666666671,66.666666666666657,25,33.333333333333329,41.666666666666671,66.666666666666657,16.666666666666664,33.333333333333329,58.333333333333336,33.333333333333329,33.333333333333329,25,16.666666666666664,41.666666666666671,33.333333333333329,33.333333333333329,33.333333333333329,33.333333333333329,75,0,41.666666666666671,100,75,33.333333333333329,50,58.333333333333336,8.3333333333333321,33.333333333333329,50,66.666666666666657,33.333333333333329,75,58.333333333333336,41.666666666666671,0,8.3333333333333321,8.3333333333333321,16.666666666666664,33.333333333333329,16.666666666666664,58.333333333333336,66.666666666666657,83.333333333333343,25,50,25,33.333333333333329,41.666666666666671,41.666666666666671,41.666666666666671,50,50,75,50,25,16.666666666666664,41.666666666666671,50,25,33.333333333333329,25,33.333333333333329,25,58.333333333333336,41.666666666666671,66.666666666666657,0,8.3333333333333321,41.666666666666671,58.333333333333336,83.333333333333343,33.333333333333329,50,16.666666666666664,50,25,41.666666666666671,58.333333333333336,16.666666666666664,75,66.666666666666657,25,0,33.333333333333329,66.666666666666657,41.666666666666671,8.3333333333333321,58.333333333333336,66.666666666666657,75,16.666666666666664,50,33.333333333333329,16.666666666666664,33.333333333333329,41.666666666666671,58.333333333333336,33.333333333333329,66.666666666666657,0,33.333333333333329,50,33.333333333333329,41.666666666666671,75,41.666666666666671,25,41.666666666666671,66.666666666666657,58.333333333333336,0,33.333333333333329,0,16.666666666666664,33.333333333333329,0,8.3333333333333321,25,41.666666666666671,8.3333333333333321,25,25,50,8.3333333333333321,25,41.666666666666671,41.666666666666671,58.333333333333336,25,58.333333333333336,58.333333333333336,33.333333333333329,41.666666666666671,0,66.666666666666657,16.666666666666664,91.666666666666657,33.333333333333329,41.666666666666671,33.333333333333329,33.333333333333329,25,33.333333333333329,8.3333333333333321,58.333333333333336,0,0,33.333333333333329,16.666666666666664,41.666666666666671,25,8.3333333333333321,50,0,58.333333333333336,16.666666666666664,50,33.333333333333329,33.333333333333329,58.333333333333336,25,0,0,66.666666666666657,41.666666666666671,25,50,58.333333333333336,33.333333333333329,25,41.666666666666671,25,0,0,8.3333333333333321,41.666666666666671,33.333333333333329,58.333333333333336,58.333333333333336,25,41.666666666666671,66.666666666666657,41.666666666666671,8.3333333333333321,41.666666666666671,25,33.333333333333329,41.666666666666671,66.666666666666657,50,8.3333333333333321,33.333333333333329,0,0,33.333333333333329,0,41.666666666666671,91.666666666666657,58.333333333333336,58.333333333333336,8.3333333333333321,41.666666666666671,33.333333333333329,66.666666666666657,33.333333333333329,50,16.666666666666664,16.666666666666664,41.666666666666671,33.333333333333329,41.666666666666671,8.3333333333333321,33.333333333333329,25,50,8.3333333333333321,16.666666666666664,50,41.666666666666671,41.666666666666671,66.666666666666657,25,41.666666666666671,33.333333333333329,25,41.666666666666671,50,41.666666666666671,33.333333333333329,58.333333333333336,50,66.666666666666657,41.666666666666671,33.333333333333329,50,58.333333333333336,8.3333333333333321,33.333333333333329,50,16.666666666666664,41.666666666666671,8.3333333333333321,0],\"y\":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],\"hoverinfo\":\"x\",\"type\":\"box\",\"fillcolor\":\"rgba(255,255,255,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.6692913385826778},\"line\":{\"color\":\"rgba(248,118,109,1)\",\"width\":1.8897637795275593},\"legendgroup\":\"\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"orientation\":\"h\",\"frame\":null},{\"x\":[44.113273861197136,-1.0809593585630233,64.4820428530996,9.0828991852079799,36.282993949328848,36.304785663572439,9.5355609882002028,71.881625017461687,73.625468816608191,30.533786487455171,34.818326419529811,31.021202239207923,80.350859660344838,24.537872282477718,47.547172705332443,38.340092410023026,31.352460952475667,56.450275775666043,19.524919859444093,41.325214550209544,42.441470307918891,30.368671263568103,40.287837401653334,9.5606467298542412,26.17178326938301,66.59167710691689,-0.50176006897042091,42.780709985333189,83.783356915228083,33.545082484682396,48.580656380703054,80.189212681725635,26.508323357750967,7.4159841844812044,11.208994455325099,41.53891540598125,25.383371353770293,50.735767333147422,5.2058481952796436,7.3543239369367566,57.273064445083342,22.696278717679288,-2.1482535513738741,52.964469729922705,52.144422970401742,33.39141393080353,-1.2535777610416186,40.817564199678607,57.998007507994771,38.340386222116663,49.70483760970334,41.773846028372652,49.716472257860005,17.999140208897487,14.586340449750425,-2.6534199388697686,39.381417731444053,67.237264170932264,38.611764581874027,48.441564384847879,-2.5392588134854974,48.376921132827803,58.818132098143302,14.501994014717642,16.934162323984005,-1.7815317570542257,32.089390422527984,14.555114251561465,51.914398767985396,52.511409690293164,68.513513766229138,33.755706087686114,78.200826581257076,52.872326939056308,42.67468445468694,41.342770600070558,-2.3161884987105874,35.121641157505408,27.817248303132747,57.938643052863583,44.461743429613605,30.652936257732414,33.514342630902924,35.335348301256687,65.740961839134485,44.403532122572258,-3.3010080037638474,25.324271507561207,39.71613387266796,15.887070191092789,43.542971832988165,51.810171357356005,26.472739144228395,15.628517987206578,-2.4376723992948675,30.050856955349449,27.639922533805166,39.5792992024993,60.574765031536415,33.461379601309694,34.090229817666106,33.215925542948142,49.804600984789431,18.119426663033657,22.987001755585275,42.118904011634491,36.153187397867427,82.311681010760381,17.721882240536306,65.779362261916191,25.45179902265469,22.707968143125381,30.869583709475897,34.943174008900911,0.8777002881591498,66.298242183402166,39.080281880063325,32.612307787251964,63.63737530385454,25.794065849234659,31.099132850455742,26.154265566729006,1.1519976643224528,56.629895052562162,64.084481421547622,27.814306143360827,-2.4134090418616876,19.557029432617121,17.558670346625146,6.5686084299037883,40.969373324575528,50.67490655307968,49.487132650489613,64.012342575006187,7.8047596539060269,35.506654251366847,23.153834432984397,22.726253787986941,66.403786117831856,66.605667658150182,18.665013015270226,67.248747629734368,41.268638467105731,36.4847671225046,59.406610160755612,42.256373596998557,67.38311115341881,34.440549343513936,55.947555778548129,25.306142889894545,17.930733165703707,30.081104679654043,1.3053328714643886,23.056154580165948,2.3917375442882323,18.91032909664014,56.393168432017177,-0.25837871090819364,67.51683378747353,42.976883579976857,33.744755950756364,41.661343886516995,27.403641245327883,40.905168214812882,5.2279600532104631,49.666140377521515,41.131741283461459,24.05378300851832,11.236520255915813,48.666690867394209,-2.9060513324414625,17.720181512025491,19.992673907739409,36.32951662254829,51.068380028009415,50.946720715922609,42.740048874790475,-2.8246023956065311,61.542214884733156,32.310927974370614,34.709996053328112,51.735573612774409,36.428320738486931,52.821004975897566,26.445006318390366,10.840980907281233,27.710012709721916,64.663613435501844,60.396469604844846,13.692381175545359,77.048813829508916,-0.60280472040176258,50.772195025347173,33.338513056126729,18.085454014750812,8.2943759129072223,77.081275074742734,82.075915586513787,51.113934234405555,36.495623767065496,86.409414266236126,59.933766097140804,-0.57693654050429544,65.328088859096169,33.451717019391552,17.412908741583422,18.516830598625038,17.449318616030112,22.079941825941212,50.063100957001247,76.208523131596536,19.722744796114654,23.945976911733549,43.421903151708349,21.700704001511145,25.219082521895565,22.124886023812003,49.770743437111378,-2.8557962380970454,18.381210335840777,68.927605516898126,68.684805811693252,19.152865940704935,85.501106386072934,51.421103947795928,24.789503384381533,31.463744530143835,36.614708635024712,33.957687416113906,14.377866047434512,14.7735603293404,68.329902417026446,35.469409824969858,43.238354815791055,31.407488002441823,8.0017954669892788,34.843375453104571,52.308599549966551,32.162515482244387,34.887997205369167,42.841356530164681,23.323688233892128,32.437812029384077,65.864860508590922,23.218460902571682,67.011184566654251,7.4546007843067255,-2.5778946451221847,34.651919108194605,27.359814426551257,15.319460815129181,52.002322909732655,82.035068053131312,69.124781433492885,0.06925754404316331,19.50048353833456,26.787812816910442,83.438320971714958,1.3218844138706691,-0.42448346347858434,52.411465152787663,23.610695932681367,71.889832696566984,42.717731484832868,31.870027480957408,40.642568667729705,-2.2877778361240972,63.970150503640369,17.359461033095911,33.351764753460877,47.000742506546288,15.29817788861692,38.69921499087166,52.192043059815958,64.978215688218668,66.129728186254695,49.869658970274031,72.431828544164702,19.771730246332776,51.253008722948529,8.6408457299694401,41.737175436380014,50.221551172435284,43.027988504618406,59.226035980197288,40.038070490894228,36.641887892037616,26.066478197462853,16.590927761668958,51.109874658286572,101.17910246209551,44.516445520954825,34.810654727431626,48.81574141792953,18.22572362919648,57.78918740184357,73.803225915568575,50.622575388600424,35.471062138676636,30.437833269437157,65.597252314910293,43.976122797466815,51.964969420805566,69.970264551229761,40.176947020615145,36.57170521871496,16.562815112993118,26.903949772628643,67.362153974051267,50.175070414940514,81.359134403367847,47.687843769478306,31.530148761036493,41.14178074058146,31.846738210879266,41.821802334549531,51.676857654626168,58.433923041447997,32.547009042464197,-1.3509487935031423,30.740110731373232,83.409910315337285,24.22024634977182,27.924042288213961,25.305973030626774,16.749659554722406,59.361546413662531,47.33254047731559,50.491872866017118,15.720825490231315,35.404397275609263,26.231398434999086,22.34658297306548,7.6170231945191826,34.362205378711216,-1.6859201155602894,50.542776249349117,22.517855350549027,47.095876202608153,43.723983981957041,60.275135187742606,53.083486508888498,43.722381048525371,75.505973204659924,50.89990838275601,14.49935942112158,27.58428243454545,53.312555537559085,17.063370078491666,11.072324186873924,23.85148045451691,22.130117872729905,49.210090225872896,15.505605132008593,42.913373927585781,53.1417571598043,31.922184081437685,59.145163361293577,55.42260544685027,68.356928266584859,7.8116342363258209,49.375702018539116,31.008556853048503,39.107801769860103,1.2951975191632874,47.981218897427127,27.900921354691182,40.400423039682217,-2.6251027826219739,32.751130255249635,38.828068077564254,33.268811837770038,52.052505106354751,25.581039696310956,31.523146340623498,31.841472924376525,27.476288415491574,15.034594978205861,27.694559755424653,73.691333602182567,40.277782192764192,51.268129677822188,32.736141923815012,18.636839239237204,22.283910017771031,16.111670726289351,22.662274121927723,65.086981031733245,31.533417510800064,27.325148664725319,69.305012609499187,40.261227348819382,39.37271049711854,49.65812662305931,32.457663404444851,48.402961622923613,30.706517215197287,5.5215943154568521,13.405110100284224,27.163532646372911,86.35148290079087,56.776060218301922,-3.0718593578785591,40.979737271554775,49.04419987462461,10.775758895712588,39.975787061266608,52.136934190057211,75.178341210509345,40.256712560852378,30.118384997670852,17.563448781147596,40.368395382538445,81.493906877003624,64.981523483681173,43.29828250377129,60.662131584249437,33.885235606382281,65.45928854340066,50.345842074602842,63.710428426663078,40.118371335168689,10.921323364600532,44.991152769265071,52.427134386574224,86.368512882230192,65.620676133160785,17.941438586761549,58.216362499321505,27.074018574009333,25.042592597504456,25.625341931978859,31.971420467210312,31.018934962339699,36.560985318695494,26.156231250303485,63.345437611763671,39.315608134493239,65.31641876945892,33.398622561556593,49.36010572438439,23.127120194646224,33.142023592566446,97.859203236488014,16.283718342892826,22.885233553436901,77.832000725902617,33.282983046956353,22.887078085914258,40.307699300659209,33.419097412067153,67.214339358421654,60.561012754527226,69.861260674272955,48.5920436338832,8.645044304430483,34.556466871872537,58.761939940353237,26.923871263861653,52.261517858132713,30.397324068471789,35.839459399382264,38.868650346994414,35.779718421399586,18.069020964515701,53.099225885234766,40.44307567644865,17.776488497232393,30.537558066037796,43.24613086568813,-1.8551174054543136,18.162309493248657,49.978064286212124,31.293174256570637,58.195217150884375,76.583863222040236,55.465375087223954,60.194394703333572,35.460472675040357,-2.7655848255380926,26.329798817945019,41.242180193463966,53.08818941780676,34.073154806780309,47.931955576253436,10.013266402917598,-3.1913768127560544,42.849892113978669,0.85741879573712598,46.846040821013361,2.2938152604425897,34.098463001040116,52.721945519248635,60.207255842785038,59.558087661862373,89.663317459635437,44.471201070894793,78.127660572839275,44.902123962529004,50.122021928740047,52.94151435916622,34.750248691998415,42.710586171597242,22.07064486108721,16.348967466813821,16.182200315718848,56.381249149950847,49.16588231921196,50.923685700011745,7.1213354604939632,16.363594448193908,60.288043990731239,1.7269245116040075,7.9734447055185829,28.007089301633332,39.657160878802351,34.306157113363341,55.405865263504296,23.476889886272453,25.103032593615353,17.211170444885887,-1.3888991593072781,58.026578589342535,16.897765938192602,34.412565957754843,80.88587491307409,10.127480848071471,3.0876054506127968,23.126497922154769,31.931392443366349,50.227410829005144,49.273061451191708,22.000908628106124,2.3937631072476453,69.430233341020823,44.099021139554679,71.712728686009854,0.51635582620898779,1.3698776112869355,18.966370001435273,26.463489676825699,0.11188698156426335,22.99219010708233,10.686044997225199,34.097199210276202,39.83818071583908,18.512688774305079,30.441505894996226,11.580445400128752,31.116717867553234,15.48820354199658,35.721809132955961,65.790648418478654,47.104779502066478,56.419836833762631,58.317122445441782,68.998134137752146,8.6667998755971567,13.881061167145774,35.664090698895343,31.152121918275952,-2.5502520396063666,43.944495834099747,52.923916971000523,40.39689116335164,25.191249982453883,30.440885750576854,65.877961949445293,36.23794883179167,42.659198977053165,8.0220640466238056,39.997848231966309,43.893229370005429,15.635510552674532,24.695443419429164,32.44895706884563,68.261391059495494,24.687113823990028,26.459396877326068,47.276130754811078,28.301687887869768,50.731991808861494,42.643911143143974,66.798242338312164,26.845095336126782,33.715710975229733,67.207693050925926,33.230527465542153,89.880496722956494,34.711722577922039,9.8952524798611741,25.003267227051158,31.268546481927235,58.275192131598793,42.364348104844495,52.86067984377344,-2.0641158024469966,65.921072756561131,35.065853558480732,50.305693157327674,22.141519210611786,56.620318090232715,28.004065326725438,16.512077716179189,-0.96957206570853582,78.234936208464205,41.740779845664903,40.318679409101613,19.095312717060239,35.303891384974115,2.7818778871248107,39.155068981150798,51.157531955589846,26.028412561863657,30.480762543156743,23.126740427687768,33.04052177040527,64.272410701960325,43.287135711871088,69.967986620031283,34.496846905288592,43.595692361705005,43.68229687679559,40.928370780311532,48.147389579874776,34.141745980208114,44.110262026078999,16.360348047067721,-0.29814934047559838,36.036786944605396,51.299913905871406,22.807864323258404,51.480959745434419,16.348717710934579,47.571256433924042,39.023208225456386,22.731746964467074,16.812337300119299,50.485431076958776,35.17906850203871,34.853338004710764,25.92390973276148,23.769769545954965,35.409795205729694,30.818937158522509,33.154097093890108,47.305454371186599,31.565625760704279,31.075476878322661,9.8543035192415083,14.857592994036775,49.587321065676711,33.325393491735056,52.670999948556215,34.588879412040107,52.245014448029295,-3.2660336885601211,-0.20697506455083658,50.975221991539001,38.562271906994297,74.489933994288251,42.890104317727193,25.744719832825162,35.371657105473169,0.64283790532499419,58.475024380410716,35.124303684569888,69.330512128459901,17.812257542585328,16.043021761191387,0.16340785038967898,61.43019756923119,19.645485092575342,30.933865668872993,50.795004835041858,43.734374695147075,34.368585445918136,31.224439682749409,39.136363280316203,77.575860776317612,58.382514206071697,68.446466797031448,27.625474608503275,41.544686274913452,56.058088834397502,18.664508193420861,42.990809340650841,57.678819810971625,77.36608784335354,47.647221462490663,39.025270356796696,40.152894573596626,68.155799759551869,27.07605081920822,33.793715421731264,43.262966445957623,68.110566060058758,14.017866210391126,30.854889779972535,57.214079981980227,35.557529344223433,33.464372522818543,26.527047245763239,13.665699106641117,43.460507178679109,31.766120217119653,35.090803229250007,33.409595090585448,36.077720521328338,76.855217918443174,-2.8441948055600061,42.210717789518341,97.848602460386857,75.570868801635996,31.289979775125783,50.74892804492265,56.720714879532665,8.8868549481655137,36.225695071431488,49.037053673528135,66.133685270324335,31.642879035013415,74.326550468492016,56.909142381822072,41.239290159816548,-1.0542344534769632,11.331408807697388,5.7708950930585505,16.908259262951709,36.093429625034318,16.253838360620041,58.326044771820307,68.713704417459653,83.957306104712202,24.357003094628453,52.500055061342806,21.988985564870145,34.63847583935906,44.60785917006433,40.306110549718149,43.649909570813179,51.11385963701953,51.997616935210921,71.891228747554123,47.070731647933528,25.949161476455629,16.267745724568762,42.905360314374171,47.779975404652461,26.878729114929833,31.920597671220698,26.709063152472176,34.46869053101787,25.35332662363847,59.378417797076203,43.558404745223619,65.794779968758419,-2.4516485678031987,9.5224880815173147,43.290291881809637,58.000126314970359,86.193942522319659,34.825089173391454,52.627926819647342,17.556816268091396,50.918541991462305,22.737610791809864,42.784360170674823,59.744269264241055,16.56978097433845,73.424087942888349,68.854572532388062,23.472990607842807,2.0259126725917014,33.547831438481801,64.4424606518199,40.74830983765424,9.1260939820980003,59.286459917202592,68.248192043974981,73.634494058787823,14.984284850458305,47.786182835698135,35.180153894859046,18.719861437566571,31.843037668926019,41.147896239223584,58.768545159449182,32.665120484307408,63.702362133190036,2.0398214211066517,32.316078464500606,47.535574170760817,34.453830722098544,44.55418933338175,72.741358910376832,38.452353792575508,22.28278031107039,43.542166572685041,64.644989458223179,59.259402674312391,-0.12007999699562744,31.36715198090921,-1.3383425368616948,17.157254999813929,33.870006953366094,-0.23521759392072683,5.2270892867818528,25.176822904807825,42.746804382962488,7.6273172643656535,23.332636607810858,24.100158778019249,50.941700022667646,7.3868186290686335,23.270647274330262,41.668305193694934,38.898535288559906,60.189291757221021,22.42229651038846,57.984887585043907,55.254205617432802,31.999189802445471,42.827721661888063,3.1109090242534805,63.412898737005889,15.488671700780591,94.03651674278079,31.678000345515706,38.599630359870702,35.626824058902749,34.063965973133833,23.505789058593415,34.500627477342874,7.2165896153698377,58.06207304509978,-0.095564345829188824,-1.4335278949389823,32.886904571205378,18.888649983952433,40.518820687818035,24.394151094990473,5.2163158683106357,51.910188128240399,0.98854520358145059,56.944780151049301,18.068350084746871,47.228305445363134,30.614896112432085,34.460815119867519,60.169677712644138,24.472589952250324,2.8355882192651372,-2.7672586527963419,69.244878552854047,44.779028526196875,23.164133750833575,50.955070904456079,61.54594666169335,36.378777896364518,27.887729668679331,41.706582480110235,24.948195995142061,-1.1360659372682349,1.5075072335700161,8.3645427056277786,39.619806404225535,32.125430706267551,55.128865394120425,61.450857999734573,23.580772805338107,38.780606185706965,68.348112204112098,39.869654886424549,11.53556002614398,40.300192399881787,27.420562311696504,33.29431005753576,40.289180857750281,67.468075401460126,47.997579017343625,5.3597652120515757,30.782627190152805,2.8464683253938894,2.0634574815630868,30.05823517063012,3.2747262762859393,44.131148561524846,88.756829144743577,57.087381655971214,58.517309950354203,9.4427003804594243,43.323627910576761,30.797612971315782,67.526277393723518,30.713825946052872,51.790745835751295,15.355584300123155,16.667034363684554,43.206001631915569,32.623393585284546,44.144528134105101,11.236966249222549,31.913082608953118,25.961982870164015,51.265938452755407,10.063658258877689,14.061080166138712,49.831821519571044,39.717426490969963,40.906191199707493,65.138278221711516,25.798775372095406,41.869220946294568,33.879166161641471,22.341446016604706,38.535123056111246,50.927572189830244,40.122076578748732,30.705562170284491,59.08007429136584,51.564316853570439,67.163206194527433,42.448345449132226,30.31256436215093,47.919468364367887,55.023576991322152,8.5952568566426617,32.116280451106526,51.677538966760039,19.222938610861689,38.943875931824259,9.2036907592167427,-0.97861972947915188],\"y\":[1.0979291946627199,1.0969837036915124,1.1567112317308783,1.0619726991280913,1.1112960509955883,1.0104686838574708,1.0534609031863511,1.0954862809740007,0.96942382231354718,1.0148211177438498,0.88153500780463223,1.0926592359319329,0.97765658032149072,1.0178867619484664,1.1122283783741296,1.1028582471422852,0.85725048547610638,0.96488707968965171,0.85794146507978442,0.99032734623178842,0.86867179740220313,1.1028272198513149,1.1001846608705819,1.0907667322084307,0.91304545821622018,0.87897688234224913,1.0731317972764374,1.0669245430268348,0.83201650092378254,1.116184910852462,0.85981231015175585,1.0623884347267449,0.87723286878317597,1.127168510016054,0.96165194856002922,0.92045888807624576,0.94432722609490161,1.0921662037260831,1.1523138620890676,1.1283833690918983,1.0633678459562361,0.85692275743931534,0.90146652497351165,1.0816445747390389,1.1985472990199924,0.85069305673241613,0.88623223025351761,1.1573574930429458,1.1834376870654524,1.0166316218674183,0.9955233509652317,1.0789676357991993,0.86894129207357762,1.1623916392214597,1.1232428770512342,0.91588187078014016,0.96333705019205806,1.1773432922549545,0.98023755792528389,1.0243415889330207,1.0847414582036436,1.1544632933102548,0.80266943350434306,0.88526804493740197,0.9564416707493365,1.0175355361774563,0.81347507173195477,1.0105937098152935,0.84829714978113768,0.97980644199997191,0.96956294933333997,0.82141837254166605,1.1049111955799162,0.9157149900682271,1.0719368491321801,1.0044477886520327,1.117284231260419,0.86001456286758182,0.87744774753227828,1.0429672827944159,1.1973793601617218,0.8672066483646631,0.9905812718905509,0.88944528354331853,1.0904524927027524,0.87344191791489723,0.83183920383453369,1.0920489651151002,1.0446921986527742,0.88954611402004957,1.1828806611709297,0.96511093983426688,0.95066066337749366,0.9863399656489491,1.0648034094832837,1.0329941278323531,0.90553816547617316,1.0312203207984567,0.96868943730369206,0.85224493192508821,1.1546451650559901,1.1389281626790762,0.91754895793274049,0.84396981028839946,1.1678699932992458,0.99040336906909943,0.90873061800375576,0.83705950574949384,1.1108968425542116,0.83133251518011098,1.0912719991989435,0.83713279543444519,1.1595075602643192,0.92847039271146059,0.87757239202037451,0.84124893862754102,0.93630181476473806,1.0391155164688826,0.91270135352388027,1.1639972041361033,1.0639036676846445,0.82180693810805683,1.0369501248002053,0.99326732475310564,0.87236452437937262,1.0095156717114151,1.0829638226889073,1.1996121116913856,1.1980893094092608,1.1983114381320774,1.0120400131680072,1.1826509697362781,1.1550039724446832,0.90738727794960139,0.87611620100215082,1.040415870025754,0.83923746095970275,1.1733159171417356,0.85531182596459987,0.94311697585508225,1.1479111028835178,1.1418202918022871,0.86074802596122024,0.86542796650901432,0.83603020617738366,0.91139094531536102,0.98652081331238151,1.1134942758828401,0.80357747590169315,1.0040405243635178,0.82058033654466267,0.97799184294417496,0.91105191446840761,0.98900768989697097,0.94010138548910616,1.1866781585849822,1.0227980124764144,1.0654604695737362,0.87572752926498654,1.1311639279127121,0.92432161280885339,1.1145101937465369,1.0774054078385233,1.1596130979247392,1.0374779121018947,0.94792573126032953,0.92586366720497604,0.91576881939545274,0.99037378076463933,0.99959512688219543,0.9743287243880332,0.9003270386718214,0.98640173207968473,1.0448560602962971,1.0009818434715272,0.81114873196929693,1.1717942076735199,0.94268021043390038,1.0319005024619401,0.90285483477637174,1.1593183164484799,1.0101166773587464,1.0878486014902591,0.89174560206010933,1.0964060644619167,1.1634098106995225,0.85430938182398675,1.1867603247985243,1.158763059321791,1.1899292464368045,0.99669271940365434,0.96759183639660473,1.130274789687246,0.84275264553725715,0.87510252725332971,0.91491149291396145,1.0296214669011534,0.85627496065571906,1.166519520804286,1.1664403106085957,0.85149385984987025,0.93103288337588308,0.97943410277366638,0.96794830122962594,1.1416168813593686,0.88345722118392589,1.0856713788583874,0.87741034561768172,1.0951309193857015,1.0144188918173314,0.93317976072430608,0.88811493553221221,1.1219476573169231,1.1816989311948418,1.1666892950423062,1.0049542443826796,0.92898268587887289,0.85178028214722867,0.9090393204241991,0.99630142208188777,0.97737292535603049,1.1041472401469945,0.843678027857095,1.0843989407643675,1.0850048097781837,0.92327141622081399,0.86168025787919755,1.0790263852104545,1.1886130147613585,0.90143023421987889,0.99986738823354249,0.89828828945755956,1.0514483075588941,0.95378542151302104,0.88279734924435616,0.92036066865548494,1.1009497774764896,0.80049913590773936,1.1149323013611139,0.82403120184317236,1.0865572038106621,1.1603704055771231,0.92311155386269095,0.85853609507903461,1.0991279539652168,1.1501564822159707,1.0858959881588817,1.0174107254482805,0.89814857924357061,1.066843055281788,1.0251859573647379,0.89012558404356246,0.98832283932715659,1.1200713557191193,1.1006726478226483,0.95602907417342065,1.1142809130251408,1.1379512204788624,0.99354334659874444,1.0132406395860016,1.1589265700429678,1.0612692225724458,0.90111538888886566,0.88660798156633969,0.9474272602237761,1.0783609765581788,1.1609442788176239,1.1212495429441334,1.1401467519812285,0.92308843750506642,0.84573875898495321,0.93909919792786245,1.1461045781150461,1.1267089650034905,0.97106834696605804,1.0628609926439823,1.1576306909322738,1.0650653291493655,0.83335847090929749,0.92348756175488234,1.175434374809265,1.1425266922451556,0.98869986729696391,0.95630454448983071,1.1249584438279272,1.0335377046838403,0.92672087205573916,0.82690506447106604,0.80027346173301339,0.86712877107784148,1.1867134471423924,0.958758020401001,1.0534437361173332,1.0864632157608867,1.1082150647416711,0.8583326635882258,0.99181418307125568,1.1907238204963506,1.0549896473996341,1.1189809897914529,1.0117540705017745,1.0974502258002758,0.832629706338048,0.85845202757045624,0.86635459316894414,1.0038194919936358,1.1863230997696519,1.1850758690387011,1.182404557056725,0.97029316639527674,1.1514839256182312,1.1632288996130229,0.94078491060063241,0.89246678808704016,1.0051818695850669,1.1962729969061912,0.95571247590705755,1.0057855306193233,0.84912561904639006,0.83471553307026625,1.1406468108296395,1.1422839668579399,1.0079941115342081,0.9124077802523971,1.112088425643742,0.86597916455939417,0.97414033040404324,0.91235723253339529,1.1139552557840944,0.93418377740308645,1.1366647208109497,0.99348796196281908,1.057230875454843,1.1309557024389505,1.1379908923991024,0.98709545973688362,0.94108277680352326,0.94780277479439978,1.0201145789586008,0.93406297164037821,1.1605991271324456,0.9209755942225456,0.91862889435142281,1.0555603583343327,1.1577936344780029,1.1669165837578475,1.1967916774563492,1.1190043410286308,1.0984528702683747,1.1524088573642075,1.0275180596858262,1.0638926105573774,1.0372520717792213,0.91235981332138183,0.84963000677526002,0.82804199205711482,0.92828174587339163,0.81933021005243067,1.1870862110517919,0.86585220592096446,0.86424883967265487,0.94945964692160489,0.92857207916676998,0.96832081172615292,0.84647147525101896,1.1370080515742302,1.1609429742209614,1.0123045434243978,1.1423194668255747,1.1212919915094972,0.8404676653444767,0.81872691344469783,1.0643524277955294,1.0315800293348729,1.0921376463957131,0.9720499392598867,0.92587315523996949,1.0481316571123898,1.1423938439227641,1.0069652930833399,1.0841264432296156,0.84287747005000713,0.82323259143158789,0.80692396545782685,0.99519189661368723,1.0420413646847009,0.88686963729560375,0.94402013896033166,0.99474912108853464,0.88145276252180338,1.0507825673557818,0.8682740132324398,1.1661722710356117,0.82226979658007626,1.0245974601246417,1.0753517075441779,0.85348844509571786,1.0835515876300632,0.93586929766461258,1.1162585870362818,1.0786238735541702,1.1444220851175486,0.8340351690538228,0.92402200121432543,1.1864685570821165,0.81632625786587598,1.1115395528264345,0.8115474626421928,0.94239441715180872,0.80250943452119827,0.83113908134400849,0.933927942160517,1.0036496500484646,1.1458565545268358,1.1648002095520495,0.9032285688444972,0.94363435078412294,0.87328107189387083,0.84904869869351385,0.86559583786875005,1.0754868727177382,0.81824323758482931,1.0958037326112389,0.88208991158753636,0.81850055316463111,1.1935984810814262,0.85250408463180061,0.81211198111996052,1.0137205576524138,1.150525786075741,0.92206458766013388,0.92741566989570856,1.1275320867076517,1.0084242162294685,0.93329303292557597,0.80403911685571072,1.0730054680258037,1.160891430452466,1.1748181371949613,1.1468172076158225,1.0706463640555739,1.1832134443335236,0.96312520084902642,0.81243833992630243,1.1716129896230996,0.99300722433254118,0.95952355349436402,0.91018338948488231,1.0222933047451079,1.0426994578912854,0.98971948977559809,0.8716275580227375,0.98195681972429161,0.98011645348742604,0.87806199742481117,1.0835632482543587,0.81272179596126082,1.1235635758377611,1.1771890162490308,0.97157294768840075,0.97100084722042079,0.87314117792993784,1.0808953646570445,0.95502953678369518,1.1291637543588877,1.0089408837258815,1.0809148513711988,1.049487616121769,0.86464249733835463,0.85709393182769422,0.80768904853612189,0.88396808151155715,0.99005234446376567,1.1710291135124862,1.0287542551755906,1.1458075448870659,1.070652926247567,0.94089572997763748,0.9770567811094224,0.99083032784983516,0.91352300243452189,0.92397902989760039,1.0544127802364529,0.88889617528766396,0.85309552494436502,0.94064935240894554,0.99557113759219651,0.83446840355172758,1.0678444433026015,1.0515874118544162,0.97934582186862829,0.99959352221339937,1.1533210116438568,0.88566065626218915,0.98352528521791105,0.91043578917160628,1.1228774197399616,1.1726211457513274,0.95810570400208239,1.1725836507044733,0.85592043837532406,1.1236443060450256,1.1927558633498847,0.85936817834153767,1.041550765465945,0.97913140058517456,1.0799076228402555,1.1103432253934442,1.1126645027659834,0.80008279699832197,1.1691748174838721,0.96862622117623687,1.0391401041299104,0.9674205432645977,0.94657077379524712,0.97119186762720344,0.83774017216637731,0.85155337704345579,0.82831609016284347,0.82632503127679224,1.1498206544667482,0.81950134905055161,1.0368042666465045,0.9013963183388114,1.1413212871178984,0.86655811248347159,0.95101483212783933,0.98618657849729063,0.98854394201189277,0.85935708489269014,0.93979859417304401,0.98975444491952658,1.0946454429998993,1.1089680425822734,0.88770403768867256,0.91345976945012808,0.88887274982407694,1.0888263173401356,0.99688359405845406,0.90127898333594203,0.96013350542634723,0.83867158368229866,0.83329727230593564,0.8568970622494817,0.84699848135933276,0.88009637994691725,1.0615097817964851,0.84975341875106092,0.89875526549294593,0.91653591087087993,0.90061553511768577,1.0071427878923713,1.0548051433637737,0.89046626463532452,0.8739413870498538,1.1929300311021507,0.81450493745505814,0.90754226697608831,1.1143700658343731,1.1727375221438705,0.96629646252840762,1.1566224520094692,1.0108565776608884,1.1965198676101862,1.0311560101807118,1.1331997815519572,0.8042554610408843,0.89158876203000548,0.9383562004193664,0.96894071726128461,1.0482900329865514,1.0387599355541171,1.1438158418983222,1.0369718220084905,0.93506379667669537,1.0866858193650841,1.0088281431235373,0.89702789410948758,1.0098579569719732,0.99246487123891713,0.923325564712286,0.99853485105559225,0.90975756151601672,1.1618023392744363,0.96465109167620544,0.93901445213705304,1.0213701901957393,0.8671635318547487,1.199594112019986,1.0746551560238005,0.92119930293411012,0.82605873858556156,0.86965132672339673,0.9917653881013393,1.0914049409329891,1.1519901596009732,0.8198375490494072,0.81949369711801412,1.1279963796027004,1.0775141269899904,1.1344033483415843,1.1558603269979357,0.94314493583515291,1.1361888728104532,1.1744695668108762,0.88981610117480159,0.94482684936374428,0.84280720679089427,0.96725433114916082,1.144370383117348,1.1927587857469917,1.0495100413449108,0.84134153062477712,0.81957931602373724,1.1597246158868075,1.0948625792749227,1.0331046920269729,0.90217832233756778,1.161334333382547,0.82957680346444251,0.9182754435576499,0.95438735326752067,0.96111775310710068,1.0869281906634569,0.96473247371613979,0.87730731237679715,0.99095343444496398,0.80114973923191424,1.1587389846332372,0.80837303260341287,0.91312457518652079,0.93003950538113711,0.9480399460531771,1.1867894319817425,1.0756267804652453,1.0511595520190895,0.96048644511029124,1.1542862173169852,0.99321507699787615,0.89918707739561798,0.81266383202746506,0.89358673291280866,0.89825396658852696,1.1145152975805104,0.92750211516395209,1.1121055993251503,0.82299365000799296,1.0636390035040677,1.0314161509275437,1.0611063288524747,1.1300845614634454,0.85485333688557152,0.83130341842770572,0.94288817206397657,1.0339847018010915,1.0137307500466703,0.98452729256823657,0.93057860108092427,0.80826378855854275,0.95570145035162568,1.1241478208452462,0.99866974968463185,1.1122993511147796,1.1088377318345011,1.0615128203295172,0.94486159291118388,0.99545358857139943,1.1646589010022581,1.0647237928584219,1.1573205580934882,0.81569576207548378,0.80024748966097836,0.85780041413381691,0.90984517084434624,0.86491413274779916,0.89576900890097022,1.0536732121370733,1.0704396146349608,0.84615372819826007,1.1916242346167565,1.1440773136913776,1.0561155581846833,1.1782879314385355,1.0384384216740727,0.85905238743871448,1.1683547060005366,0.9213041365146637,0.88317667469382288,1.113028055615723,1.0179160959087312,1.181807170342654,0.97058919863775373,0.95923057300969961,1.1401715544983744,0.88087435662746427,1.0520421697758138,0.93023803513497116,1.0532562969252468,0.88662532791495319,0.80061831669881944,1.1738777438178658,1.0899098773486913,1.0857982161454856,1.1052687206305563,1.08763766894117,1.188989109173417,1.1914449893869459,1.0520302020013332,0.91226738234981897,0.99812336862087248,1.0679361897520721,0.99040272217243908,0.83157535949721928,0.97665788130834696,1.141597303096205,1.0886865735054017,1.0934736353345216,0.8364193210378289,0.89455646136775613,0.94031382640823724,0.8305808051489294,1.1797158340923488,0.81323652956634762,0.80657021012157204,0.97103070011362436,0.80698081199079752,1.022668201290071,1.0094263157807291,0.95333890840411184,0.89099963577464225,1.1847077494487166,0.96897407872602348,0.91234404826536775,1.1030417003668844,0.91128517091274264,1.113873206730932,0.85032226759940388,1.0464439049363137,0.8743232605047524,0.87946753678843381,1.1499587724916638,1.0249274415895342,1.0064947670325637,0.87926883585751059,0.9585628903470933,0.95139028169214723,0.88256685677915814,0.84596585100516675,0.88676711255684493,0.85636037951335309,1.1525234726257623,0.82684127185493705,0.88772123856469987,0.80208334466442466,1.1352095862850546,0.81880091922357678,0.9692409716546535,0.80887315962463613,1.0491355730220675,1.1107979025691748,1.0342346497811377,0.87694365503266458,0.98431136636063454,0.9674006110057235,0.92220242591574786,0.9204059265553951,0.90695150503888722,0.96345450039952996,0.94812324764207001,1.0894931268878281,0.88619111077860002,0.87041002977639437,1.0189654485322535,0.96884785844013099,1.1271264979615807,0.91489733410999174,0.90999741414561863,0.97100132927298544,1.140284721646458,1.0343751657754183,0.8407172711566091,1.0805550353601574,0.92053216267377136,1.1765912044793367,0.83638469623401757,0.92569742957130075,1.014857501257211,0.93021782916039231,1.0721088998019694,1.0874597107991577,1.1793757079169154,0.99125622687861326,1.1353632247075438,0.84982488835230474,0.89578126296401028,1.1493697915226222,1.1865514888428152,0.97928454978391533,1.0736810098402203,0.83837566701695321,1.0022422824054957,0.95420480379834771,1.182761588972062,0.95681576449424033,0.92576706595718861,0.99391398513689633,0.95701362434774639,0.87257556216791277,1.1063624675385655,1.1086404789239168,1.1987316675484181,0.85439012479037046,0.84302548561245205,1.0358767233788968,0.90060195904225115,1.0793061779811979,0.93455567592754962,0.8138743116520345,0.86910032685846095,0.82659177174791698,0.82736652791500087,0.81971851624548431,0.9561843663454056,1.0049915769137443,0.84519428694620724,1.1140908602625132,1.0873123452998699,0.81945318039506676,0.99877182152122257,0.97899006772786379,0.90722562354058023,0.80140952402725818,1.1519009816460311,1.0288890963420272,1.1795361790806056,0.99270602995529766,1.164583343360573,1.1982174664735794,1.1987398779951035,1.1544537410140037,0.83429092848673458,0.87287913858890531,0.84719219449907546,1.0928541450761258,1.1448248618282377,0.80087452614679933,0.82770084757357831,0.92172873420640822,1.022745248209685,1.1539512894116342,1.1532201832160354,1.1666233961470425,1.1398813008330761,1.1032456651329994,0.91320593245327475,0.97600350845605133,1.092669271118939,1.1755368115380407,1.0129830594174565,0.95376691818237302,0.94032689090818167,1.0254698903299868,1.1734464574605226,0.93647850351408124,1.1579142428934575,1.0518459593877196,0.9673689926043153,1.1120255476795138,0.85136716840788718,0.84159661848098044,0.80464032562449572,1.1434371644631027,1.0007247314788401,1.0500244547612965,0.97149489102885123,1.1823392669670283,0.82657259041443465,0.98991147819906478,0.89745919769629834,1.189228406175971,1.1020096377469599,1.0543767428956925,1.0274113341234625,0.81321771871298554,0.91678955946117635,0.98672188892960544,0.81150299292057748,1.0760395351797343,1.1075265334919095,1.0159905758686363,0.91603546533733604,0.84494421100243922,1.0578327955678106,0.92146933982148771,1.1678154202178122,1.1763482789508999,1.1821043615229427,0.90063608428463338,1.0764056708663703,0.96880656518042085,0.88229032624512915,1.1781446828506887,0.94030683645978574,1.1686411866918207,1.1190313543193042,1.1871621170081199,0.81367114400491114,1.1827886287122964,0.95737054403871302,1.0430377391166985,1.0359912060201169,1.0196967273019255,0.97826649565249679,1.1685047022998334,0.87665738221257927,1.1297705459408462,0.88944178074598312,0.85268541248515251,0.97475561778992414,1.1831193654797971,1.0681860673241317,0.97366701383143661,1.1831912668421865,1.141935770586133,0.91862701978534456,0.97428385466337208,1.0246281336992979,0.83068042872473602,1.1091888319700955,0.82629133975133295,1.0325445964001119,1.1349677765741943,0.81835732487961654,1.1300096279010177],\"text\":[\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador: 100.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador: 100.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  91.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  91.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador: 100.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  83.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  75.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  91.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  91.666667<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  25.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  66.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  58.333333<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:  33.333333<br />colour: \",\"x: <br />indicador:  50.000000<br />colour: \",\"x: <br />indicador:  16.666667<br />colour: \",\"x: <br />indicador:  41.666667<br />colour: \",\"x: <br />indicador:   8.333333<br />colour: \",\"x: <br />indicador:   0.000000<br />colour: \"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"opacity\":1,\"size\":5.6692913385826778,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"legendgroup\":\"\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":46.046948356807512,\"r\":7.3059360730593621,\"b\":42.46703968100843,\"l\":10.958904109589042},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Indicador\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-8.5250135270568155,106.40310798538849],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"25\",\"50\",\"75\",\"100\"],\"tickvals\":[0,25,49.999999999999993,75,100],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"25\",\"50\",\"75\",\"100\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716894984},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Index\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,1.6000000000000001],\"tickmode\":\"array\",\"ticktext\":[\"\"],\"tickvals\":[1],\"categoryorder\":\"array\",\"categoryarray\":[\"\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":false,\"tickfont\":{\"color\":null,\"family\":null,\"size\":0},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716894984},\"title\":{\"text\":\"colour\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"6a9c35059cc\":{\"x\":{},\"y\":{},\"colour\":{},\"type\":\"box\"},\"6a9c77f35cdd\":{\"x\":{},\"y\":{},\"colour\":{}}},\"cur_data\":\"6a9c35059cc\",\"visdat\":{\"6a9c35059cc\":[\"function (y) \",\"x\"],\"6a9c77f35cdd\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nFigure 1: Indicador (Latinobarometro 2020).\n:::\n\n```{.r .cell-code}\n# HIST:\nggplot(peru_data, aes(x = indicador, color = \"\")) + \n  geom_histogram(fill = \"white\", alpha = 0.5, position = \"identity\", bins = 30) +  #agregar bins = 30 o breaks=seq()\n    labs(title =\"Indicador\", y = \"\", x=\"Index\", subtitle = \"\", caption = \"Fuente: Latinobarometro 2020. Elaboración propia.\")+\n    theme(plot.title = element_text(hjust = 0.5)) + \n    theme(panel.background=element_rect(fill = \"white\", colour = \"white\"))\n```\n\n::: {.cell-output-display}\n![Figure 1: Indicador (Latinobarometro 2020).](s8-ejercicio-parcial-semana8_files/figure-html/unnamed-chunk-20-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n  - AQUÍ HACEMOS T.TEST SOLO CON LA VARIABLE NUMERICA, PUES NOS DA EL PROMEDIO y el intervalo de confianza--> lo que nos solicita la pregunta RA:\n\n#Otra forma es más larga\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(peru_data$indicador)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  peru_data$indicador\nt = 53.998, df = 933, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 35.61263 38.29886\nsample estimates:\nmean of x \n 36.95575 \n```\n:::\n:::\n\n\n## **INTERPRETACIÓN**:\n\n  + La distribución de la variables nos reporta que el indicador de confianza  (0-100) es ….., muestra una distribución asimétrica hacia la derecha, es decir, hay mayor concentración de casos en los valores menores.\n\n#El promedio de la confianza es de 36.92. A un 95% de nivel de confianza, el promedio oscila entre 35.58 puntos y 38.25 puntos. #(puntos pues hablamos del indicador!!!)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nPregunta 4 (5 puntos)\n============================================================\n•\tResponda si existe diferencia de promedios del indicador de CONFIANZA INSTITUCIONAL DE ORGANIZACIONES DE LA SOCIEDAD CIVIL con respecto a sexo, ideología política (izquierda, centro y derecha) y grupos de edad (jóvenes, adultos, adultos mayores). Elabore un balance general de las diferencias. (5 puntos)\n\n#tenemos que haces estos pasos con cada variable (se usará diferentes pruebas):\n\n#Identificamos: Indicador de confianza (Variable Numérica) - Sexo (Nominal dicotómica). Entonces, usamos La prueba es el T-test. \nPrimero con sexo:\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(indicador ~ SEXO, data = peru_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  indicador by SEXO\nt = 1.6403, df = 923.72, p-value = 0.1013\nalternative hypothesis: true difference in means between group Hombre and group Mujer is not equal to 0\n95 percent confidence interval:\n -0.4408926  4.9300446\nsample estimates:\nmean in group Hombre  mean in group Mujer \n            38.01555             35.77098 \n```\n:::\n:::\n\n#INTERPRETACIÓN:\n#H0: No existe diferencia significativa del promedio de confianza institucional entre hombres y mujeres.\n#Verifico el p-valor que es 0.08. No rechazo la hipótesis nula.\n\n##A un nivel de confianza del 95%, se podría indicar que no existe diferencia significativa entre los promedios de confianza institucional entre hombres y mujeres. El promedio de hombres es 38.02 y mujeres es 35.69 puntos. El intervalo de confianza de la diferencia de promedios oscila entre -0.34 y 4.99, es decir, que puede tomar el valor 0, no hay diferencia. \n\n#CUANDO EL NIVEL DE CONFIANZA ES DEL 95%.\n    #RECHAZO LA H0, CUANDO EL P-VALOR ES MENOR QUE 0.05\n    #NO RECHAZO LA H0,  CUANDO EL P-VALOR ES MAYOR QUE 0.05\n\n#CUANDO EL NIVEL DE CONFIANZA ES DEL 90%.\n    #RECHAZO LA H0, CUANDO EL P-VALOR ES MENOR QUE 0.1\n    #NO RECHAZO LA H0,  CUANDO EL P-VALOR ES MAYOR QUE 0.1\n\n#CUANDO EL NIVEL DE CONFIANZA ES DEL 99%.\n    #RECHAZO LA H0, CUANDO EL P-VALOR ES MENOR QUE 0.01\n    #NO RECHAZO LA H0,  CUANDO EL P-VALOR ES MAYOR QUE 0.01\n\n\n\n\n\n\n\n\n## Ahora con ideología política (P18ST). En el cuestionario está del 0 al 10. Entonces, tenemos que recodificar\n\n# Identificamos que el Indicador de confianza (Variable Numérica)- ideología política (Nominal polinómica), por tanto, usaremos la prueba bivariada es la prueba ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(peru_data$P18ST)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  0   1   2   3   4   5   6   7   8   9  10  97 \n 66  38  51  53  71 330  81  54  45  12  66  36 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nperu_data$Ideologia=recode(peru_data$P18ST, \n                           \"0:3 = 'Izquierda'; 4:6 = 'Centro'; 7:10 = 'Derecha'; 97= NA\")\ntable(peru_data$Ideologia)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Centro   Derecha Izquierda \n      482       177       208 \n```\n:::\n:::\n\n  - Advertimos NA's y borramos:\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(peru_data$Ideologia))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 67\n```\n:::\n\n```{.r .cell-code}\nperu_data = peru_data[complete.cases(peru_data$Ideologia), ]\n```\n:::\n\n\n\n#En este caso tenemos que hacer la prueba anova:\n\n::: {.cell}\n\n```{.r .cell-code}\nanova1 = aov(indicador ~ Ideologia, data = peru_data)\nsummary(anova1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \nIdeologia     2   6015  3007.3   7.052 0.000916 ***\nResiduals   864 368430   426.4                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#H0: No existe diferencia significativa del promedio de Confianza de acuerdo a la ideología política de las personas.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(anova1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = indicador ~ Ideologia, data = peru_data)\n\n$Ideologia\n                        diff        lwr       upr     p adj\nDerecha-Centro     0.8436482  -3.417294  5.104590 0.8877537\nIzquierda-Centro  -5.8939116  -9.915915 -1.871908 0.0017604\nIzquierda-Derecha -6.7375598 -11.695316 -1.779804 0.0041958\n```\n:::\n:::\n\n\n##  **BOXPLOT**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(plotly)\nboxplot <- ggplot(peru_data, aes(y = indicador, \n                                 x = Ideologia,fill=factor(Ideologia))) +\ngeom_boxplot() + xlab(\"Ideologia\") + ylab(\"Indicador\")\n\nggplotly(boxplot)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-7c33d1f13b9ee6586d34\" style=\"width:100%;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7c33d1f13b9ee6586d34\">{\"x\":{\"data\":[{\"x\":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],\"y\":[33.333333333333329,33.333333333333329,58.333333333333336,25,41.666666666666671,16.666666666666664,8.3333333333333321,41.666666666666671,75,66.666666666666657,50,0,41.666666666666671,50,83.333333333333343,33.333333333333329,58.333333333333336,0,50,41.666666666666671,25,83.333333333333343,0,8.3333333333333321,8.3333333333333321,25,25,50,41.666666666666671,25,16.666666666666664,58.333333333333336,33.333333333333329,58.333333333333336,50,0,50,50,25,8.3333333333333321,33.333333333333329,33.333333333333329,33.333333333333329,66.666666666666657,16.666666666666664,58.333333333333336,66.666666666666657,25,33.333333333333329,33.333333333333329,66.666666666666657,66.666666666666657,66.666666666666657,66.666666666666657,83.333333333333343,66.666666666666657,25,58.333333333333336,50,75,50,8.3333333333333321,50,41.666666666666671,50,58.333333333333336,25,83.333333333333343,33.333333333333329,83.333333333333343,50,50,41.666666666666671,33.333333333333329,41.666666666666671,0,16.666666666666664,8.3333333333333321,16.666666666666664,58.333333333333336,0,33.333333333333329,25,8.3333333333333321,33.333333333333329,33.333333333333329,66.666666666666657,33.333333333333329,25,50,50,41.666666666666671,0,25,41.666666666666671,16.666666666666664,25,75,50,50,66.666666666666657,25,33.333333333333329,83.333333333333343,50,66.666666666666657,16.666666666666664,50,16.666666666666664,33.333333333333329,16.666666666666664,25,66.666666666666657,50,75,58.333333333333336,33.333333333333329,33.333333333333329,8.3333333333333321,25,25,41.666666666666671,66.666666666666657,33.333333333333329,50,0,16.666666666666664,50,25,50,33.333333333333329,66.666666666666657,41.666666666666671,50,50,33.333333333333329,25,50,50,41.666666666666671,25,33.333333333333329,66.666666666666657,41.666666666666671,8.3333333333333321,50,16.666666666666664,50,33.333333333333329,58.333333333333336,41.666666666666671,33.333333333333329,50,41.666666666666671,8.3333333333333321,25,33.333333333333329,16.666666666666664,83.333333333333343,33.333333333333329,16.666666666666664,58.333333333333336,66.666666666666657,58.333333333333336,50,0,66.666666666666657,33.333333333333329,25,16.666666666666664,33.333333333333329,0,75,16.666666666666664,25,50,8.3333333333333321,41.666666666666671,41.666666666666671,50,0,66.666666666666657,41.666666666666671,16.666666666666664,66.666666666666657,41.666666666666671,58.333333333333336,41.666666666666671,41.666666666666671,33.333333333333329,25,58.333333333333336,16.666666666666664,41.666666666666671,50,41.666666666666671,0,16.666666666666664,16.666666666666664,50,25,33.333333333333329,41.666666666666671,41.666666666666671,33.333333333333329,41.666666666666671,0,33.333333333333329,41.666666666666671,33.333333333333329,16.666666666666664,75,16.666666666666664,33.333333333333329,16.666666666666664,58.333333333333336,33.333333333333329,33.333333333333329,0,33.333333333333329,25,8.3333333333333321,50,25,41.666666666666671,58.333333333333336,50,33.333333333333329,75,58.333333333333336,16.666666666666664,83.333333333333343,66.666666666666657,8.3333333333333321,66.666666666666657,33.333333333333329,75,25,75,41.666666666666671,33.333333333333329,75,41.666666666666671,66.666666666666657,41.666666666666671,33.333333333333329,25,33.333333333333329,58.333333333333336,16.666666666666664,41.666666666666671,58.333333333333336,75,50,58.333333333333336,16.666666666666664,66.666666666666657,25,58.333333333333336,41.666666666666671,41.666666666666671,16.666666666666664,33.333333333333329,33.333333333333329,33.333333333333329,25,25,66.666666666666657,66.666666666666657,33.333333333333329,66.666666666666657,25,50,75,41.666666666666671,25,75,33.333333333333329,66.666666666666657,91.666666666666657,83.333333333333343,33.333333333333329,33.333333333333329,58.333333333333336,41.666666666666671,8.3333333333333321,58.333333333333336,41.666666666666671,0,50,25,33.333333333333329,41.666666666666671,25,50,41.666666666666671,41.666666666666671,25,33.333333333333329,25,0,16.666666666666664,33.333333333333329,25,33.333333333333329,50,75,66.666666666666657,33.333333333333329,16.666666666666664,25,33.333333333333329,50,66.666666666666657,50,50,33.333333333333329,41.666666666666671,0,33.333333333333329,50,41.666666666666671,0,58.333333333333336,58.333333333333336,91.666666666666657,33.333333333333329,25,25,25,33.333333333333329,33.333333333333329,25,33.333333333333329,16.666666666666664,8.3333333333333321,33.333333333333329,16.666666666666664,41.666666666666671,16.666666666666664,58.333333333333336,50,75,41.666666666666671,33.333333333333329,33.333333333333329,75,33.333333333333329,25,41.666666666666671,66.666666666666657,58.333333333333336,33.333333333333329,50,66.666666666666657,50,41.666666666666671,50,33.333333333333329,25,66.666666666666657,0,33.333333333333329,16.666666666666664,83.333333333333343,0,25,25,8.3333333333333321,8.3333333333333321,25,16.666666666666664,25,41.666666666666671,41.666666666666671,58.333333333333336,0,66.666666666666657,58.333333333333336,33.333333333333329,41.666666666666671,41.666666666666671,66.666666666666657,33.333333333333329,33.333333333333329,33.333333333333329,41.666666666666671,33.333333333333329,41.666666666666671,33.333333333333329,33.333333333333329,33.333333333333329,58.333333333333336,75,100,33.333333333333329,66.666666666666657,41.666666666666671,33.333333333333329,8.3333333333333321,58.333333333333336,33.333333333333329,58.333333333333336,16.666666666666664,66.666666666666657,25,0,0,66.666666666666657,33.333333333333329,50,50,58.333333333333336,25,16.666666666666664,16.666666666666664,50,41.666666666666671,41.666666666666671,50,58.333333333333336,33.333333333333329,16.666666666666664,50,66.666666666666657,41.666666666666671,8.3333333333333321,41.666666666666671,25,33.333333333333329,41.666666666666671,41.666666666666671,41.666666666666671,25,33.333333333333329,16.666666666666664,0,33.333333333333329,41.666666666666671,41.666666666666671,50,25,33.333333333333329,41.666666666666671,25,50,33.333333333333329,16.666666666666664,25,33.333333333333329,41.666666666666671,8.3333333333333321,33.333333333333329,25,50,33.333333333333329,16.666666666666664,50,41.666666666666671,41.666666666666671,50,58.333333333333336,41.666666666666671,33.333333333333329,25,41.666666666666671,50,16.666666666666664,58.333333333333336,50,8.3333333333333321,41.666666666666671,33.333333333333329,50,58.333333333333336,8.3333333333333321,16.666666666666664,50,16.666666666666664,41.666666666666671,50,58.333333333333336],\"hoverinfo\":\"y\",\"type\":\"box\",\"fillcolor\":\"rgba(248,118,109,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.6692913385826778},\"line\":{\"color\":\"rgba(51,51,51,1)\",\"width\":1.8897637795275593},\"name\":\"Centro\",\"legendgroup\":\"Centro\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],\"y\":[41.666666666666671,0,0,41.666666666666671,41.666666666666671,33.333333333333329,8.3333333333333321,41.666666666666671,33.333333333333329,0,25,50,83.333333333333343,41.666666666666671,25,50,41.666666666666671,16.666666666666664,25,41.666666666666671,41.666666666666671,50,33.333333333333329,0,66.666666666666657,33.333333333333329,50,33.333333333333329,50,100,25,41.666666666666671,33.333333333333329,33.333333333333329,41.666666666666671,75,66.666666666666657,16.666666666666664,33.333333333333329,66.666666666666657,50,41.666666666666671,16.666666666666664,58.333333333333336,16.666666666666664,33.333333333333329,66.666666666666657,41.666666666666671,25,33.333333333333329,50,33.333333333333329,16.666666666666664,33.333333333333329,58.333333333333336,33.333333333333329,41.666666666666671,16.666666666666664,33.333333333333329,41.666666666666671,25,50,50,33.333333333333329,75,50,66.666666666666657,41.666666666666671,33.333333333333329,16.666666666666664,41.666666666666671,58.333333333333336,16.666666666666664,75,33.333333333333329,0,83.333333333333343,50,0,66.666666666666657,25,25,50,33.333333333333329,50,25,58.333333333333336,41.666666666666671,41.666666666666671,33.333333333333329,0,58.333333333333336,50,33.333333333333329,8.3333333333333321,75,100,33.333333333333329,83.333333333333343,66.666666666666657,66.666666666666657,50,66.666666666666657,33.333333333333329,83.333333333333343,16.666666666666664,41.666666666666671,75,33.333333333333329,25,25,41.666666666666671,16.666666666666664,33.333333333333329,66.666666666666657,58.333333333333336,0,83.333333333333343,0,66.666666666666657,41.666666666666671,25,25,33.333333333333329,58.333333333333336,58.333333333333336,8.3333333333333321,41.666666666666671,33.333333333333329,66.666666666666657,41.666666666666671,33.333333333333329,50,25,0,58.333333333333336,8.3333333333333321,33.333333333333329,50,83.333333333333343,41.666666666666671,50,8.3333333333333321,16.666666666666664,8.3333333333333321,33.333333333333329,16.666666666666664,41.666666666666671,50,41.666666666666671,41.666666666666671,75,16.666666666666664,75,50,41.666666666666671,50,25,50,25,0,33.333333333333329,16.666666666666664,25,0,8.3333333333333321,41.666666666666671,33.333333333333329,50,50,50,41.666666666666671,58.333333333333336,58.333333333333336,41.666666666666671,50,41.666666666666671],\"hoverinfo\":\"y\",\"type\":\"box\",\"fillcolor\":\"rgba(0,186,56,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.6692913385826778},\"line\":{\"color\":\"rgba(51,51,51,1)\",\"width\":1.8897637795275593},\"name\":\"Derecha\",\"legendgroup\":\"Derecha\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3],\"y\":[16.666666666666664,66.666666666666657,0,16.666666666666664,33.333333333333329,33.333333333333329,33.333333333333329,41.666666666666671,41.666666666666671,58.333333333333336,8.3333333333333321,50,50,25,41.666666666666671,16.666666666666664,33.333333333333329,41.666666666666671,33.333333333333329,41.666666666666671,50,33.333333333333329,33.333333333333329,41.666666666666671,33.333333333333329,25,25,16.666666666666664,50,25,25,25,33.333333333333329,8.3333333333333321,41.666666666666671,16.666666666666664,8.3333333333333321,33.333333333333329,33.333333333333329,41.666666666666671,25,50,50,33.333333333333329,50,41.666666666666671,33.333333333333329,58.333333333333336,41.666666666666671,0,50,41.666666666666671,0,16.666666666666664,33.333333333333329,41.666666666666671,66.666666666666657,41.666666666666671,16.666666666666664,16.666666666666664,50,0,41.666666666666671,8.3333333333333321,33.333333333333329,50,33.333333333333329,25,8.3333333333333321,25,33.333333333333329,25,25,25,16.666666666666664,16.666666666666664,33.333333333333329,58.333333333333336,50,0,66.666666666666657,58.333333333333336,50,25,0,33.333333333333329,0,25,75,58.333333333333336,41.666666666666671,75,25,25,16.666666666666664,8.3333333333333321,8.3333333333333321,58.333333333333336,41.666666666666671,41.666666666666671,66.666666666666657,16.666666666666664,25,33.333333333333329,50,41.666666666666671,83.333333333333343,50,41.666666666666671,16.666666666666664,0,75,16.666666666666664,33.333333333333329,25,66.666666666666657,33.333333333333329,0,50,25,33.333333333333329,33.333333333333329,16.666666666666664,50,8.3333333333333321,8.3333333333333321,50,16.666666666666664,66.666666666666657,33.333333333333329,33.333333333333329,58.333333333333336,58.333333333333336,16.666666666666664,33.333333333333329,66.666666666666657,8.3333333333333321,0,50,66.666666666666657,0,58.333333333333336,8.3333333333333321,33.333333333333329,8.3333333333333321,58.333333333333336,0,66.666666666666657,0,91.666666666666657,25,41.666666666666671,0,25,0,58.333333333333336,41.666666666666671,41.666666666666671,0,0,16.666666666666664,16.666666666666664,25,16.666666666666664,58.333333333333336,66.666666666666657,50,58.333333333333336,41.666666666666671,33.333333333333329,0,25,8.3333333333333321,41.666666666666671,25,8.3333333333333321,33.333333333333329,16.666666666666664,33.333333333333329,0,8.3333333333333321,25,16.666666666666664,58.333333333333336,8.3333333333333321,25,66.666666666666657,0,66.666666666666657,25,25,33.333333333333329,50,50,91.666666666666657,33.333333333333329,41.666666666666671,50,66.666666666666657,66.666666666666657,0,0,25,0,25,41.666666666666671,66.666666666666657,41.666666666666671],\"hoverinfo\":\"y\",\"type\":\"box\",\"fillcolor\":\"rgba(97,156,255,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.6692913385826778},\"line\":{\"color\":\"rgba(51,51,51,1)\",\"width\":1.8897637795275593},\"name\":\"Izquierda\",\"legendgroup\":\"Izquierda\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283104,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":43.105022831050235},\"plot_bgcolor\":\"rgba(235,235,235,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,3.6000000000000001],\"tickmode\":\"array\",\"ticktext\":[\"Centro\",\"Derecha\",\"Izquierda\"],\"tickvals\":[1,2,3],\"categoryorder\":\"array\",\"categoryarray\":[\"Centro\",\"Derecha\",\"Izquierda\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Ideologia\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-5,105],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"25\",\"50\",\"75\",\"100\"],\"tickvals\":[0,24.999999999999996,50,75,100],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"25\",\"50\",\"75\",\"100\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Indicador\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"factor(Ideologia)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"6a9c69fc49e5\":{\"x\":{},\"y\":{},\"fill\":{},\"type\":\"box\"}},\"cur_data\":\"6a9c69fc49e5\",\"visdat\":{\"6a9c69fc49e5\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gplots)\nplotmeans(indicador ~ Ideologia, data = peru_data, \n          p = 0.95, \n          main= \"Mean Plot \\n with 95% CI\")\n```\n\n::: {.cell-output-display}\n![](s8-ejercicio-parcial-semana8_files/figure-html/prueba-1.png){width=100%}\n:::\n:::\n\n\n## **INTEEPRETACIÓN**:\n\n  + A nivel de confianza del 95%, se podría afirmar que existe diferencia significativa del promedio de Confianza de acuerdo a la ideología política de las personas. De acuerdo a la prueba Tukey, se observa que existe diferencia entre los promedios de las personas con tendencia política de centro con las de izquierda (), y a su vez, las personas de izquierda con las de ideología de derecha. \n\n\nAhora con\n-\tIndicador de confianza (Variable Numérica)- Grupos de edad ( Ordinal) La prueba bivariada es la prueba ANOVA.\n\n\n\n\n\n\n\n\nPregunta 5 (2 puntos)\n============================================================\n#¿Existe alguna relación entre su evaluación de la actual situación económica (P5STGBS) y su satisfacción con la democracia (P11STGBS.A)?\n\n#Haremos\n#Dos variables ordinales … Prueba Chi-cuadrado\n#Definir el tipo de relación: Simétrica \n#Sentido y la intensidad (Gamma)\n\n\n\n\n\n\nPregunta 6 (2 puntos)\n============================================================\n¿Existe asociación entre la formar parte de un grupo discriminado (P57ST) y la percepción de probabilidad de sufrir repercusiones por opiniones políticas? (P60N.B) Si es así, describa la asociación.\n\n#Haremos\n#Prueba Chi-cuadrado\n#Definir el tipo de relación: Asimétrica \n#Intensidad\n\n  - Viendo el cuestionario y su estructura:\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(peru_data$P57ST) # Nominal <- variable independiente\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:867] 2 2 2 1 2 2 2 1 2 2 ...\n```\n:::\n\n```{.r .cell-code}\nstr(peru_data$P60N.B) # Nominal sí, no, NS/NR <- variable dependiente\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:867] 2 2 1 1 2 1 1 2 1 NA ...\n```\n:::\n:::\n\n  - Formateo:\n\n::: {.cell}\n\n```{.r .cell-code}\nperu_data$P57ST = as.factor(peru_data$P57ST) \nperu_data$P57ST = factor(peru_data$P57ST,\n                 levels = levels(peru_data$P57ST),\n                 labels = c(\"Sí\",\"No\"),\n                 ordered = F)\n#table(peru_data$P57ST)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nperu_data$P60N.B = as.factor(peru_data$P60N.B) \nperu_data$P60N.B = factor(peru_data$P60N.B,\n                 levels = levels(peru_data$P60N.B),\n                 labels = c(\"Sí\",\"No\"),\n                 ordered = F)\ntable(peru_data$P60N.B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Sí  No \n526 326 \n```\n:::\n:::\n\n\n- Advertimos NA's y borramos:\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(peru_data$P57ST)) # Borrar 6 NA's\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n\n```{.r .cell-code}\nperu_data = peru_data[complete.cases(peru_data$P57ST), ]\n\nsum(is.na(peru_data$P60N.B)) # 15 NA's\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 15\n```\n:::\n\n```{.r .cell-code}\nperu_data = peru_data[complete.cases(peru_data$P60N.B), ]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naddmargins(table(peru_data$P57ST, peru_data$P60N.B))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     \n       Sí  No Sum\n  Sí  140  53 193\n  No  381 272 653\n  Sum 521 325 846\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(peru_data$P57ST, peru_data$P60N.B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  peru_data$P57ST and peru_data$P60N.B\nX-squared = 12.091, df = 1, p-value = 0.0005066\n```\n:::\n:::\n\n\n\n\n\n\n\n\nPregunta 7 (2 puntos)\n============================================================\n•\t ¿Existe asociación entre la percepción de garantía de justa distribución de la riqueza (P47ST.F)  y la clase social (S1)? Si es así, describa la asociación.\n\n#haremos\n#Prueba Chi-cuadrado\n#Definir el tipo de relación: Asimétrica \n#Intensidad\n\n  - Viendo el cuestionario y su estructura:\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(peru_data$P47ST.F) #  Ordinal <- variable independiente\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:846] 3 4 1 3 3 3 2 3 2 3 ...\n```\n:::\n\n```{.r .cell-code}\nstr(peru_data$S1) # Nominal sí, no, NS/NR <- variable dependiente\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:846] 3 5 4 3 5 3 5 4 4 5 ...\n```\n:::\n:::\n\n\n  - Formateo:\n  \n\n::: {.cell}\n\n```{.r .cell-code}\n#table(peru_data$P47ST.F)\nlibrary(car)\nperu_data$P47ST.F = recode(peru_data$P47ST.F, \n                           \"1= 4; 2= 3; 3= 2; 4= 1\") # Recodificando\n#table(peru_data$P47ST.F)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nperu_data$S1[peru_data$S1 == 8]= NA # Revisando el codebook, encontramos que se ha digitado un numero 8, mejor lo convertimos NA y luego lo eliminamos.\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(peru_data$S1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4   5 \n 17  65 310 237 196 \n```\n:::\n\n```{.r .cell-code}\nlibrary(car)\nperu_data$S1 = recode(peru_data$S1, \n                           \"1= 5; 2= 4; 3= 3; 4= 2; 5 = 1\" ) # Recodificando\ntable(peru_data$S1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4   5 \n196 237 310  65  17 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nperu_data$P47ST.F = as.factor(peru_data$P47ST.F) \nperu_data$P47ST.F = factor(peru_data$P47ST.F,\n                 levels = levels(peru_data$P47ST.F),\n                 labels = c(\"garantizada\",\"algo\", \"poco\", \"para_nada\"),\n                 ordered = T)\ntable(peru_data$P47ST.F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\ngarantizada        algo        poco   para_nada \n         98         368         294          84 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nperu_data$S1 = as.factor(peru_data$S1) \nperu_data$S1 = factor(peru_data$S1,\n                 levels = levels(peru_data$S1),\n                 labels = c(\"alta\",\"media_alta\", \"media\", \"media_baja\", \"baja\"),\n                 ordered = T)\ntable(peru_data$S1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n      alta media_alta      media media_baja       baja \n       196        237        310         65         17 \n```\n:::\n:::\n\n\n  - Advertimos NA's y borramos:\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(peru_data$P47ST.F)) # Borrar 2 NA's\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2\n```\n:::\n\n```{.r .cell-code}\nperu_data = peru_data[complete.cases(peru_data$P47ST.F), ]\n\n\nsum(is.na(peru_data$S1)) # 21 NA's\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21\n```\n:::\n\n```{.r .cell-code}\nperu_data = peru_data[complete.cases(peru_data$S1), ]\n```\n:::\n",
    "supporting": [
      "s8-ejercicio-parcial-semana8_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\r\n<script src=\"site_libs/plotly-binding-4.10.4/plotly.js\"></script>\r\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\r\n<link href=\"site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}