{
  "hash": "2cda745a848dd1892be63e07480508f8",
  "result": {
    "markdown": "---\naliases:\n  - ejercicio-semana10.html\n---\n\n\n# Correlación\n\nAbrir la base de datos\n\nImporta la base de datos a R. Recuerda que si termina en .dta proviene de stata, si termina con .xslx proviene de excel\n\n#### Más información del paquete rio en el siguiente link: <https://www.rdocumentation.org/packages/rio/versions/0.5.16>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#setwd(\" \")\n\nlibrary(\"rio\")\ndata <- import(\"./data/s10/PVotos_CirElectoral_idh.xlsx\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Distrito.electoral\" \"IDH\"                \"Evida\"             \n [4] \"EduCom\"             \"Aeduca\"             \"IngresoPer\"        \n [7] \"VotosV_Castillo\"    \"VotosV_Keiko\"       \"VotosV_Aliaga\"     \n[10] \"VotosV_De_Soto\"     \"VotosV_Mendoza\"     \"Votos_no_validos\"  \n```\n:::\n:::\n\n\n#### Realizo la prueba de normalidad para definir si empleo Pearson o Spearman . Recordar que cuando el número de casos es menor a 121 , utilizo la prueba de Spearman.\n\nla H0 de la prueba de normalidad: HAY NORMALIDAD\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Hipótesis de normalidad: la variable se distribuye normalmente\nlibrary(nortest)\nshapiro.test(data$IDH)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  data$IDH\nW = 0.97142, p-value = 0.6605\n```\n:::\n\n```{.r .cell-code}\nshapiro.test(data$VotosV_Castillo)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  data$VotosV_Castillo\nW = 0.92945, p-value = 0.07519\n```\n:::\n\n```{.r .cell-code}\nshapiro.test(data$VotosV_De_Soto)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  data$VotosV_De_Soto\nW = 0.89647, p-value = 0.01307\n```\n:::\n:::\n\n  - IDH\n+ Con respecto a la prueba de normalidad shapiro wilk de la variable IDH, el p-value (0.6605) es mayor a 0.05, por tanto, aceptamos la H0 y concluimos que la variable edad presenta una distribución normal.\n\n  - Castillo\n+ Con respecto a la prueba de normalidad shapiro wilk de la variable (VotosV_Castillo), el p-value (0.07519) es mayor a 0.05, por tanto, aceptamos la H0 y concluimos que la variable edad presenta una distribución normal.\n\n  - De Doto \n+ Con respecto a la prueba de normalidad Kolmogorov smirnov de la variable edad, el p-value (0.01307) es menor a 0.05, por tanto, rechazamos la H0 y concluimos que la variable (VotosV_De_Soto) no presenta una distribución normal.\n\n\n### Prueba de correlación (EL MéTODO SE PRECISA EN LA PRUEBA DE CORRELACION)\n\nEN CASTILLO, LA HO: NO EXISTE CORRELACION \n\n-> CORT TEST - VARIABLE X - VARIABLE Y - EL METODO\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(data$IDH, data$VotosV_Castillo, method = c(\"pearson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  data$IDH and data$VotosV_Castillo\nt = -2.8874, df = 24, p-value = 0.008096\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.7479941 -0.1498866\nsample estimates:\n       cor \n-0.5077587 \n```\n:::\n:::\n\n#INTERPRETACIÓN: \n  + Al revisar el P-value (0.008096), el cual es menor a 0.05, rechazamos la H0 y, por tanto, aceptamos la H1. A un 95% del nivel de confianza, sí parece existir una relación entre las variables IDH Y EL PORCENTAJE DE VOTO A PEDRO CASTILLO.\n  \n*--> O HAY EVIDENCIA ESTADISTICA SUFICIEnTE PARA AFIRMAR O NO LA HAY PARA NEGAR LA RELACION.*\n\n+ El Coeficiente de Parson (COR) es de 0.5077587 (50%). \n\n+ Por tanto, se trata de una correlación negativa; es decir, la relación es inversa: a medida de que el IDH aumenta, hay menor porcentaje de voto a Castillo.  \n+ Además, se trata de una correlación que es grande En efecto, según el criterio de Cohen, la correlación se encuentra en el rango entre 0.5 y 1.0. \n\n*Acá reflexionar respecto a las afirmaciones*:\n\n - POR EJEMPLO: LAS PERSONAS QUE TENGAN LOS SERIVICOS BÁSICOS CUBIERTOS (BUEN IDH), REGISTRARON MENOR POSIBLIDAD QUE VOTEN POR UN CANDIDATO OUTSIDER Y CON UNA AGENDA RADICAL. REPRESENTANTES NUEVOS. VOTO ANTISISTEMA, NO EN LA NORMA.\n \n PROFUNDIZAR QUÉ PASA EN ESAS REGIONES QUE VOTARON ASÍ.\n\n## VER MÁS ALLÁ DE LO EVIDENTE\nSTORY TELLING --> IMPORTANTE EN CÓMO COMUNICO LA EVIDENCIA ESTADISTICA. MANEJAR UNA ARGUMETNACIÓN DE INTERPRETACIÓN DE LOS DATOS\nINICIAR UNA DISCUSIÓN. CONTRUBUIR A LA ACADEMIA\n\n  - AHORA CON DE SOTO:\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(data$IDH, data$VotosV_De_Soto, method = c(\"spearman\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  data$IDH and data$VotosV_De_Soto\nS = 296, p-value = 1.539e-06\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.8988034 \n```\n:::\n:::\n\n#INTERPRETACIÓN: \n\n+ Al revisar el P-value (1.539e-06), el cual es menor a 0.05, rechazamos la H0 y, por tanto, aceptamos la H1. A un 95% del nivel de confianza, sí parece existir una relación entre las variables IDH Y el porcentaje de voto a De Soto.\n\n+ El Coeficiente de Spearman (RHO es de 0.8988034 (89%). \n\n+ Por tanto, se trata de una correlación positiva; es decir, la relación es directa: a medida de que el IDH aumenta, hay mayor porcentaje de voto a Castillo. \n+ Además, se trata de una correlación que es grande. En efecto, según el criterio de Cohen, la correlación se encuentra en el rango entre 0.5 y 1.0. \n\n\n## Gráfico de dispersión\n\n### A través del gráfico de dispersión puedo percibir el sentido de la relación\nusualmente eje X: variables que suceden primero (VARIABLES INDEPENDIENTES)\n\n  - IDH - Castillo\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(data$IDH, data$VotosV_Castillo) #gráfico básico de R\n\n#OTRA FORMA DE CREAR EL GRÁFICO, PERO MÁS BELLO:\nlibrary(ggplot2)\n```\n\n::: {.cell-output-display}\n![](s10-ejercicio-semana10_files/figure-html/unnamed-chunk-6-1.png){width=100%}\n:::\n\n```{.r .cell-code}\nggplot(data, aes(x = IDH, y = VotosV_Castillo)) + geom_point(colour = \"red\")\n```\n\n::: {.cell-output-display}\n![](s10-ejercicio-semana10_files/figure-html/unnamed-chunk-6-2.png){width=100%}\n:::\n:::\n\nRELACIÓN QUE PARECIERA SER INVERSA (MENOS IDH, MAYOR VOTO POR CASTILLO)\n\n  - IDH - De Soto\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(data, aes(x = IDH, y = VotosV_De_Soto)) + geom_point(colour = \"blue\")\n```\n\n::: {.cell-output-display}\n![](s10-ejercicio-semana10_files/figure-html/unnamed-chunk-7-1.png){width=100%}\n:::\n:::\n\nEN DE SOTO SE DA UNA RELACION FUERTE Y DIRECTA (+IDH, +REGIONES VOTAN)\nSENTIDO: POSITIVO\n\n\n--------------------------------------------------------------------------------\n\n## OTRO TEMA:\n\nRECORDAR DOS FORMAS PARA RECODIFICAR:\nUSANDO LA MISMA BASE, POR EJEMPLO:\n\n1) FORMA: UNO POR UNO\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(data$Distrito.electoral)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n chr [1:26] \"Amazonas\" \"Ancash\" \"Apurimac\" \"Arequipa\" \"Ayacucho\" ...\n```\n:::\n:::\n\nOJO, ESTA VARIABLE ESTÁ EN chr (CONVERTIR A NUMERICA)\n\nCosta = 1\nSierra = 2\nSelva = 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# AQUÍ TAMBIÉN PODEMOS COLOCAR 1 en LUGAR DE SELVA:\ndata$region[data$Distrito.electoral == 'Amazonas'] = 'Selva' \ndata$region[data$Distrito.electoral == 'Ancash'] = 'Sierra'\ndata$region[data$Distrito.electoral == 'Apurimac'] = 'Sierra'\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data$region)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Selva Sierra \n     1      2 \n```\n:::\n:::\n\n\n2) forma: USANDO RECODE\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\ndata$region2 = recode(data$Distrito.electoral,\n                      \"'Amazonas' = 'Selva'; 'Ancash' = 'Sierra'\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data$region2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n       Apurimac        Arequipa        Ayacucho       Cajamarca          Callao \n              1               1               1               1               1 \n          Cusco    Huancavelica         Huanuco             Ica           Junin \n              1               1               1               1               1 \n    La_Libertad      Lambayeque      Lima_metro Lima_provincias          Loreto \n              1               1               1               1               1 \n  Madre_de_Dios        Moquegua           Pasco           Piura            Puno \n              1               1               1               1               1 \n     San_Martin           Selva          Sierra           Tacna          Tumbes \n              1               1               1               1               1 \n        Ucayali \n              1 \n```\n:::\n:::\n\nAQUÍ, FALTA DEFINIR (SE HACE UN POR UNO)\n\n",
    "supporting": [
      "s10-ejercicio-semana10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}