{
  "hash": "d7291d53438c99d37140a855143b61dd",
  "result": {
    "markdown": "---\naliases:\n  - ejercicio-semana15.html\n---\n\n\n\n\n\n# REPASO FINAL I\n\n\nDescargue la base de datos LAPOPPERU2019.dta que corresponde a las respuestas de peruanos y residentes al cuestionario de LAPOP 2019. Descargue el cuestionario. \n\nConsideraciones:\nEl archivo esta en formato stata. (.dta)\nVerifique las hipótesis formuladas usando las pruebas estadísticas correspondientes. Tenga en cuenta el tipo de variables para utilizar cada prueba. Interprete.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#getwd() \n#setwd(\"\")\n\nlibrary(rio)\ndataBARO = import(\"./data/s15/Peru-LAPOP-2019.dta\")\n```\n:::\n\n\nUn investigador desea analizar la satisfacción con el presidente y la confianza al presidente en Perú antes de la crisis por la pandemia del Covid-19.  Para ello, busca variables que estén relacionadas:\n\n\n    1•\tUna hipótesis es que la confianza al presidente (B21A) está vinculada a la edad. Corroboré esta hipótesis.  \n\n    2•\tEl investigador formula un primer modelo de regresión para verificar qué variables están relacionadas con la confianza al presidente (B21A).  El investigador utiliza las variables sociodemográficas como: Rural o Urbano (UR), Tamaño de la ciudad (ESTRATOSEC), Género (Hombre y Mujer) y Edad.   El investigador considera que estas variables sociodemográficas tienen un efecto sobre la confianza al presidente. \n\n    3•\tUn segundo modelo que se plantea es el efecto que tiene el apoyo a la democracia (ING4) en la confianza al presidente (B21A). \n\n    4•\tElabore un tercer modelo que explique la confianza al presidente (B12A). \n    \n    \n Consideraciones:\nEl archivo esta en formato stata. (.dta)\nVerifique las hipótesis formuladas usando las pruebas estadísticas correspondientes. Tenga en cuenta el tipo de variables para utilizar cada prueba. Interprete.\n   \n    \n    \n    \n    \n    \n    \n\n::: {.cell}\n\n```{.r .cell-code}\n#names(dataBARO)\n#str(dataPAVI)\n```\n:::\n\n\n\n# 1•\tUna hipótesis es que la confianza al presidente (B21A) está vinculada a la edad (q2). Corroboré esta hipótesis. \n\nVD -> confianza al presidente (B21A) - Y\nVI -> la edad (q2) - X\n\n    H0: No existe correlacion entrer la variables confianza al presidente (B21A) y la edad (q2).\n    H1:\n\n#Como la base de datos es grande, no es necesario aplicar la prueba de normalidad. TLC -> más de 121 de casos.\nPor tanto, por defecto con Pearson.\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(dataBARO$b21a, dataBARO$q2) #Pearson\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  dataBARO$b21a and dataBARO$q2\nt = 3.5927, df = 1510, p-value = 0.0003378\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.04184437 0.14181627\nsample estimates:\n       cor \n0.09206231 \n```\n:::\n\n```{.r .cell-code}\n#cor.test(data$b21a, data$q2, method = \"spearman\")\n```\n:::\n\nDebido a que el p-value (0.0003378) es menor a 0.05, rechazamos la H0 y, por tanto, aceptamos la H1 de que \"sí existe correlación entre confianza al presidente (B21A) y la edad (q2)\".\n\nEl Coeficiente de Pearson (RHO) es de 0.09 (9%) quiere decir:\n- Se trata de una \"correlación positiva\"; es decir, relación directa (a medida de que la edad aumenta, la confianza al presidente aumenta). No obstante el nivel de fuerza de la relación es muy débil. \n- Se trata de una \"correlación no es relevante\". En efecto, según el criterio de Cohen, la correlación se encuentra en el rango entre 0.0 y 0.1.\n\n\nGraficamos:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(dataBARO$b21a,dataBARO$q2, xlab=\"b21a\", ylab=\"q2\")\n```\n\n::: {.cell-output-display}\n![](s15-ejercicio-final-semana15_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\nINTERPRETACIÓN:\n\n+ No se aprecia la dirección. no nos da un diagonal perfecta.\n\n\n    - AHORA REGRESIÓN LINEAL SIMPLE DE ESTAS VARIABLES:\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo1 <- lm(b21a ~ q2, data = dataBARO) \nsummary(modelo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = b21a ~ q2, data = dataBARO)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.0590 -1.4746  0.2936  1.3541  3.6060 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 3.212687   0.117258  27.398  < 2e-16 ***\nq2          0.010075   0.002804   3.593 0.000338 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.693 on 1510 degrees of freedom\n  (9 observations deleted due to missingness)\nMultiple R-squared:  0.008475,\tAdjusted R-squared:  0.007819 \nF-statistic: 12.91 on 1 and 1510 DF,  p-value: 0.0003378\n```\n:::\n:::\n\n*Nos fijamos en el Multiple R-squared: 0.008475 (ya que solo tenemos una variable independiente)*\n\n 2. Al revisar el p-value (0.0003378), el cual es menor a 0.05), se determina que el modelo1 es válido para predecir la variable dependiente (confianza al presidente) a partir de la variable (edad). Es decir, la edad sí influye en la confianza al presidente.\n \n3. El modelo ayuda a predecir el 0.08% de la variabilidad de la variable independiente confianza al presidente.\n\n4 y 5. Coeficientes: Y = a + bx\nEl salario actual de un trabajador va a ser igual a 3.212687 + 0.010075*(educ). En ese sentido, por cada año adicional de edad, la confianza al presidente se incrementa en 3.212687 puntos.\n\n \n    2•\tEl investigador formula un primer modelo de regresión para verificar qué variables están relacionadas con la confianza al presidente (B21A).  El investigador utiliza las variables sociodemográficas como: Rural o Urbano (UR), Tamaño de la ciudad (ESTRATOSEC), Género (Hombre y Mujer) y Edad.   El investigador considera que estas variables sociodemográficas tienen un efecto sobre la confianza al presidente.\n\n#Formateando\n    - Rural o Urbano (UR)\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    str(dataBARO$ur)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n     num [1:1521] 1 1 1 1 1 1 1 1 1 1 ...\n     - attr(*, \"label\")= chr \"Urbano/Rural\"\n     - attr(*, \"format.stata\")= chr \"%36.0g\"\n     - attr(*, \"labels\")= Named num [1:2] 1 2\n      ..- attr(*, \"names\")= chr [1:2] \"Urbano\" \"Rural\"\n    ```\n    :::\n    :::\n\n::: {.cell}\n\n```{.r .cell-code}\ndataBARO$ur <- as.factor(dataBARO$ur)\ndataBARO$ur <- factor(dataBARO$ur, levels = levels(dataBARO$ur), labels = c(\"Urbano\", \"Rural\"))\nstr(dataBARO$ur)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Factor w/ 2 levels \"Urbano\",\"Rural\": 1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n\n```{.r .cell-code}\ntable(dataBARO$ur)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nUrbano  Rural \n  1165    356 \n```\n:::\n:::\n\n\n    - Tamaño de la ciudad (estratosec)\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dataBARO$estratosec)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 1 1 1 1 1 1 1 1 1 1 ...\n - attr(*, \"label\")= chr \"Estrato Secundario\"\n - attr(*, \"format.stata\")= chr \"%36.0g\"\n - attr(*, \"labels\")= Named num [1:3] 1 2 3\n  ..- attr(*, \"names\")= chr [1:3] \"Grande (más de 100,000)\" \"Mediana (entre 25,000 y 100,000)\" \"Pequeña (menos de 25,000)\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndataBARO$estratosec <- as.factor(dataBARO$estratosec)\ndataBARO$estratosec <- factor(dataBARO$estratosec, levels = levels(dataBARO$estratosec), labels = c(\"Grande\", \"Mediana\", \"Pequeña\"), ordered=T)\n\nstr(dataBARO$estratosec)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Ord.factor w/ 3 levels \"Grande\"<\"Mediana\"<..: 1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n\n```{.r .cell-code}\ntable(dataBARO$estratosec)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Grande Mediana Pequeña \n    845     223     453 \n```\n:::\n:::\n\n\n    - Sexo (q1)\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dataBARO$q1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 2 1 1 1 2 2 2 1 2 1 ...\n - attr(*, \"label\")= chr \"Sexo\"\n - attr(*, \"format.stata\")= chr \"%36.0g\"\n - attr(*, \"labels\")= Named num [1:2] 1 2\n  ..- attr(*, \"names\")= chr [1:2] \"Hombre\" \"Mujer\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndataBARO$q1 <- as.factor(dataBARO$q1)\ndataBARO$q1 <- factor(dataBARO$q1, levels = levels(dataBARO$q1), labels = c(\"Hombre\", \"Mujer\"))\n\nstr(dataBARO$q1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Factor w/ 2 levels \"Hombre\",\"Mujer\": 2 1 1 1 2 2 2 1 2 1 ...\n```\n:::\n\n```{.r .cell-code}\ntable(dataBARO$q1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nHombre  Mujer \n   758    762 \n```\n:::\n:::\n\n\n    - AHORA PROCEDEMOS CON EL MODELO DE REGRESIÓN LINEAL (MODELO SIN HACER FASTDUMMIES)\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo2 <- lm(b21a~ ur + estratosec + q1 + q2, data = dataBARO)\nsummary(modelo2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = b21a ~ ur + estratosec + q1 + q2, data = dataBARO)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2370 -1.4453  0.2649  1.3704  3.6947 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.199374   0.134676  23.756  < 2e-16 ***\nurRural       0.204014   0.139327   1.464 0.143327    \nestratosec.L -0.044191   0.094435  -0.468 0.639890    \nestratosec.Q  0.096863   0.101656   0.953 0.340818    \nq1Mujer      -0.109753   0.087109  -1.260 0.207883    \nq2            0.009825   0.002807   3.501 0.000477 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.693 on 1506 degrees of freedom\n  (9 observations deleted due to missingness)\nMultiple R-squared:  0.01182,\tAdjusted R-squared:  0.00854 \nF-statistic: 3.603 on 5 and 1506 DF,  p-value: 0.00304\n```\n:::\n:::\n\nUsaremos este modelo pero...\n    - Dicotomizando las variables independientes: \n    *NOTA: DICOTOMIZAR SIRVE PARA CREAR LA VARIABLE DE REFERENCIA/CONTROL, TAMBIEN PARA REEMPLAZAR EN LA ECUICACION DE ACUERDO A (SÍ: 1 ; NO: 0). ADEMÁS, PARA AGRUPAR Y TRATAR MEJOR A LAS VARIABLES*\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./data/s15/DICO.PNG){fig-align='center' width=60%}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fastDummies)\ndataBARO = dummy_cols(dataBARO, select_columns = c(\"estratosec\", \"ur\", \"q1\"))\n```\n:::\n\n\n    VERIFICANDO LAS NUEVAS VARIABLES CREADAS:\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(dataBARO)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] \"idnum\"                  \"uniq_id\"                \"cluster\"               \n  [4] \"upm\"                    \"wt\"                     \"wave\"                  \n  [7] \"pais\"                   \"nationality\"            \"estratopri\"            \n [10] \"prov\"                   \"municipio\"              \"estratosec\"            \n [13] \"tamano\"                 \"ur\"                     \"fecha\"                 \n [16] \"q1\"                     \"q2\"                     \"a4\"                    \n [19] \"soct2\"                  \"idio2\"                  \"np1\"                   \n [22] \"sgl1\"                   \"cp6\"                    \"cp7\"                   \n [25] \"cp8\"                    \"cp13\"                   \"it1\"                   \n [28] \"l1\"                     \"prot3\"                  \"jc10\"                  \n [31] \"jc13\"                   \"jc15a\"                  \"jc16a\"                 \n [34] \"vic1ext\"                \"vicbar7\"                \"arm2\"                  \n [37] \"vic73\"                  \"vic41\"                  \"vicbar4a\"              \n [40] \"percap1\"                \"percap2\"                \"percap3\"               \n [43] \"percap4\"                \"aoj11\"                  \"aoj12\"                 \n [46] \"aoj22\"                  \"b0\"                     \"b1\"                    \n [49] \"b2\"                     \"b3\"                     \"b4\"                    \n [52] \"b6\"                     \"b10a\"                   \"b12\"                   \n [55] \"b13\"                    \"b18\"                    \"b21\"                   \n [58] \"b21a\"                   \"b31\"                    \"b32\"                   \n [61] \"b37\"                    \"b47a\"                   \"m1\"                    \n [64] \"sd2new2\"                \"sd3new2\"                \"sd6new2\"               \n [67] \"infrax\"                 \"ros4\"                   \"redist1\"               \n [70] \"redist2a\"               \"redist3\"                \"redist_questions_order\"\n [73] \"ing4\"                   \"eff1\"                   \"eff2\"                  \n [76] \"eff10\"                  \"eff11\"                  \"dst1b\"                 \n [79] \"drk1\"                   \"env1\"                   \"env1calt\"              \n [82] \"env2b\"                  \"envp3l\"                 \"envp3n\"                \n [85] \"envp41\"                 \"envp42\"                 \"pn4\"                   \n [88] \"dem30\"                  \"e5\"                     \"d1\"                    \n [91] \"d2\"                     \"d3\"                     \"d4\"                    \n [94] \"d5\"                     \"d6\"                     \"lib1\"                  \n [97] \"lib2c\"                  \"exc2\"                   \"exc6\"                  \n[100] \"exc11\"                  \"exc13\"                  \"exc14\"                 \n[103] \"exc15\"                  \"exc16\"                  \"exc18\"                 \n[106] \"exc7\"                   \"exc7new\"                \"immig1xa\"              \n[109] \"immig1xb\"               \"immig1xc\"               \"comcon3xa\"             \n[112] \"comcon3xb\"              \"comcon3xc\"              \"perven1\"               \n[115] \"perven2\"                \"perven3\"                \"perven4\"               \n[118] \"perven5\"                \"vb2\"                    \"vb3n\"                  \n[121] \"vb10\"                   \"vb11\"                   \"pol1\"                  \n[124] \"vb20\"                   \"clien4a\"                \"clien1n\"               \n[127] \"clien1na\"               \"clien4b\"                \"vb50\"                  \n[130] \"vb51\"                   \"vb52\"                   \"vb58\"                  \n[133] \"w14a\"                   \"mil10a\"                 \"mil10e\"                \n[136] \"ie1n\"                   \"ie2\"                    \"wf1\"                   \n[139] \"cct1b\"                  \"ed\"                     \"q3cn\"                  \n[142] \"q5a\"                    \"q5b\"                    \"ocup4a\"                \n[145] \"ocupoit\"                \"ocup1a\"                 \"formal\"                \n[148] \"q10new\"                 \"q14\"                    \"q10e\"                  \n[151] \"q11n\"                   \"q12c\"                   \"q12bn\"                 \n[154] \"etid\"                   \"gi0n\"                   \"gi1\"                   \n[157] \"gi4\"                    \"gi7\"                    \"smedia1\"               \n[160] \"smedia2\"                \"smedia3\"                \"smedia4\"               \n[163] \"smedia5\"                \"smedia6\"                \"smedia7\"               \n[166] \"smedia8\"                \"smedia9\"                \"r3\"                    \n[169] \"r4\"                     \"r4a\"                    \"r5\"                    \n[172] \"r6\"                     \"r7\"                     \"r8\"                    \n[175] \"r12\"                    \"r14\"                    \"r15\"                   \n[178] \"r18\"                    \"r1\"                     \"r16\"                   \n[181] \"psc1\"                   \"psc2\"                   \"psc7\"                  \n[184] \"psc8\"                   \"psc9\"                   \"psc10\"                 \n[187] \"psc11\"                  \"psc11a\"                 \"psc12\"                 \n[190] \"psc13_1\"                \"psc13_2\"                \"psc13_3\"               \n[193] \"psc13_4\"                \"psc13_5\"                \"psc13_6\"               \n[196] \"psc13_7\"                \"psc13_8\"                \"psc13_9\"               \n[199] \"psc13_10\"               \"psc13_11\"               \"psc13_12\"              \n[202] \"psc13_13\"               \"psc3_0\"                 \"psc3_1\"                \n[205] \"psc3_2\"                 \"psc3_3\"                 \"psc4\"                  \n[208] \"psc5\"                   \"psc6\"                   \"inteval\"               \n[211] \"noise1\"                 \"noise2_1\"               \"noise2_2\"              \n[214] \"noise2_3\"               \"noise2_4\"               \"noise2_5\"              \n[217] \"noise2_6\"               \"noise2_7\"               \"noise2_8\"              \n[220] \"noise2_9\"               \"noise2_10\"              \"conocim\"               \n[223] \"sex\"                    \"formatq\"                \"colorr\"                \n[226] \"sexi\"                   \"colori\"                 \"intid\"                 \n[229] \"idiomaq\"                \"estratosec_Grande\"      \"estratosec_Mediana\"    \n[232] \"estratosec_Pequeña\"     \"ur_Urbano\"              \"ur_Rural\"              \n[235] \"q1_Hombre\"              \"q1_Mujer\"               \"q1_NA\"                 \n```\n:::\n:::\n\n\n  - utilizaremos las variables de interes\n  A LA VARIABLE DE REFERENCIA NO SE COLOCA EN EL CODIGO.\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo3 <- lm(b21a ~ ur_Urbano + estratosec_Grande + estratosec_Mediana + q1_Mujer + q2, data = dataBARO)\nsummary(modelo3) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = b21a ~ ur_Urbano + estratosec_Grande + estratosec_Mediana + \n    q1_Mujer + q2, data = dataBARO)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2370 -1.4453  0.2649  1.3704  3.6947 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         3.411685   0.151963  22.451  < 2e-16 ***\nur_Urbano          -0.204014   0.139327  -1.464 0.143327    \nestratosec_Grande   0.062495   0.133551   0.468 0.639890    \nestratosec_Mediana -0.087385   0.148119  -0.590 0.555301    \nq1_Mujer           -0.109753   0.087109  -1.260 0.207883    \nq2                  0.009825   0.002807   3.501 0.000477 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.693 on 1506 degrees of freedom\n  (9 observations deleted due to missingness)\nMultiple R-squared:  0.01182,\tAdjusted R-squared:  0.00854 \nF-statistic: 3.603 on 5 and 1506 DF,  p-value: 0.00304\n```\n:::\n:::\n\n*EDAD no es variable de control o referencia -> porque es numérica , solo se asume que aumenta en una unidad. las demás variables son de control.*\n\nINTERPRETACIÓN:\n\nH0: NO ES VALIDO\nH1:\n\nRechazamos la H0, alguna de estas variables independientes puede determinar la variable dependiente.\n\n2. Al revisar el p-value (0.00304), el cual es menor a 0.05), se determina que el modelo3 es válido para predecir la variable dependiente la confianza al presidente (b21a) solo a partir de la variable edad(q2).  \n\n3. El modelo ayuda a predecir el 0.85% de la variabilidad de la variable salario actual.\n\n3. La única variable que influye es EDAD (las otras no) de acuerdo con el p-value (0.000477)\n\n4 y 5. Coeficientes: Y = a + bx + b2x2 ...\n\nLa confianza al presidente va a ser igual a 3.411685 + (-0.204014*ur_urbano) + 0.062495*(estratosec_Grande) + (-0.087385*estratosec_Mediana) +  (-0.109753*q1_Mujer)+ 0.009825*(q2)\n\npor ejemplo:\n\nuna persona que vive en un sitio urbano, en una ciudad grande, es mujer y tiene 20 años dedad\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY = 3.411685 + (-0.204014*1) + 0.062495*1 +  (-0.109753*1) + 0.009825*(20)\nY\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.356913\n```\n:::\n:::\n\n\nLa confianza al presidente por parte de una mujer que vive en un sitio urbano, en una ciudad grande y tiene 20 años de edad va a ser igual a 3.356913 puntos. \n\n\nOTOR EJEMPLO\n\nSi es hombre (en este modelo es el modelo de referencia, por ello, reemplazamos con cero)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY2 = 3.411685 + (-0.204014*1) + 0.062495*1 +  (-0.109753*0) + 0.009825*(20)\nY2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.466666\n```\n:::\n:::\n\n\nLa confianza al presidente por parte de un hombre que vive en un sitio urbano, en una ciudad grande y tiene 20 años de edad va a ser igual a 3.466666 puntos. \n\n\nOTOR EJEMPLO:\n\nTomemos en cuenta (SER 1 EN LUGAR DE SER 0, DISMINUYE/AUMENTA LA CONFIANZA)\nreferencia -> rural: 0\n              urbano: 1\n\n+ SI UNA PERSONA PASA DE URBANO A RURAL, SU CONFIANZA DISMINUYE EN 0.204014. \n\nENTONCES...\n\n+ SI UNA PERSONA PASA DE ESTRATO GRANDE A PEQUEÑO, SU CONFIANZA AUMENTA  EN 0.062495. \n\n+ SI UNA PERSONA PASA DE ESTRATO MEDIANO A PEQUEÑO, SU CONFIANZA DISMINUYE EN 0.087385. \n\n+ SI UNA PERSONA ES MUJER EN LUGAR DE SER HOMBRE, SU CONFIANZA DISMINUYE EN 0.109753. \n\n+ RESPECTO A EDAD -> COMO ES NUMÉRICA, ASUMIMOS QUE AUMENTA EN UNA UNIDAD. ENTONCES, NO HAY CON QUIEN COMPARARLO.\n\n\nGráfica\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(jtools)\nplot_summs(modelo3, scale=TRUE)\n```\n\n::: {.cell-output-display}\n![](s15-ejercicio-final-semana15_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\nINTERPRETACIÓN:\npor los intervalos de confianza nos damos cuenta que solo EDAD influye en la varaible dependiente.\n\nLos intervalos de confianza de los coefricientes de las otras variables está tomando el valor cero.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#lm.beta(modelo3) #para ver el coeficiente estandarizado (NOS INDICA QUÉ VARIABLE IMPACTA MÁS EN LA VARIABLE)\n```\n:::\n\n*verlo en valor absoluto*\n\nEL MAYOR ES ES EDAD\n\n\n\n    3•\tUn segundo modelo que se plantea es el *efecto* que tiene el apoyo a la democracia (ING4) en la confianza al presidente (B21A). (Regresión lineal simple)\n\nVD: CONFIANZA AL PRESIDENTE\nVI: APOYO A LA DEMOCRACIA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dataBARO$ing4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 5 5 4 3 5 4 3 4 5 4 ...\n - attr(*, \"label\")= chr \"La democracia es mejor que cualquier otra forma de gobierno\"\n - attr(*, \"format.stata\")= chr \"%36.0f\"\n - attr(*, \"labels\")= Named num [1:5] 1 7 NA NA NA\n  ..- attr(*, \"names\")= chr [1:5] \"Muy en desacuerdo\" \"Muy de acuerdo\" \"No sabe\" \"No responde\" ...\n```\n:::\n:::\n\nConvertimos en numerica:\n#que salga numerica en R no signfica que sea definida así. R solamente está leyendo numeros.\n\n::: {.cell}\n\n```{.r .cell-code}\ndataBARO$ing4 <- as.numeric(dataBARO$ing4)\nstr(dataBARO$ing4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 5 5 4 3 5 4 3 4 5 4 ...\n```\n:::\n:::\n\n#que salga numerica en R no signfica que sea así.\n\ndefinimos como numerica tambien b21a\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dataBARO$b21a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 3 6 4 5 5 4 3 5 6 5 ...\n - attr(*, \"label\")= chr \"Confianza en el presidente\"\n - attr(*, \"format.stata\")= chr \"%36.0f\"\n - attr(*, \"labels\")= Named num [1:5] 1 7 NA NA NA\n  ..- attr(*, \"names\")= chr [1:5] \"Nada\" \"Mucho\" \"No sabe\" \"No responde\" ...\n```\n:::\n\n```{.r .cell-code}\ndataBARO$b21a <- as.numeric(dataBARO$b21a)\nstr(dataBARO$b21a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 3 6 4 5 5 4 3 5 6 5 ...\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo4 <- lm(b21a ~ ing4, data = dataBARO)\nsummary(modelo4) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = b21a ~ ing4, data = dataBARO)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1197 -1.2928  0.0871  1.2938  4.1207 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.67255    0.13627   19.61  < 2e-16 ***\ning4         0.20673    0.02908    7.11 1.79e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.668 on 1489 degrees of freedom\n  (30 observations deleted due to missingness)\nMultiple R-squared:  0.03284,\tAdjusted R-squared:  0.03219 \nF-statistic: 50.56 on 1 and 1489 DF,  p-value: 1.791e-12\n```\n:::\n:::\n\nINTERPRETACIÓN:\n\n2. Al revisar el p-value (1.791e-12), el cual es menor a 0.05, se determina que el modelo4 es válido para predecir la variable dependiente la confianza al presidente (b21a) a partir de la variable (ing4)  apoyo a la democracia.\n\n3. El modelo ayuda a predecir/explicar el 3.2% de la variabilidad de la variable (dependiente) confianza al presidente.\n\nEs una relacion positiva directa. por lo que a mayor apoyo a la demcoracua, habrá mayor confianza en el presidente.\n\n4 y 5. Coeficientes: Y = a + bx + b2x2 ...\n\nLa confianza al presidente va a ser igual a 2.67255 + 0.20673*(ing4) \n\npor ejemplo:\n\n+ Cuánto tendra una persona confianza al presidente que tienen 2 apoyo a la democraqcia\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY4 = 2.67255 + 0.20673*(2) \nY4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.08601\n```\n:::\n:::\n\nLa confianza al presidente por una persona que apoya a la democracia en 2 puntos, sería de 3.08601 puntos.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(dataBARO$b21a,dataBARO$ing4)  \nabline(modelo4)\n```\n\n::: {.cell-output-display}\n![](s15-ejercicio-final-semana15_files/figure-html/unnamed-chunk-26-1.png){width=100%}\n:::\n:::\n\nINTERPRETACIÓN:\n\n\n\n\n\n\n\n\n# PARTE 2\n\n- Co-author: Luis Valverde\n\nEl objetivo de esta sesión es conocer los comandos básicos de para la regresión lineal Múltiple. Para este ejercicio utilizaremos para reaplicar la base de datos de LAPOP.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rmdformats)\n#setwd(\"~/Documentos/12 PUCP-Docencia/4. Estadística 1 Ciencia Politica\")\n```\n:::\n\n\n# Formato de base de datos\n\n#### Importa la base de datos a R. Recuerda que si termina en .dta proviene de stata, si termina con .xslx proviene de excel\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n•\tUna hipótesis es que la confianza al presidente (B21A) está vinculada a la edad. Corroboré esta hipótesis. \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 3 6 4 5 5 4 3 5 6 5 ...\n - attr(*, \"label\")= chr \"Confianza en el presidente\"\n - attr(*, \"format.stata\")= chr \"%36.0f\"\n - attr(*, \"labels\")= Named num [1:5] 1 7 NA NA NA\n  ..- attr(*, \"names\")= chr [1:5] \"Nada\" \"Mucho\" \"No sabe\" \"No responde\" ...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 21 60 23 36 30 78 54 20 40 68 ...\n - attr(*, \"label\")= chr \"Edad\"\n - attr(*, \"format.stata\")= chr \"%36.0g\"\n - attr(*, \"labels\")= Named num NA\n  ..- attr(*, \"names\")= chr \"No sabe\"\n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n# Confianza al Presidente\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  1.000   2.000   4.000   3.605   5.000   7.000       8 \n```\n:::\n\n::: {.cell-output-display}\n![](s15-ejercicio-final-semana15_files/figure-html/unnamed-chunk-32-1.png){width=100%}\n:::\n:::\n\n\n# Confianza al Presidente y edad\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  data$ConfPresidente and data$Edad\nt = 3.5927, df = 1510, p-value = 0.0003378\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.04184437 0.14181627\nsample estimates:\n       cor \n0.09206231 \n```\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](s15-ejercicio-final-semana15_files/figure-html/unnamed-chunk-34-1.png){width=100%}\n:::\n:::\n\n\n# Hipótesis del investigador \n\n•\tEl investigador formula un primer modelo de regresión para verificar qué variables están relacionadas con la confianza al presidente (B21A).  El investigador utiliza las variables sociodemográficas como: Rural o Urbano (UR), Tamaño de la ciudad (ESTRATOSEC), Género (Hombre y Mujer) y Edad.   El investigador considera que estas variables sociodemográficas tienen un efecto sobre la confianza al presidente.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 1 1 1 1 1 1 1 1 1 1 ...\n - attr(*, \"label\")= chr \"Urbano/Rural\"\n - attr(*, \"format.stata\")= chr \"%36.0g\"\n - attr(*, \"labels\")= Named num [1:2] 1 2\n  ..- attr(*, \"names\")= chr [1:2] \"Urbano\" \"Rural\"\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n Factor w/ 2 levels \"Urbano\",\"Rural\": 1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 1 1 1 1 1 1 1 1 1 1 ...\n - attr(*, \"label\")= chr \"Estrato Secundario\"\n - attr(*, \"format.stata\")= chr \"%36.0g\"\n - attr(*, \"labels\")= Named num [1:3] 1 2 3\n  ..- attr(*, \"names\")= chr [1:3] \"Grande (más de 100,000)\" \"Mediana (entre 25,000 y 100,000)\" \"Pequeña (menos de 25,000)\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data$estratosec)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Grande Mediana Pequeña \n    845     223     453 \n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\nkable(table(data$estratosec_Grande))\n```\n\n::: {.cell-output-display}\n|Var1 | Freq|\n|:----|----:|\n|0    |  676|\n|1    |  845|\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data$estratosec_Mediana)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 \n1298  223 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data$estratosec_Pequeña)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 \n1068  453 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(data$q1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:1521] 2 1 1 1 2 2 2 1 2 1 ...\n - attr(*, \"label\")= chr \"Sexo\"\n - attr(*, \"format.stata\")= chr \"%36.0g\"\n - attr(*, \"labels\")= Named num [1:2] 1 2\n  ..- attr(*, \"names\")= chr [1:2] \"Hombre\" \"Mujer\"\n```\n:::\n\n```{.r .cell-code}\ndata$sexo=as.factor(data$q1)\nlevels(data$sexo) = c(\"Hombre\",\"Mujer\")\nstr(data$sexo)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Factor w/ 2 levels \"Hombre\",\"Mujer\": 2 1 1 1 2 2 2 1 2 1 ...\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo1=lm(ConfPresidente~ur+Edad+sexo+estratosec_Pequeña,data = data)\nsummary(modelo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ConfPresidente ~ ur + Edad + sexo + estratosec_Pequeña, \n    data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2252 -1.4457  0.2615  1.3620  3.6634 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         3.238179   0.129860  24.936  < 2e-16 ***\nurRural             0.158333   0.133210   1.189 0.234783    \nEdad                0.009920   0.002806   3.536 0.000419 ***\nsexoMujer          -0.109924   0.087116  -1.262 0.207210    \nestratosec_Pequeña -0.004657   0.123129  -0.038 0.969835    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.693 on 1507 degrees of freedom\n  (9 observations deleted due to missingness)\nMultiple R-squared:  0.011,\tAdjusted R-squared:  0.008376 \nF-statistic: 4.191 on 4 and 1507 DF,  p-value: 0.002228\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo2=lm(ConfPresidente~ur+Edad+sexo+estratosec,data = data)\nsummary(modelo2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ConfPresidente ~ ur + Edad + sexo + estratosec, \n    data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2370 -1.4453  0.2649  1.3704  3.6947 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        3.270166   0.132965  24.594  < 2e-16 ***\nurRural            0.204014   0.139327   1.464 0.143327    \nEdad               0.009825   0.002807   3.501 0.000477 ***\nsexoMujer         -0.109753   0.087109  -1.260 0.207883    \nestratosecMediana -0.149880   0.134092  -1.118 0.263855    \nestratosecPequeña -0.062495   0.133551  -0.468 0.639890    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.693 on 1506 degrees of freedom\n  (9 observations deleted due to missingness)\nMultiple R-squared:  0.01182,\tAdjusted R-squared:  0.00854 \nF-statistic: 3.603 on 5 and 1506 DF,  p-value: 0.00304\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stargazer) \nstargazer(modelo1,modelo2, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n===================================================================\n                                  Dependent variable:              \n                    -----------------------------------------------\n                                    ConfPresidente                 \n                              (1)                     (2)          \n-------------------------------------------------------------------\nurRural                      0.158                   0.204         \n                            (0.133)                 (0.139)        \n                                                                   \nEdad                       0.010***                0.010***        \n                            (0.003)                 (0.003)        \n                                                                   \nsexoMujer                   -0.110                  -0.110         \n                            (0.087)                 (0.087)        \n                                                                   \nestratosec_Pequeña          -0.005                                 \n                            (0.123)                                \n                                                                   \nestratosecMediana                                   -0.150         \n                                                    (0.134)        \n                                                                   \nestratosecPequeña                                   -0.062         \n                                                    (0.134)        \n                                                                   \nConstant                   3.238***                3.270***        \n                            (0.130)                 (0.133)        \n                                                                   \n-------------------------------------------------------------------\nObservations                 1,512                   1,512         \nR2                           0.011                   0.012         \nAdjusted R2                  0.008                   0.009         \nResidual Std. Error    1.693 (df = 1507)       1.693 (df = 1506)   \nF Statistic         4.191*** (df = 4; 1507) 3.603*** (df = 5; 1506)\n===================================================================\nNote:                                   *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"jtools\")\nlibrary(jtools)\n#install.packages(\"ggstance\")\nlibrary(ggstance)\n#install.packages(\"broom.mixed\")\nlibrary(broom.mixed)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(jtools)\nlibrary(sandwich)\ntestplot1 <- plot_summs(modelo1,modelo2,legend.title=\"Determinantes de la Confianza al Presidente\",scale = TRUE, robust = TRUE)\ntestplot1\n```\n\n::: {.cell-output-display}\n![](s15-ejercicio-final-semana15_files/figure-html/unnamed-chunk-47-1.png){width=100%}\n:::\n:::\n\n•\tUn segundo modelo que se plantea es el efecto que tiene el apoyo a la democracia (ING4) en la confianza al presidente (B21A).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$ing4=as.numeric(data$ing4)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo3=lm(ConfPresidente~+ing4,data = data)\nsummary(modelo3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ConfPresidente ~ +ing4, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1197 -1.2928  0.0871  1.2938  4.1207 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.67255    0.13627   19.61  < 2e-16 ***\ning4         0.20673    0.02908    7.11 1.79e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.668 on 1489 degrees of freedom\n  (30 observations deleted due to missingness)\nMultiple R-squared:  0.03284,\tAdjusted R-squared:  0.03219 \nF-statistic: 50.56 on 1 and 1489 DF,  p-value: 1.791e-12\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo4=lm(ConfPresidente~ur+Edad+sexo+estratosec_Grande+estratosec_Pequeña+ing4,data = data)\nsummary(modelo4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ConfPresidente ~ ur + Edad + sexo + estratosec_Grande + \n    estratosec_Pequeña + ing4, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.4029 -1.3070  0.1318  1.2692  4.3157 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         2.190092   0.211831  10.339  < 2e-16 ***\nurRural             0.224731   0.138142   1.627  0.10399    \nEdad                0.009604   0.002770   3.468  0.00054 ***\nsexoMujer          -0.097373   0.086195  -1.130  0.25879    \nestratosec_Grande   0.131755   0.131702   1.000  0.31728    \nestratosec_Pequeña  0.055013   0.146018   0.377  0.70641    \ning4                0.210139   0.029022   7.241 7.14e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.66 on 1483 degrees of freedom\n  (31 observations deleted due to missingness)\nMultiple R-squared:  0.04492,\tAdjusted R-squared:  0.04106 \nF-statistic: 11.62 on 6 and 1483 DF,  p-value: 9.342e-13\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo5=lm(ConfPresidente~Edad+ing4,data = data)\nsummary(modelo5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ConfPresidente ~ Edad + ing4, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.3768 -1.3100  0.1155  1.2615  4.2622 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2.270801   0.174456  13.016  < 2e-16 ***\nEdad        0.009857   0.002767   3.563 0.000378 ***\ning4        0.210742   0.028972   7.274 5.63e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.66 on 1487 degrees of freedom\n  (31 observations deleted due to missingness)\nMultiple R-squared:  0.0417,\tAdjusted R-squared:  0.04041 \nF-statistic: 32.35 on 2 and 1487 DF,  p-value: 1.768e-14\n```\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<table class=\"huxtable\" data-quarto-disable-processing=\"true\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \">\n<col><col><col><col><col><tr>\n<th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 1</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 2</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 3</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 4</th></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(Intercept)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">3.24 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">3.27 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">2.67 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">2.19 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.13)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.13)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.14)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.21)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">urRural</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.16&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.20&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.22&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.13)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.14)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.14)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Edad</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.01 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.01 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.01 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">sexoMujer</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.11&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.11&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.10&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.09)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.09)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.09)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">estratosec_Pequeña</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.00&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.06&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.12)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.15)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">estratosecMediana</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.15&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.13)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">estratosecPequeña</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.06&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.13)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">ing4</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.21 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.21 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.03)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.03)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">estratosec_Grande</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.13&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.13)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">N</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">1512&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">1512&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">1491&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">1490&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">R2</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.01&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.01&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.03&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.04&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th colspan=\"5\" style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>\n</table>\n\n```\n:::\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ConfPresidente ~ Edad + ing4, data = data)\n\nStandardized Coefficients::\n(Intercept)        Edad        ing4 \n         NA  0.09046121  0.18468520 \n```\n:::\n:::\n",
    "supporting": [
      "s15-ejercicio-final-semana15_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}