{
  "hash": "4ee522a1de8e0617e8d0b2c988ceb101",
  "result": {
    "markdown": "---\naliases:\n  - ejercicio-semana13.html\n---\n\n\n\n\n# Regresión lineal Múltiple\n\nEl objetivo de esta sesión es conocer los comandos básicos de para la regresión lineal Múltiple Para este ejercicio utilizaremos para reaplicar la base de datos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#getwd() \n#setwd(\"\")\nlibrary(rio)\ndataPAVI = import(\"./data/s12/b-pavimentando con votos.sav\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#names(dataPAVI)\n#str(dataPAVI)\n```\n:::\n\n\n## Formateo: DISTINGAMOS LAS VARIABLES NUMERICAS Y (NOMINALES) DICOTOMICAS\n\n::: {.cell}\n\n```{.r .cell-code}\n# forma corta\ndataPAVI[,c(1:2, 5, 7:8)] = lapply(dataPAVI[,c(1:2, 5, 7:8)],as.numeric)\ndataPAVI[,c(3:4, 6)] = lapply(dataPAVI[,c(3:4, 6)],as.factor)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# forma larga\n#dataPAVI$poblacioncienmil = as.numeric(dataPAVI$poblacioncienmil)\n#dataPAVI$nbi = as.numeric(dataPAVI$nbi)\n\n#dataPAVI$consejocomunal = as.factor(dataPAVI$consejocomunal)\n#dataPAVI$priorizado = as.factor(dataPAVI$priorizado)\n\n#dataPAVI$uribista = as.numeric(dataPAVI$uribista)\n\n#dataPAVI$ejecucion = as.factor(dataPAVI$ejecucion)\n\n#dataPAVI$apropiaciondolar = as.numeric(dataPAVI$apropiaciondolar)\n#dataPAVI$pctopo = as.numeric(dataPAVI$pctopo)\n```\n:::\n\n\n**HIPOTESIS 1:** \n============================================================\n  - Reﬁere a la asignación presupuestal en relación a los criterios TÉCNICOs determinados por documentos elaborados por el gobierno / La asignación presupuestal se debe a criterios técnicos\n\n\napropiaciondolar -> Variable dependiente\nPriorizado -> variable independiente - categorica dummy -> sí y no. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo1 = lm(apropiaciondolar ~ priorizado, data = dataPAVI) #(Y~X)\nsummary(modelo1) #modelo1 -> este es incompleto, mejor usar summary\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = apropiaciondolar ~ priorizado, data = dataPAVI)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n -8.277  -8.277  -8.272   1.108 124.371 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  8.277427   0.560554  14.766   <2e-16 ***\npriorizado1 -0.005434   1.117040  -0.005    0.996    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.05 on 1094 degrees of freedom\nMultiple R-squared:  2.163e-08,\tAdjusted R-squared:  -0.0009141 \nF-statistic: 2.367e-05 on 1 and 1094 DF,  p-value: 0.9961\n```\n:::\n:::\n\n\n  - Gráfico: SOLO LINEAL\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2) # para hacer gráficos facheros\nggplot(dataPAVI, aes(x = priorizado, y = apropiaciondolar)) +\n  geom_point(colour=\"red\") + \n  xlab(\"priorizado\") +  ylab(\"apropiaciondolar\") +\n  ggtitle(\"priorizado / apropiaciondolar\") +\n  theme_light() + geom_smooth(method=\"lm\", se = F)\n```\n\n::: {.cell-output-display}\n![](s13-ejercicio-semana13_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=100%}\n:::\n:::\n\n#No es regresión lineal múltiple, pues *Solo tenemos una variable independiente -> priorizado* \n\n#INTERPRETACIÓN:\n  + Al revisar el p-value (0.9961), el cual es mayor a 0.05, se determina que el modelo1 no es válido para predecir la variable dependiente (apropiaciondolar) a partir de la variable (priorizado). Parece que la H1 no funciona, es decir, no aporta ninguna explicación.\n\n\n\n**HIPOTESIS 2:** \n============================================================\n  - La asignación presupuestal en infraestructura vial en Colombia r esponde a negociaciones bilaterales entre el ejecutivo y el legislativo basadas en necesidades políticas y electorales de corto plazo // Reﬁere a la asignación presupuestal en relación a negociaciones basadas en necesidades políticas y electorales (mecanismo clientelista)\n\n\nvariables: \n      alcalde uribista o no uribista-categorica dicotomica\n      porcentaje de oposicion -numérica-, \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#str(dataPAVI$uribista)\n\n# Uribista tiene que estar como factor:\ndataPAVI$uribista <- as.factor(dataPAVI$uribista)\ntable(dataPAVI$uribista)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  0   1 \n332 560 \n```\n:::\n:::\n\n \n## Modelo 2\n\n::: {.cell}\n\n```{.r .cell-code}\n# aca se le añade otra variable con el signo: + \nmodelo2 = lm(apropiaciondolar ~ uribista + pctopo, data = dataPAVI) \n\nsummary(modelo2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = apropiaciondolar ~ uribista + pctopo, data = dataPAVI)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-11.939  -8.803  -7.585   2.127 122.158 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 11.93907    1.18455  10.079  < 2e-16 ***\nuribista1   -3.04661    1.17808  -2.586  0.00987 ** \npctopo      -0.04209    0.02282  -1.845  0.06539 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.74 on 885 degrees of freedom\n  (208 observations deleted due to missingness)\nMultiple R-squared:  0.009834,\tAdjusted R-squared:  0.007596 \nF-statistic: 4.395 on 2 and 885 DF,  p-value: 0.01261\n```\n:::\n:::\n\n\n  - Si una municipalidad tiene alcalde uribista, el presupuesto de infraestructura vial disminuye en 3.04661.\n\n  - Si una municipalidad incrementa su porcentaje oposición al uribismo en una unidad, el presupuesto de infraestructura vial disminuye en 0.04209.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(scatterplot3d)\n(a=scatterplot3d(dataPAVI[,c('uribista', 'pctopo', 'apropiaciondolar')]))\n```\n\n::: {.cell-output-display}\n![](s13-ejercicio-semana13_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n    H0: las variables independientes no influyen en la variable dependiente / (Los coeficientes de las variables independientes son iguales a cero)\n    H1: las variables independientes sí influyen en la variable dependiente\n    \n  + Al revisar el p-value (0.01261), el cual es menor a 0.05, se determina que el modelo2 es válido para predecir la variable dependiente (apropiaciondolar) a partir de las variables (uribista + pctopo). Por lo que podemos rechazar la hipotesos nula.\n  \n  + Al revisar el p-value (2.2e-16), el cual es menor a 0.05, rechazamos la H0. Por lo que a un 95% de confianza las variables independientes (educ) y (experiencia) tienen impacto significativo en la variable dependiente (salario_actual). \n  \n  Pero al revisar el p-value (0.1330) de la otra variable independiente (antiguedad), advertimos que es mayor a 0.05, a saber, no aporta significativamente al modelo5. Por tanto, se recomienda construir un modelo de regresión sin la variable (antiguedad). Pese a ello, para la interpretacón lo tomaremos en cuenta. Así se determina que el modelo5 solo es válido para predecir el salario actual de un trabjador a partir de su educación y experiencia. \n\n\n## Frente a uribista \n\n    H0: Si un municipio tenga o no tenga un alcalde uribista no influye en la variable independiente (la asignación presupuestal) \n    H1: Si un municipio tenga o no tenga un alcalde uribista sí influye en la variable independiente (la asignación presupuestal)\n\nEl p-value específico de esta variable es 0.00987, menor a 0.05, por lo que la variable uribista sí impacta en la asignacion presupuestal. Rechazamos la H0.\n\n#INTERPRETACIÓN:\n  - sentido: inverso -3.04661\n  - variable uribista: \n    - 0: no fue uribista el alcalde\n    - 1: sí fue uribista el alcalde\n\n  + CUANDO UN MUNICIPIO tiene un alcalde uribista, manteniendo consante el porcentaje de oposición, la asignación presupuestal vial disminuye en 3.04661 millones de dólares \n\n\n## Frente a pctopo (No es signifcativa)      \n\n  + El p-value especifico para la variable pctopo es 0.06539, mayor a 0.05,por lo que fracasamos al rechazar la H0.La variable no impacta significativamente en la (variable dependiente) asignacion presupuestal.\n\n  - Explicando su sentido: Inverso -0.04209\n\n  + Cuando un porcentaje de oposición incrementa en una unidad (1%) (o punto procentual mayor), mateniendo constante el ser una alcalde uribista, la asignación presupuestal vial disminuye en 0.04209 millones de dólares. \n\nCoeficientes:\n\nasignaciónvial = 11.93907 + (-3.04661*uribista1) + (-0.04209*pctopo)\n\nEJEMPLOS:\n #PERO ANTES: ¿CÓMO SABER EL PORCENTAJE DE OPOSICIÓN DE UNA MUNICIPALIDAD QUE ES URIBISTA? #EN este caso usaremos summary para conocer el min y el max\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dataPAVI$pctopo)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  0.000   5.922  20.308  27.874  45.711  99.419       7 \n```\n:::\n:::\n\nEntonces, ¿qué sucede con un municipio que tiene un alcalde uribista y que tiene 27.874 de porcentaje de oposición?\n\n::: {.cell}\n\n```{.r .cell-code}\nY1 <- 11.93907+(-3.04661*1)+(-0.04209*27.874)\nY1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.719243\n```\n:::\n:::\n\nUn municipio con esas características va a tener un presupuesto de 7.719243 millones\n\nAhora: ¿qué sucede con un municipio que no tiene un alcalde uribista y que tiene 27.874 de porcentaje de oposición?\n\n::: {.cell}\n\n```{.r .cell-code}\nY2 <- 11.93907+(-3.04661*0)+(-0.04209*27.874)\nY2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.76585\n```\n:::\n:::\n\nUn municipio con esas características va a tener un presupuesto de 10.76585 millones\n\n  - CONCLUSIÓN: \n   + El gobierno prefirió a los alcaldes no uribistas y también donde no tenían tanto porcentaje de oposición. \n\n\n\n3. El modelo ayuda a predecir el 0.7% de la variabilidad de la variable dependiente asignación presupuestal vial (apropiaciondolar).\n\n*de la variabilidad de la variable dependiente = del cambio sistemático de nuestra variable dependiente*\n\n\nEntonces,\nla variable que más impacta es \"Uribista\" --> PARA ESTAR MÁS SEGUROS, GUIARNOS POR LO COEFICIENTES ESTANDARIZADOS:\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"lm.beta\")\nlibrary(lm.beta)\nlm.beta(modelo2) #Nos otorga los coeficientes estandarizados para ver los efectos de las variables\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = apropiaciondolar ~ uribista + pctopo, data = dataPAVI)\n\nStandardized Coefficients::\n(Intercept)   uribista1      pctopo \n         NA -0.08763178 -0.06251466 \n```\n:::\n:::\n\n*NOTA: FIJARNOS EN EL VALOR ABSOLUTO, ES DECIR, SIN EL SIGNO*\n\nLa variable uribista1 (-0.08763178) impacta más en el modelo. o sea, tener o no alcalde Uribista impacta más en el modelo. \n\n ###PARA VISUALIZAR LOS DATOS\n#Pequeña tabla \n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"jtools\")\nlibrary(jtools)\nsumm(modelo2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMODEL INFO:\nObservations: 888 (208 missing obs. deleted)\nDependent Variable: apropiaciondolar\nType: OLS linear regression \n\nMODEL FIT:\nF(2,885) = 4.39, p = 0.01\nR² = 0.01\nAdj. R² = 0.01 \n\nStandard errors: OLS\n------------------------------------------------\n                     Est.   S.E.   t val.      p\n----------------- ------- ------ -------- ------\n(Intercept)         11.94   1.18    10.08   0.00\nuribista1           -3.05   1.18    -2.59   0.01\npctopo              -0.04   0.02    -1.84   0.07\n------------------------------------------------\n```\n:::\n:::\n\n*NOTA: \nEst. -> Estimate\nP. -> P-value\nS.E. -> ERROR ESTANDAR\nt val. -> LOS VALORES T -> t value (en summary)*\n\n\n###Grafico de los coeficientes\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#plot_coefs(modelo2)\nplot_coefs(modelo1, modelo2)\n```\n\n::: {.cell-output-display}\n![](s13-ejercicio-semana13_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=100%}\n:::\n:::\n\nINTERPRETACIÓN:\n\nSer uribista1 tiene un efecto más lejano de cero y el porcentaje de oposicion sale muy cercano a cero.\n\n*la linea es el intervalo de confianza del coeficiente, es decir, dicho coeficiente puede variar de acuerdo a la muestra que tengamos*   \n\n*El cuadradito es el promedio del coeficiente y la linea que le cruza es el intervalo de confianza.*\n\n\n#ahora con más variables... tabla resumen\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(huxtable) #install.packages(\"huxtable\")\n\nlibrary(officer) #install.packages(\"officer\")\nexport_summs(modelo1, modelo2, scale = TRUE,\n             error_format = \"[{conf.low}, {conf.high}]\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<table class=\"huxtable\" data-quarto-disable-processing=\"true\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \">\n<col><col><col><tr>\n<th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 1</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 2</th></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(Intercept)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">8.28 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">10.79 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">[7.18, 9.38]&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">[8.96, 12.61]&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">priorizado1</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.01&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">[-2.20, 2.19]&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">uribista1</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-3.05 **&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">[-5.36, -0.73]&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">pctopo</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-1.05&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">[-2.17, 0.07]&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">N</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">1096&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">888&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">R2</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.00&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.01&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th colspan=\"3\" style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">All continuous predictors are mean-centered and scaled by 1 standard deviation. The outcome variable is in its original units.  *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>\n</table>\n\n```\n:::\n:::\n\nINTERPRETACIÓN:\n\n\n\n\nHIPOTESIS 3 :la asignación presupuestal en infraestructura vial en Colombia responde al esfuerzo del gobierno por fortalecer su base social de apoyo local a través de los Consejos Comunales de Gobierno.\n\n# AHORA CON LAS VARIABLES INDEPENDIENTES: consejocomunal + ejecucion\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo3 = lm(apropiaciondolar ~ consejocomunal + ejecucion, data = dataPAVI) \nsummary(modelo3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = apropiaciondolar ~ consejocomunal + ejecucion, data = dataPAVI)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-23.924  -7.321  -7.321   0.773 125.321 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       7.3214     0.4928  14.855  < 2e-16 ***\nconsejocomunal1  16.6023     2.0734   8.007 2.98e-15 ***\nejecucion1        1.2232     2.4855   0.492    0.623    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.6 on 1093 degrees of freedom\nMultiple R-squared:  0.05592,\tAdjusted R-squared:  0.05419 \nF-statistic: 32.37 on 2 and 1093 DF,  p-value: 2.198e-14\n```\n:::\n:::\n\n  \n  - Si la municipalidad ha tenido la instalación del consejo comunal , el presupuesto de infraestructura vial incrementaría en 16.60 millones de dólares.\n\n\nrechazar la H0, p-value (2.198e-14) menor a 0.05, sí explica\n\nla variable consejocomunal que indica esfuerzops populista si \n\n\n#PARA VER LA UNIDAD\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dataPAVI$consejocomunal) #ES DICOTÓMICA \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n:::\n\n\nINTERPRETACIÓN:\n\nconsejocomunal  \nManteniendo fija la variable ejecución, si la alcaldía presenta consejo comunal el presupesto vial asiganado se incrementa en  16.6023 de dolares, en comparación de un consejo que no es comunal.\n\nejecucion        \n\n##Frente a ejecucion (No es signifcativa)      \n\nEl p-value especifico para la variable ejecucion es 0.623, mayor a 0.05, por lo que fracasamos al rechazar la H0. La variable no impacta significativamente en la (variable dependiente) asignación presupuestal.\n\nExplicando su sentido: directo 1.2232 \n\nCuando la ejecucion se incrementa en una unidad (1%) (o punto procentual mayor), mateniendo constante la varaible independiente consejocomunal, la asignación presupuestal vial aumenta en 1.2232 millones de dólares. \n\nCoeficientes:\n\nPresupuesto asignación vial = 7.3214 + (-3.04661*uribista1) + (-0.04209*pctopo)\n\nEJEMPLOS:\n\n\n\n\n\nHIPOTESIS GENERAL: La asignación presupuestal se debe a criterios técnicas, políticos y populistas.\n============================================================\n\n3 hipotesis + población en 100 mil y necesidades básicas insatisfechas\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo4 = lm(apropiaciondolar ~ priorizado + uribista + pctopo + consejocomunal + ejecucion + poblacioncienmil + nbi,data = dataPAVI) \nsummary(modelo4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = apropiaciondolar ~ priorizado + uribista + pctopo + \n    consejocomunal + ejecucion + poblacioncienmil + nbi, data = dataPAVI)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-60.201  -8.207  -5.875   2.505  92.488 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      14.13181    1.67651   8.429  < 2e-16 ***\npriorizado1      -2.21395    1.18715  -1.865  0.06253 .  \nuribista1        -2.57184    1.09188  -2.355  0.01872 *  \npctopo           -0.03096    0.02126  -1.456  0.14563    \nconsejocomunal1  14.05017    2.32452   6.044 2.23e-09 ***\nejecucion1        2.95688    2.80758   1.053  0.29255    \npoblacioncienmil  1.83866    0.20024   9.182  < 2e-16 ***\nnbi              -0.09292    0.02941  -3.160  0.00163 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.38 on 868 degrees of freedom\n  (220 observations deleted due to missingness)\nMultiple R-squared:  0.1751,\tAdjusted R-squared:  0.1684 \nF-statistic: 26.32 on 7 and 868 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stargazer) \nstargazer(modelo1,modelo2,modelo3,modelo4, type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=================================================================================================================\n                                                         Dependent variable:                                     \n                    ---------------------------------------------------------------------------------------------\n                                                          apropiaciondolar                                       \n                             (1)                    (2)                    (3)                      (4)          \n-----------------------------------------------------------------------------------------------------------------\npriorizado1                 -0.005                                                                -2.214*        \n                           (1.117)                                                                (1.187)        \n                                                                                                                 \nuribista1                                        -3.047***                                       -2.572**        \n                                                  (1.178)                                         (1.092)        \n                                                                                                                 \npctopo                                            -0.042*                                         -0.031         \n                                                  (0.023)                                         (0.021)        \n                                                                                                                 \nconsejocomunal1                                                         16.602***                14.050***       \n                                                                         (2.073)                  (2.325)        \n                                                                                                                 \nejecucion1                                                                1.223                    2.957         \n                                                                         (2.485)                  (2.808)        \n                                                                                                                 \npoblacioncienmil                                                                                 1.839***        \n                                                                                                  (0.200)        \n                                                                                                                 \nnbi                                                                                              -0.093***       \n                                                                                                  (0.029)        \n                                                                                                                 \nConstant                   8.277***              11.939***               7.321***                14.132***       \n                           (0.561)                (1.185)                (0.493)                  (1.677)        \n                                                                                                                 \n-----------------------------------------------------------------------------------------------------------------\nObservations                1,096                   888                   1,096                     876          \nR2                         0.00000                 0.010                  0.056                    0.175         \nAdjusted R2                 -0.001                 0.008                  0.054                    0.168         \nResidual Std. Error   16.052 (df = 1094)     16.735 (df = 885)      15.604 (df = 1093)       15.378 (df = 868)   \nF Statistic         0.00002 (df = 1; 1094) 4.395** (df = 2; 885) 32.371*** (df = 2; 1093) 26.316*** (df = 7; 868)\n=================================================================================================================\nNote:                                                                                 *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(jtools)\nplot_coefs(modelo1, modelo2, modelo3, modelo4)\n```\n\n::: {.cell-output-display}\n![](s13-ejercicio-semana13_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nModelo1 -> nos dice que no influye nada la priorización técnica\n\nel modelo 4 -> es distinto porque hemos añadiddo las variables de los modelos anteriroes a él, pero ademas las variables población en 100 mil y necesidades básicas insatisfechas.\n\nparece ser que si solamente tuvisiesempos que explicar la aporacion dolar, a traves de la priorizacion tecina, no logaramos explicarla.\n\nPero si le añadimos otras variables como sucede en el modelo4 CON LAS VARIABALES población en 100 mil y necesidades básicas insatisfechas, parece ser que el ser priroizado tiene un efecto inverso (negativo) en la aporpiacion dolar. es decir que los criterios tecnicos tiene un efecto inverso en la aporpaicon dolar. es decir, de no tener  ninguna relacion, ahora tiene algun impacto negativo. \nEn efecto, si observamos los intervalos de confianza de priorizado1 en el modelo 4, la linea (vigote) esta myr cerca de cero, no termina de impactar.  \n\n\nen los modelos 2 y 4 se mantiene sin ningun efecto en la asignacion presupuestal el porcfentaje de oposicion \n\n\n\nRespecto al modelo 4, nbi parece no impactar nada, en contraste con la POBLACION EN CIEN MIL \n\n\nRespecto a consejo comunal en el modelo 4 se hace más pequeño cuango agreagmos las otras dos variables, respecto al modelo 3. Los mismo podriamos señalar de la variable ejecución, pero sus respectivos inetrvalos tocan el cero, entonces, la variable ehecucion tampoco impacta en la apropicacion dolar (presupuesto.)\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"jtools\")\nlibrary(jtools)\n#install.packages(\"ggstance\")\nlibrary(ggstance)\n#install.packages(\"broom.mixed\")\nlibrary(broom.mixed)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo5=lm(apropiaciondolar ~ uribista + pctopo + consejocomunal + poblacioncienmil + nbi,data = dataPAVI)\nsummary(modelo5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = apropiaciondolar ~ uribista + pctopo + consejocomunal + \n    poblacioncienmil + nbi, data = dataPAVI)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-61.260  -8.165  -5.819   1.669  92.937 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      13.52620    1.64309   8.232 6.69e-16 ***\nuribista1        -2.53957    1.09309  -2.323  0.02039 *  \npctopo           -0.03082    0.02127  -1.449  0.14772    \nconsejocomunal1  13.94523    2.31933   6.013 2.68e-09 ***\npoblacioncienmil  1.81659    0.20014   9.077  < 2e-16 ***\nnbi              -0.09037    0.02939  -3.075  0.00217 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.4 on 870 degrees of freedom\n  (220 observations deleted due to missingness)\nMultiple R-squared:  0.1712,\tAdjusted R-squared:  0.1664 \nF-statistic: 35.93 on 5 and 870 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntestplot1 <- plot_summs(modelo4, modelo5, legend.title =\"Determinantes de la asignación presupuestal\", scale = TRUE, robust = TRUE)\ntestplot1\n```\n\n::: {.cell-output-display}\n![](s13-ejercicio-semana13_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nInterpretación:\n\n",
    "supporting": [
      "s13-ejercicio-semana13_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}