{
  "hash": "d904e42d971f08fe2ab18f0684275899",
  "result": {
    "markdown": "---\naliases:\n  - ejercicio-semana12.html\n---\n\n\n# Regresión Lineal\n\n\n\n\n\n## **PRIMERA BASE DE DATOS: ELECCIONES PERÚ (CASTILLO)**\n  \n  - IDH Y CASTILLO:\n\n::: {.cell}\n\n```{.r .cell-code}\n#getwd()\n#setwd(\"\")\n\nlibrary(rio)\ndataVOTO = import(\"./data/s12/PVotos_CirElectoral_idh.xlsx\")\n\n#names(dataVOTO)\n#str(dataVOTO)\n```\n:::\n\n\n**Modelo 1**\n============================================================\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo1 <- lm(VotosV_Castillo ~ IDH, data = dataVOTO)\nsummary(modelo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = VotosV_Castillo ~ IDH, data = dataVOTO)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.25650 -0.10446 -0.02506  0.13784  0.20256 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   0.7566     0.1715   4.413 0.000185 ***\nIDH          -0.9311     0.3225  -2.887 0.008096 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1391 on 24 degrees of freedom\nMultiple R-squared:  0.2578,\tAdjusted R-squared:  0.2269 \nF-statistic: 8.337 on 1 and 24 DF,  p-value: 0.008096\n```\n:::\n:::\n\n\nINTERPRETACION: \n\n## **1. ¿Existe una relación de depencia entre las variables? ¿Y depende de X1?**\n\n  - **H0: La variable independiente (`IDH`) no tiene efecto sobre la variable dependiente (`VotosV_Castillo`)**\n\n  + Al revisar el p-value (0.008096), el cual es menor a 0.05, rechazamos la H0. Por lo que a un 95% de confianza, el (`IDH`) tiene **impacto significativo** / **sí tiene un efecto** / **sí influye** en (`VotosV_Castillo`). Así se determina que el \"modelo1\" es válido para predecir el porcentaje de votos válidos a Castillo en los departamentos del país a partir del IDH; es decir, existe una relación lineal entre ambas variables.\n     \n## **2. ¿Cuánto explica el modelo?**\n\n  + La mejor recta graficada del \"modelo1\" de regresión lineal ayuda a predecir el 22% de la variabilidad total de la variable (`VotosV_Castillo`) explicada por la variable (`IDH`). Por lo que podemos concluir que es un modelo bajo.\n\n## **3. ¿Cómo Y depende de X 1?**\n\nCOEFICIENTE:\n\n  + El porcentaje de votos válidos de Castillo va a ser igual a 0.7566 + (-0.9311)*IDH. En ese sentido, cuando el (`IDH`) se incrementa en una unidad, el porcentaje de votos válidos de Castillo **disminuye** / **se reduce** en 0.9311 puntos porcentuales / 93%.\n\nINTERCEPTO:\n\n  + Cuando IDH toma el valor 0, el porcentaje de votos válidos para Castillo sería 0.7566.\n\n  + Y = 0.7566 +(-0.9311)*X\n\n  + Y = 0.7566 +(-0.9311)*IDH\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dataVOTO$IDH)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.3838  0.4688  0.5125  0.5249  0.5849  0.7255 \n```\n:::\n:::\n\n  + ¿Qué sucede con la región que tiene el min de IDH? remplazar 0.3838 en --> Y= 0.7566 + (-0.9311)*IDH\n\n::: {.cell}\n\n```{.r .cell-code}\nY1 = 0.7566 + (-0.9311)*0.3838\nY1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3992438\n```\n:::\n:::\n\n \n  + Porcentaje de voto a castillo al 40% \n\n## **Gráfica**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#plot(VotosV_Castillo ~ IDH, dataVOTO)\n#abline(modelo1, col = \"red\")\n\n# GRÁFICO FACHEREX:\nlibrary(ggplot2)\nlibrary(hrbrthemes)\nggplot(dataVOTO, aes(x = IDH, y = VotosV_Castillo, color = \"\")) +\n  geom_point(size = 6,\n                     alpha = 1/2) +  xlab(\"IDH\") +  ylab(\"Votos por Castillo\") +\n  ggtitle(\"IDH \\ Votos por Castillo\") +\n  theme_light() + geom_smooth(method=\"lm\", \n                             se = F) +  # Se eliminan las bandas de confianza (se = standard error) \n  theme_ipsum()\n```\n\n::: {.cell-output-display}\n![](s12-ejercicio-semana12_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nINTERPRETACIÓN:\n\n  + Las regiones con mayor IDH votaron menos por castillo.\n\n\n**SEGUNDA BASE DE DATOS: ELECCIONES COLOMBIA (PETRO)**\n============================================================\n  - IDH Y PETRO:\n\n::: {.cell}\n\n```{.r .cell-code}\n#getwd()\n#setwd(\"\")\n\nlibrary(rio)\ndataCOLOM = import(\"./data/s12/Colombia2022.xlsx\")\n\n#names(dataCOLOM)\n#str(dataCOLOM)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dataCOLOM$`Petro (%)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:33] 0.24 0.547 0.47 0.499 0.314 ...\n```\n:::\n\n```{.r .cell-code}\nstr(dataCOLOM$`IDH-2019`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:33] 0.772 0.786 0.813 0.756 0.76 0.778 0.717 0.719 0.729 0.716 ...\n```\n:::\n:::\n\n**Modelo 2**\n============================================================\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo2 <- lm(`Petro (%)` ~ `IDH-2019`, data = dataCOLOM)\nsummary(modelo2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = `Petro (%)` ~ `IDH-2019`, data = dataCOLOM)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.25500 -0.11035 -0.02323  0.09892  0.22906 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2.0028     0.4968   4.032 0.000334 ***\n`IDH-2019`   -2.1193     0.6670  -3.178 0.003354 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.141 on 31 degrees of freedom\nMultiple R-squared:  0.2457,\tAdjusted R-squared:  0.2214 \nF-statistic:  10.1 on 1 and 31 DF,  p-value: 0.003354\n```\n:::\n:::\n\n\n## INTERPRETACION:\n\n  - **H0: La variable independiente (`IDH-2019`) no tiene efecto sobre la variable dependiente (`Petro (%)`)**\n\n  + Al revisar el p-value (0.003354), el cual es menor a 0.05, rechazamos la H0. Por lo que a un 95% de confianza el (`IDH-2019`) tiene impacto significativo en (`Petro (%)`). Así se determina que el modelo2 es válido para predecir el porcentaje de votos válidos a Petro en las regiones del país colombiano a partir del IDH. Es decir, existe una relación lineal entre ambas variables.\n\n  + La mejor recta graficada del modelo2 de regresión lineal ayuda a predecir el 24% de la variabilidad total de la variable (`Petro (%)`) explicada por la variable (`IDH-2019`). Por lo que podemos concluir que es un modelo bajo.\n\nCOEFICIENTE:\n  \n  + El porcentaje de votos válidos de Petro va a ser igual a 2.0028 + (-2.1193)*`IDH-2019`. En ese sentido, cuando el `IDH-2019` se incrementa en una unidad, el porcentaje de votos válidos de Petro disminuye/se reduce en 2.1193 puntos porcentuales.\n\nINTERCEPTO:\n\n  + Cuando IDH toma el valor 0, el porcentaje de votos válidos para Petro sería 2.0028.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dataCOLOM$`IDH-2019`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.6390  0.7190  0.7500  0.7439  0.7740  0.8130 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nY2 = 2.0028 +(-0.9311*0)\nY2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.0028\n```\n:::\n:::\n\n\n## GRÁFICA\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#plot(`Petro (%)` ~ `IDH-2019`, dataCOLOM)\n#abline(modelo2, col = \"red\")\n\n# GRÁFICO FACHEREX:\nlibrary(ggplot2)\nggplot(dataCOLOM, aes(x=`IDH-2019`, y = `Petro (%)`)) +\n  geom_point(colour=\"red\", size = 3, alpha = 1/2) + \n  xlab(\"IDH 2019\") + \n  ylab(\"Votos por Petro\") +\n  ggtitle(\"IDH 2019 \\ Votos por Petro\") +\n  theme_light()+ geom_smooth(method=\"lm\", \n                             se = F) # Se eliminan las bandas de confianza (se = standard error)\n```\n\n::: {.cell-output-display}\n![](s12-ejercicio-semana12_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n:::\n\n  + Del mismo modo las regiones con mayor IDH votaron menos por Petro.\n\n\n\n\n",
    "supporting": [
      "s12-ejercicio-semana12_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}