{
  "hash": "687a5b01c19f3e94c30f7908375a743e",
  "result": {
    "markdown": "---\naliases:\n  - ejercicio-semana4.html\n---\n\n\n\n\n# Intervalo de Confianza\n\nDocente: Marylia Cruz\n\n1. Descargar las bases de datos \n2. Cambiar de directorio de trabajo \n3. Abrir la base de datos \n4. Comandos básicos \n5. Intervalo de confianza para una proporción \n6. Construcción de indicadores \n7. Intervalo de confianza para una media \n\n## DESARROLLO \n\nDescargar las bases de datos y los paquetes a utilizar\n\nCambiar de directorio de trabajo\n\nLa ruta de trabajo o directorio va a depender de cada computadora. Una opción fácil de\nsaberla es ir al menu - session-set working directory -choose directory\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#getwd() \n#setwd(\"\")\n```\n:::\n\n\nAbrir la base de datos\n\nImporta la base de datos a R. Recuerda que si termina en .dta proviene de stata, si termina\ncon .sav proviene de spss.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rio)\ndatalapop = import(\"./data/s2/LAPOP_PERU_2019.dta\")\n#names(datalapop) # solicitar los nombres de las variables\n#str(datalapop) # solicitar la estructura de las variables\n#class(datalapop) \n```\n:::\n\n\n  - Carga las siguiebtes Librerias\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rio) # abrir base de datos\nlibrary(psych)\nlibrary(ggplot2)# para el gráfico estático\nlibrary(gplots) # para solicitar las graficas de error\nlibrary(Rmisc)\n```\n:::\n\n\n\n# Intervalo de confianza para una proporción:\n\n\n<b style = 'color : #50D050;'>V. C. Nominal **jc15a** = Justificación del cierre del congreso</b>\n============================================================\n\n::: {.cell}\n\n```{.r .cell-code}\n#str(datalapop$jc15a)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndatalapop$jc15a = as.factor(datalapop$jc15a)\n\ndatalapop$jc15a = factor(datalapop$jc15a, \n                         levels = levels(datalapop$jc15a), \n                         labels = c(\"Si\",\"No\"), \n                         ordered = F)\n#str(datalapop$jc15a)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#tabla para variable nominal\ntable(datalapop$jc15a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Si  No \n449 313 \n```\n:::\n\n```{.r .cell-code}\nprop.table(table(datalapop$jc15a)) * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n      Si       No \n58.92388 41.07612 \n```\n:::\n:::\n\n\n## Intervalo de confianza para una proporción (en este caso los que sí están a favor del Sí)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Intervalo de proporciones de los que si justifican el cierre del congreso.\nn = 442+302 #El total de jc15a\nx = 442 #proporcion que me interesa, por ej., del SÍ\n\nprop.test(x, n, p = NULL, \n          alternative = c(\"two.sided\", \"less\", \"greater\"), \n          conf.level = 0.95, correct = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  x out of n, null probability 0.5\nX-squared = 25.969, df = 1, p-value = 3.469e-07\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5577263 0.6294607\nsample estimates:\n       p \n0.594086 \n```\n:::\n:::\n\n\nconfianza: nivel de credilidad de ese dato.\n\n  --> Fijarnos PARA LA INTERPRETACION:\n95 percent confidence interval:\n 0.5577263 0.6294607\n\n## **INTERPRETACION:**\n  H0: El nivel de la muestra no es igual al nivel de la proporcion\n  \n  - El intervalo de confianza de los que sí justifican el cierre del Congreso oscila entre 55% y 62% al 95% de nivel de confianza. \n\n  - (En cristiano este resultado señala que si se realiza otra encuesta en otro lado del perú, las personas responderán en favor de la cierre del congreso en ese intervalo de confianza en este caso.)\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ntabla1 = prop.table(table(datalapop$jc15a)) * 100\ntabla1r = as.data.frame(tabla1)\ntabla1r\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Var1     Freq\n1   Si 58.92388\n2   No 41.07612\n```\n:::\n:::\n\n\n\n## **GRAFICO DE BARRAS (BARPLOT)**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#grafico1 <- table(datalapop$jc15a) \n\n# También se puede crear una grafica en porcentaje:\ngrafico1 <- prop.table(table(datalapop$jc15a)) * 100 \n\ngrafico1 = as.data.frame(grafico1) \ncolnames(grafico1) = c(\"Reg\",\"Freq\")\n\nlibrary(ggplot2) \nbp = ggplot(grafico1, aes(x = reorder(Reg,Freq), y = Freq, fill = Reg)) +\n  geom_bar(stat = \"identity\") +\n  coord_flip() + \n  labs(title = \"Entrevistados según si justifica el cierre del congreso\", \n         y = \"% entrevistados\", x = \"Justifica el cierre al congreso\", \n         subtitle = \"\", caption = \"LAPOP, PERU 2019\") +\n  theme(plot.title = element_text(hjust = 1)) + \n  theme(panel.background = element_rect(fill = \"white\", colour = \"white\")) + \n  geom_text(aes(label = Freq), vjust = 0.5, color =\"Black\", size = 5)\nbp\n```\n\n::: {.cell-output-display}\n![Figure 1: Entrevistados según la justificación del cierre del congreso.](s4-ejercicio-semana4_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n**<b style = 'color : #50D050;'>Construcción de indicadores</b>**\n============================================================\n\n## Creación del indicador APOYO AL SISTEMA POLÍTICO:\n\n - Definir qué es un sistema politico. \n - qué signifca apoyo\n \n - Luego las personas que realizan las encuestas, a traves de una serie preguntas van a medir dicho concepto. cómo resumir dichas preguntas en un numero? - Indice aditivo: sumar las variables.\n\n - Definimos las variables que conforman el indicador. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Forma larga:\n# lapop$b1 = as.numeric(lapop$b1)\n# lapop$b2 = as.numeric(lapop$b2)\n# lapop$b3 = as.numeric(lapop$b3)\n# lapop$b4 = as.numeric(lapop$b4)\n# lapop$b6 = as.numeric(lapop$b6)\n```\n:::\n\n\n  - A númerica:\n\n::: {.cell}\n\n```{.r .cell-code}\n# forma corta de convertir varias variables:\ndatalapop[,c(48:52)] = lapply(datalapop[,c(48:52)],as.numeric) \n# del b1 al b6 # numero de la columnas 48 al 52\n```\n:::\n\n\n\n## Resumen de las variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(datalapop$b1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  1.000   2.000   3.000   2.927   4.000   7.000      11 \n```\n:::\n\n```{.r .cell-code}\nsummary(datalapop$b2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  1.000   2.000   4.000   3.824   5.000   7.000      18 \n```\n:::\n\n```{.r .cell-code}\nsummary(datalapop$b3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n   1.00    2.00    3.00    3.12    4.00    7.00      11 \n```\n:::\n\n```{.r .cell-code}\nsummary(datalapop$b4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  1.000   2.000   3.000   3.463   5.000   7.000      16 \n```\n:::\n\n```{.r .cell-code}\nsummary(datalapop$b6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  1.000   3.000   4.000   4.216   6.000   7.000      23 \n```\n:::\n:::\n\n\n  - Sumo las variables: #variable de escala Likert:\n  \n    - O sea, una persona puede puede como minimo 5 puntos y como maximo 35 puntos.\n    \n\n::: {.cell}\n\n```{.r .cell-code}\ndatalapop$SumaApoyoSistemaPolitico = datalapop$b1 + datalapop$b2 + datalapop$b3 + datalapop$b4 + datalapop$b6\n\n#datalapop$SumaApoyoSistemaPolitico\n\nsummary(datalapop$SumaApoyoSistemaPolitico)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n   5.00   13.00   18.00   17.56   22.00   35.00      45 \n```\n:::\n:::\n\n\nPero mejor lo convertimos a indice adecuado: \n\n  - Contrucción de índice de 0 a 100:\n\n::: {.cell}\n\n```{.r .cell-code}\ndatalapop$IndiceASP = ((datalapop$SumaApoyoSistemaPolitico - 5) / 30) * 100 \n#  Restamos el mínimo (5) y divimos entre el mázimo ya restado (30) \n# (sería 35, pero ya se restó 5) y finalmente se \n# multiplica * 100 (Indice aditivo de 0 a 100)\n\n#Resumen del indicador:\nsummary(datalapop$IndiceASP) # El comando brinda el resumen de la variable\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n   0.00   26.67   43.33   41.85   56.67  100.00      45 \n```\n:::\n\n```{.r .cell-code}\nhead(datalapop$IndiceASP)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 50.00000 50.00000 43.33333 46.66667 40.00000       NA\n```\n:::\n:::\n\n\nentonces, si se desea construir un indice de 0 a 100 solo sería * 10:\n\n::: {.cell}\n\n```{.r .cell-code}\ndatalapop$IndiceASP10 = ((datalapop$SumaApoyoSistemaPolitico - 5) / 30) * 10\nsummary(datalapop$IndiceASP10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  0.000   2.667   4.333   4.185   5.667  10.000      45 \n```\n:::\n\n```{.r .cell-code}\nhead(datalapop$IndiceASP10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.000000 5.000000 4.333333 4.666667 4.000000       NA\n```\n:::\n:::\n\n\n\n  - Estadísticos descriptivos del indicador de 0 a 100 (Ya se convirtió en una variable númerica). Entonces, solicitar los indicado para dicha variable:\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(datalapop$IndiceASP, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 41.85185\n```\n:::\n\n```{.r .cell-code}\nsd(datalapop$IndiceASP, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 20.62314\n```\n:::\n:::\n\n\n## **HISTOGRAMA (HIST)**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(datalapop, aes(x = IndiceASP, color = \"\")) + \n  geom_histogram(breaks = seq(105), fill = \"white\",alpha = 0.5, \n                 position = \"identity\") + \n  labs(title = \"Apoyo al sistema politico\", y = \"\", x = \"Index\", \n       subtitle = \"\", caption = \"ENDO 2020\") +\n  theme(plot.title = element_text(hjust = 0.5)) + \n  theme(panel.background = element_rect(fill = \"white\", colour = \"white\"))\n```\n\n::: {.cell-output-display}\n![Figure 2: Índice de apoyo al sistema politico.](s4-ejercicio-semana4_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n**<b style = 'color : #50D050;'>INTERVALO DE CONFIANZA PARA UNA MEDIA</b>**\n============================================================\n  - Recuerde que el intervalo de confianza se compone de un limite superior y uno inferior.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n###FORMA LARGA\nn <- length(datalapop$IndiceASP) # El tamaño válido de la muestra\nmedia <- mean(datalapop$IndiceASP,na.rm = T) # la media\ndesv <- sd(datalapop$IndiceASP, na.rm = T) # La desviacián estándar\nnivelconfianza = 0.95\n\nerror.est <- desv / sqrt(n) # Calculamos el error estándar\nmargen.error <- 1.96 * error.est # nivel de confianza de 90%\n\nlim.inf <- media - margen.error # Límite inferior del intervalo\nlim.inf # 39.839\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 40.81541\n```\n:::\n\n```{.r .cell-code}\nlim.sup <- media + margen.error # Límite superior del intervalo\nlim.sup # 42.80437\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.8883\n```\n:::\n:::\n\n  \n  - A un nivel de confianza del 95% el promedio del apoyo al sistema politico de los peruanos oscila entre 39.839 y 42.80437\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# FORMA CORTA:\nlibrary(Rmisc)\ndatalapop <- datalapop[!is.na(datalapop$IndiceASP), ] # eliminar valores perdidos\nci.indicador <- CI(datalapop$IndiceASP, ci = 0.95) # calcula el nivel de confianza\nci.indicador\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   upper     mean    lower \n42.90482 41.85185 40.79888 \n```\n:::\n:::\n\n\n*Varía la interpretacion pues se han eliminado los casos perdidos*:\n\n**INTERPRETACION**:\n\n  - A un nivel de confianza del 95% el promedio del apoyo al sistema politico de los peruanos oscila entre 40.79888 y 42.90\n\n\n## **BARRAS DE ERROR**:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplotmeans(datalapop$IndiceASP ~ datalapop$q1, \n          p = 0.95, \n          xlab = \"Sexo\", \n          ylab = \"Apoyo al sistema\", \n          main = \"Mean Plot \\n with 95% CI\")\n```\n\n::: {.cell-output-display}\n![Figure 1: Apoyo al sistema / Sexo.](s4-ejercicio-semana4_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=100%}\n:::\n:::\n\n  - parace que no hay mucha diferencia entre el sexo al apoyo del sistema pues el posible rango de valores de muejeres casi son los mismos que de hombres\n\n+   la bolita indica el promedio\n+   los bigotes indican los niveles de confianza de los promedios de cada grupo \n\n\n\n## **GRAFICO DE CAJAS (BOXPLOT)**\n\n::: {.cell}\n\n```{.r .cell-code}\ndatalapop <- datalapop[!is.na(datalapop$jc15a), ] # Eliminando casos perdidos\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(plotly)\np1 <- ggplot(datalapop, aes(x = jc15a, y = IndiceASP, color =jc15a)) + \n  geom_boxplot() + coord_flip() +\n  theme(legend.position = \"top\", axis.text.y = element_blank(), \n        panel.background=element_rect(fill = \"white\", colour = \"white\")) + \n  geom_jitter(shape = 16, position = position_jitter(0.2)) + \n  labs(title = \"El apoyo al sistema político según el sexo\", x = \"\", \n       y =\"Index\", subtitle = \"\", caption = \"ENDO 2020\") + \n  scale_y_continuous(breaks = (1:100))\nggplotly(p1)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-9cf56f5d3bf1592b817c\" style=\"width:100%;height:532.8px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-9cf56f5d3bf1592b817c\">{\"x\":{\"data\":[{\"x\":[50,43.333333333333336,46.666666666666664,83.333333333333343,73.333333333333329,10,33.333333333333329,63.333333333333329,50,50,26.666666666666668,50,23.333333333333332,53.333333333333336,30,40,43.333333333333336,36.666666666666664,0,20,73.333333333333329,56.666666666666664,56.666666666666664,23.333333333333332,30,33.333333333333329,63.333333333333329,56.666666666666664,16.666666666666664,0,36.666666666666664,63.333333333333329,60,53.333333333333336,53.333333333333336,30,30,40,40,6.666666666666667,36.666666666666664,30,63.333333333333329,33.333333333333329,53.333333333333336,13.333333333333334,0,23.333333333333332,26.666666666666668,6.666666666666667,26.666666666666668,40,63.333333333333329,53.333333333333336,50,6.666666666666667,23.333333333333332,40,53.333333333333336,0,36.666666666666664,20,36.666666666666664,0,53.333333333333336,63.333333333333329,10,40,0,33.333333333333329,16.666666666666664,46.666666666666664,43.333333333333336,50,3.3333333333333335,46.666666666666664,56.666666666666664,53.333333333333336,50,36.666666666666664,23.333333333333332,33.333333333333329,50,53.333333333333336,50,20,30,43.333333333333336,43.333333333333336,26.666666666666668,53.333333333333336,33.333333333333329,30,63.333333333333329,63.333333333333329,13.333333333333334,40,3.3333333333333335,53.333333333333336,10,40,36.666666666666664,50,16.666666666666664,80,40,53.333333333333336,6.666666666666667,40,56.666666666666664,76.666666666666671,33.333333333333329,13.333333333333334,50,26.666666666666668,46.666666666666664,46.666666666666664,16.666666666666664,56.666666666666664,43.333333333333336,30,0,40,70,40,40,23.333333333333332,40,46.666666666666664,83.333333333333343,93.333333333333329,3.3333333333333335,53.333333333333336,40,66.666666666666657,50,53.333333333333336,40,40,46.666666666666664,66.666666666666657,10,66.666666666666657,50,36.666666666666664,0,13.333333333333334,46.666666666666664,16.666666666666664,33.333333333333329,13.333333333333334,3.3333333333333335,36.666666666666664,60,50,43.333333333333336,40,36.666666666666664,63.333333333333329,23.333333333333332,13.333333333333334,10,36.666666666666664,33.333333333333329,23.333333333333332,23.333333333333332,60,46.666666666666664,56.666666666666664,46.666666666666664,50,30,33.333333333333329,40,83.333333333333343,26.666666666666668,90,26.666666666666668,73.333333333333329,26.666666666666668,63.333333333333329,40,33.333333333333329,0,13.333333333333334,70,43.333333333333336,63.333333333333329,86.666666666666671,56.666666666666664,60,30,36.666666666666664,46.666666666666664,73.333333333333329,46.666666666666664,3.3333333333333335,50,13.333333333333334,20,20,40,20,10,40,50,43.333333333333336,0,63.333333333333329,13.333333333333334,56.666666666666664,43.333333333333336,76.666666666666671,16.666666666666664,53.333333333333336,53.333333333333336,53.333333333333336,50,23.333333333333332,33.333333333333329,6.666666666666667,83.333333333333343,26.666666666666668,30,30,0,40,26.666666666666668,53.333333333333336,46.666666666666664,10,0,6.666666666666667,20,0,46.666666666666664,10,36.666666666666664,6.666666666666667,40,46.666666666666664,40,40,50,23.333333333333332,43.333333333333336,23.333333333333332,16.666666666666664,63.333333333333329,53.333333333333336,33.333333333333329,6.666666666666667,26.666666666666668,16.666666666666664,46.666666666666664,30,66.666666666666657,33.333333333333329,0,43.333333333333336,60,53.333333333333336,43.333333333333336,40,70,40,76.666666666666671,50,53.333333333333336,33.333333333333329,36.666666666666664,23.333333333333332,43.333333333333336,30,46.666666666666664,40,50,33.333333333333329,23.333333333333332,40,40,56.666666666666664,46.666666666666664,53.333333333333336,16.666666666666664,46.666666666666664,60,50,13.333333333333334,46.666666666666664,46.666666666666664,36.666666666666664,43.333333333333336,16.666666666666664,63.333333333333329,63.333333333333329,80,66.666666666666657,33.333333333333329,43.333333333333336,13.333333333333334,63.333333333333329,40,10,6.666666666666667,16.666666666666664,46.666666666666664,56.666666666666664,26.666666666666668,73.333333333333329,80,46.666666666666664,6.666666666666667,56.666666666666664,70,30,43.333333333333336,30,73.333333333333329,50,43.333333333333336,66.666666666666657,50,30,3.3333333333333335,30,23.333333333333332,0,33.333333333333329,33.333333333333329,36.666666666666664,20,60,10,50,33.333333333333329,50,100,30,50,73.333333333333329,60,56.666666666666664,36.666666666666664,50,46.666666666666664,40,36.666666666666664,63.333333333333329,63.333333333333329,46.666666666666664,36.666666666666664,50,30,36.666666666666664,43.333333333333336,6.666666666666667,6.666666666666667,10,33.333333333333329,30,16.666666666666664,10,6.666666666666667,90,43.333333333333336,16.666666666666664,40,60,30,20,50,66.666666666666657,3.3333333333333335,40,16.666666666666664,50,20,23.333333333333332,23.333333333333332,46.666666666666664,26.666666666666668,53.333333333333336,23.333333333333332,26.666666666666668,46.666666666666664,60,0,30,63.333333333333329,6.666666666666667,43.333333333333336,3.3333333333333335,3.3333333333333335,66.666666666666657,13.333333333333334,30,40,76.666666666666671,23.333333333333332,56.666666666666664,33.333333333333329,13.333333333333334,56.666666666666664,30,6.666666666666667,46.666666666666664,33.333333333333329,86.666666666666671,50,50,53.333333333333336,93.333333333333329,13.333333333333334,23.333333333333332,33.333333333333329,26.666666666666668,60,13.333333333333334,36.666666666666664,36.666666666666664,46.666666666666664,53.333333333333336,63.333333333333329,46.666666666666664,40,33.333333333333329,46.666666666666664,16.666666666666664,70,26.666666666666668,73.333333333333329,40,30,60,26.666666666666668,36.666666666666664,66.666666666666657,56.666666666666664,40,0,63.333333333333329],\"y\":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],\"hoverinfo\":\"x\",\"type\":\"box\",\"fillcolor\":\"rgba(255,255,255,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.6692913385826778},\"line\":{\"color\":\"rgba(248,118,109,1)\",\"width\":1.8897637795275593},\"name\":\"Si\",\"legendgroup\":\"Si\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"orientation\":\"h\",\"frame\":null},{\"x\":[56.666666666666664,66.666666666666657,60,36.666666666666664,63.333333333333329,63.333333333333329,83.333333333333343,56.666666666666664,73.333333333333329,33.333333333333329,36.666666666666664,40,20,30,50,26.666666666666668,13.333333333333334,36.666666666666664,50,26.666666666666668,20,30,50,56.666666666666664,73.333333333333329,53.333333333333336,86.666666666666671,40,40,90,46.666666666666664,46.666666666666664,70,53.333333333333336,36.666666666666664,50,56.666666666666664,63.333333333333329,80,40,50,10,36.666666666666664,26.666666666666668,26.666666666666668,46.666666666666664,33.333333333333329,20,33.333333333333329,20,10,36.666666666666664,20,10,60,43.333333333333336,50,20,76.666666666666671,46.666666666666664,26.666666666666668,20,46.666666666666664,73.333333333333329,46.666666666666664,73.333333333333329,76.666666666666671,70,60,46.666666666666664,50,43.333333333333336,13.333333333333334,36.666666666666664,80,56.666666666666664,56.666666666666664,23.333333333333332,86.666666666666671,46.666666666666664,76.666666666666671,40,40,23.333333333333332,50,26.666666666666668,56.666666666666664,26.666666666666668,76.666666666666671,10,50,46.666666666666664,56.666666666666664,43.333333333333336,36.666666666666664,20,23.333333333333332,66.666666666666657,66.666666666666657,70,73.333333333333329,46.666666666666664,26.666666666666668,53.333333333333336,60,40,80,66.666666666666657,70,0,63.333333333333329,63.333333333333329,23.333333333333332,50,43.333333333333336,16.666666666666664,46.666666666666664,53.333333333333336,20,20,70,40,53.333333333333336,43.333333333333336,60,20,66.666666666666657,43.333333333333336,73.333333333333329,40,43.333333333333336,53.333333333333336,83.333333333333343,70,60,53.333333333333336,53.333333333333336,26.666666666666668,60,16.666666666666664,43.333333333333336,40,33.333333333333329,80,46.666666666666664,43.333333333333336,10,36.666666666666664,33.333333333333329,36.666666666666664,50,56.666666666666664,20,36.666666666666664,50,46.666666666666664,26.666666666666668,36.666666666666664,13.333333333333334,16.666666666666664,46.666666666666664,13.333333333333334,33.333333333333329,76.666666666666671,66.666666666666657,13.333333333333334,56.666666666666664,56.666666666666664,40,23.333333333333332,26.666666666666668,16.666666666666664,30,60,63.333333333333329,23.333333333333332,63.333333333333329,0,36.666666666666664,33.333333333333329,63.333333333333329,43.333333333333336,46.666666666666664,3.3333333333333335,80,56.666666666666664,46.666666666666664,66.666666666666657,23.333333333333332,40,40,90,33.333333333333329,36.666666666666664,3.3333333333333335,60,73.333333333333329,60,40,60,56.666666666666664,33.333333333333329,50,46.666666666666664,3.3333333333333335,90,43.333333333333336,43.333333333333336,20,50,0,70,36.666666666666664,16.666666666666664,53.333333333333336,36.666666666666664,23.333333333333332,56.666666666666664,73.333333333333329,13.333333333333334,93.333333333333329,50,36.666666666666664,23.333333333333332,50,40,63.333333333333329,26.666666666666668,20,80,33.333333333333329,63.333333333333329,70,80,30,36.666666666666664,53.333333333333336,43.333333333333336,33.333333333333329,70,60,36.666666666666664,43.333333333333336,60,13.333333333333334,53.333333333333336,63.333333333333329,43.333333333333336,43.333333333333336,30,56.666666666666664,60,50,40,13.333333333333334,40,20,40,20,96.666666666666671,46.666666666666664,53.333333333333336,83.333333333333343,36.666666666666664,56.666666666666664,56.666666666666664,56.666666666666664,33.333333333333329,50,40,66.666666666666657,30,33.333333333333329,76.666666666666671,46.666666666666664,36.666666666666664,26.666666666666668,46.666666666666664,56.666666666666664,50,23.333333333333332,83.333333333333343,23.333333333333332,50,26.666666666666668,46.666666666666664,26.666666666666668,56.666666666666664,10,36.666666666666664,46.666666666666664,20,10,26.666666666666668,30,40,3.3333333333333335,43.333333333333336,43.333333333333336,46.666666666666664,53.333333333333336,53.333333333333336],\"y\":[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],\"hoverinfo\":\"x\",\"type\":\"box\",\"fillcolor\":\"rgba(255,255,255,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.6692913385826778},\"line\":{\"color\":\"rgba(0,191,196,1)\",\"width\":1.8897637795275593},\"name\":\"No\",\"legendgroup\":\"No\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"orientation\":\"h\",\"frame\":null},{\"x\":[50.703394681215286,44.396246880913772,46.99509953955809,72.934800372148544,10.005138009165725,33.637866809964173,63.896465395887688,50.226924765855074,49.950737308089934,23.031010121727981,53.910047256698213,29.031097024679184,35.759484504039087,19.297068004185956,57.080962661032871,57.474332946663097,23.666033795103431,29.702865135545533,63.214353668813899,16.580487561722595,1.0664806328713878,62.495783165718116,52.303609771654017,53.013879477356873,30.28227315035959,39.151623944441482,35.80415617053707,30.02159106048445,32.870533943176262,12.477469249938927,26.237496739253402,27.008766327674191,40.205351874853172,63.326121877878897,24.272555690258738,1.31215365976095,35.958453083410859,20.894137694810826,36.868091769516468,0.20913414160410526,52.661807466298342,62.006079503645495,40.861082823947072,32.138210838660598,16.010601062327623,42.33627948040764,3.9644326915343595,45.854590209821858,56.981629746034741,36.423080100988344,48.738795895129442,21.074336140727002,43.094181779772043,42.190053317074977,27.652977971360087,52.203618214776121,29.325183084234595,62.109136359766126,54.620679729928575,37.820476725076631,16.229574137056865,52.282971811170384,56.867395815129079,32.274790429199733,12.038439160212876,47.98737473599612,45.431051826725401,55.451586473733187,40.943950598438576,69.713693950325251,83.206801025817796,82.044101149464652,49.670868415385485,26.224632892136775,66.486621916294084,49.269792207827173,67.933925041928873,72.250433035194874,67.249619603777916,80.492091974864408,0.20173066233595183,32.868196688592427,57.183391086757183,12.168544972936315,37.348242814342179,61.149776812021926,43.490792306760952,39.587164727970958,30.970699230829872,24.424927728250619,7.2644142725815373,36.052268035088971,62.126711822425321,52.972126188377544,-0.57983091970284695,23.857367501904566,47.127414852380753,7.3725673841933403,41.192043260360755,53.601074115062758,40.643088890860476,52.201168686151512,64.447310351456196,41.138004625216126,33.996385434021548,0.2257699482142923,37.676880728453391,13.229887808362644,10.12003700559338,1.1718294130017346,30.458024402459461,46.347845850512385,45.42226192665597,49.882371804366507,46.113338318342961,49.910867295538388,54.511577532316245,49.491672751804195,22.204110784456134,52.072738346954189,44.640343697120748,64.496257352953151,12.118989863122506,57.420241743326187,42.405171589305006,32.202688547472157,15.739648399874566,52.784959828481078,62.172364592552185,12.368135746568443,10.588271814088026,26.004897369071845,51.107621212800339,40.619316574186087,77.744152031838894,19.56971899420023,11.171791097770132,36.013466897731021,0.20192254583040836,50.247525147472821,39.433597351734839,24.650892520323392,40.544973136857152,45.545436698943377,33.570944804077342,3.2694682472695908,53.213877019161984,53.302857670933008,40.79507547492782,40.2176367106537,1.0001317827651885,53.118236217647791,9.3196831618746128,39.108717477569982,0.0012734197080135345,39.506938808287181,47.332444231957197,16.703327571973201,34.385797126218669,24.566918985297281,2.2226822413504141,36.739430829261735,60.674062068263687,49.283831595753632,36.025263049950198,39.171740625053644,40.413026151557766,14.556224899366496,32.035711736107864,23.46417698264122,47.608590173845485,56.896536953747272,50.751356447115541,84.550279130538314,49.562525362397231,64.118735279267028,39.501615156730018,9.352355582639575,69.917417774597808,40.52787192414204,70.513408508772656,27.525093305235107,87.078991400077939,55.942213076477245,5.5565991854916037,36.700940140833453,70.905209245160222,72.425906322896481,12.12889764333765,33.417589725926511,48.904671008388206,41.196661082406834,23.574981646612287,51.160197225709751,28.775402961919706,36.585386165728167,20.754914119218785,48.802356384694576,89.794152894988656,40.688855851069093,38.869107839961849,36.011715776597455,29.085460558533669,38.720340995118022,11.087066923578579,-0.17592808666328574,49.252756699298821,10.554893990978599,17.02995247642199,39.427405711263418,42.086458242187902,29.015909305463236,48.840237241238356,40.749725776414074,52.516163131843015,48.701914263889194,93.431864501908422,27.491197903951008,40.863017603134111,28.988354864840709,54.384354876975216,44.406326439231634,34.62899108541508,42.548525271316372,49.706101511294641,46.982874782135085,50.618751860534154,52.514031028995916,33.248048386846975,35.512960036595665,16.332971309622128,29.705681790287297,47.308291548242167,50.170224819332361,33.918350727607802,62.859835904091589,56.142727536459759,8.9423878925542049,54.511523881306253,16.877803428719439,44.647966242705785,14.643235212191938,47.406846650565662,47.098981182401374,31.13230994219581,32.123480084041752,62.834335155785077,63.201678710058324,7.6420504425962754,76.416093832502767,72.105775995800883,80.762063253670931,60.088437828545771,47.030541333680347,30.212023907030623,44.058956760292254,72.822493830695748,49.428430023292698,20.15252185985446,39.124485637371741,45.78092556384702,32.517343237375215,33.054256080960229,52.510584454983473,59.661190613483392,39.839258193969727,48.833698093270264,5.4786990421513737,83.249877021337554,7.5285881838450823,42.794661774610482,7.4696544526765738,25.638259715711079,31.073843513925869,35.700379144400358,6.9755210243165493,29.728851798300941,41.164118394876517,38.720711698755622,4.3468990183124925,23.761450637752809,55.633953646446265,16.546485607201852,63.800026344135397,15.786152576406796,46.827125516409673,80.860291919981435,33.29207357081274,40.334307335317135,53.570213270684086,22.491544637208182,30.219882775098085,62.478079069405794,43.749028371026121,40.364800171926618,6.9265994150191545,23.844799470156428,40.247106928378344,67.422823209315524,63.540223001192011,46.831924818456173,89.479723589494824,5.9608229982356242,50.409737614293896,53.600812564293548,36.778803848971918,48.944536145155631,74.197519883513451,12.179779908309381,26.705591961120568,39.998653865108885,56.116296192010239,52.484008320296809,6.7409828342497349,42.752275343363486,45.365434372176729,60.053824428468943,14.377938942362864,12.382371693228684,3.80638151243329,48.802215624600649,24.630229061469432,42.819495933130383,50.722260761385165,20.055691728989284,3.6247835966447988,60.207721012334027,85.771064275254815,0.28405874843398693,68.828430938224002,38.691954697171852,63.520829906066254,56.821590717881918,77.814443831021592,27.163139721999567,33.210449944560722,52.243862623969719,67.947956807911382,32.034419051061072,3.9393067198495064,26.58393581956625,56.287526737277702,45.436348058904208,13.071343776459496,36.007657689973712,22.808957592894632,-0.50279945942262738,45.594362174471222,46.365807083124913,33.765571697925523,62.927214839806155,10.067477395758033,29.019378048057359,50.131526531651616,40.31206663697958,60.324957422291241,31.043289418021836,18.755759666984282,66.927659668649227,6.1850591016312446,2.1106642689555901,16.614367008830108,15.988681862130759,20.27559176646173,30.529258924846847,0.76320648938417324,58.785948836555086,27.060264398033421,51.080338377505541,47.575395531952374,36.954083545754351,45.806599524493016,43.126380970701575,6.9779920379320775,76.586085267985865,60.384423025573291,0.45001746527850561,4.2147871175159999,6.7504405037810411,30.221297456572454,30.991826366012294,58.677060741310321,62.287189273163676,57.566996879254773,60.156543091560401,22.978484001631536,44.155709324404597,16.332576135173436,14.295368903006116,26.095030973354977,27.785248912250001,44.026886339609824,45.808885663747787,36.684254334618643,93.880840511992574,39.809044683972992,27.594525345290702,36.321871834496655,45.543458585316934,27.123567455137771,30.464099476113915,40.491493893787265,30.071868400399882,18.794569133470457,55.466770722841225,9.7756944944461193,67.758310086404279,-0.41097587471206931,39.442961272473134,34.453196685761206,9.1929582785815018,44.193984931955733,50.192163384829961,65.479816595092402,50.842419576520719,42.355515530953809,22.087804601217311,72.700108527516321,46.124073263878621,17.141049301872648,63.233916384478405,6.8266646706809606,47.681436507652201,45.57495203179618,74.456480748951435,35.914274852101997,29.004247271145385,27.576131787771981,33.315530184035495,47.151598457247019,29.615334561715525,24.451085144033033,33.932098689799503,24.471260329708453,-0.10976797963182117,15.662821833044291,66.017857603728757,34.624372252573565,14.003005399679143,22.111395008862019,100.85501635198791,61.06037663357953],\"y\":[1.0773672863841057,0.84067668803036211,0.87464554440230136,0.81552520673722029,0.93800375191494823,1.0898744901642203,0.90751797938719392,1.1165701266378165,0.82885907692834737,1.1628972244448961,0.85867531718686219,1.0347869562916459,1.0113653413020074,1.1955640638247131,0.82723671728745107,0.92495905086398122,1.0280596289783717,0.94967468734830618,1.1690038769505917,1.1205384817905724,1.0797935268841683,1.1715471617877484,0.90711473384872077,1.0635323764756321,1.0947631992399693,1.1436422176659107,1.0319772949442267,1.0792642352171242,0.86459944518283005,1.0200142432004213,1.0971834870055317,0.84148699464276433,0.82260936927050354,0.97937760110944505,0.94452416012063622,0.86244539665058251,1.0218925951048732,1.0248107921332121,0.89087010081857443,0.84611035874113438,0.85343306008726361,0.9549346646293998,0.91686787065118547,0.98731175949797034,1.1364754986949266,1.1700022788718343,1.1903469915501774,1.1627254982478916,1.1636333412490785,1.1653378744609655,0.98078999938443301,1.0580811616033317,0.84959170492365954,1.186861870624125,0.97883665077388282,0.95502955811098222,1.0342578096315265,0.80205372218042614,1.19521897546947,0.8811958939768374,0.89800933301448826,1.1847254254855215,1.1709062597714364,0.80574726201593871,1.1646572140976788,1.1499030553735792,0.91564536141231656,1.0308962952345611,0.95762093905359502,0.85621673073619609,0.90096188206225636,1.1009087288752197,1.1778140847571195,1.0409264890477061,1.0767612076364457,1.1824672850780189,1.0732395140454174,1.15333329802379,0.9835008354857564,1.0810556961223483,1.1007859374396503,0.96027851058170199,0.82116977255791423,1.1657849976792931,0.99137629689648743,1.1734059144742788,1.0348800404928624,1.0087652628310024,1.0984697797335685,0.91538109295070169,1.1233358022756874,0.8974342355504632,1.1238011022098362,1.0649503707885741,0.9106423982419074,1.0086892820894717,1.0912627018988132,1.1861052865162491,1.1233721465803683,1.0855877550318838,0.88346853647381063,0.81460015168413524,1.100968662276864,0.82036895044147973,0.83959282292053106,0.80090300478041176,1.003311687335372,1.1751448520459236,1.1297210787422955,1.1690557953901588,0.949768153205514,0.97613696083426471,0.8601712057366967,0.91542057581245895,1.1661044387146831,0.82642611050978299,0.85073183989152312,0.92704697353765364,0.83768476201221342,0.87590053807944057,1.1717941525392235,0.9559456665068865,1.0657129239290952,1.0097791098058224,0.80244864961132412,1.1534981361590326,0.9824061075225472,0.84609462507069111,1.1712889002636075,0.87570097111165524,0.81327342102304101,0.96887647444382308,0.82547894399613142,1.0834080647677182,0.836180514190346,0.96538052791729567,1.1104757362045348,0.85429337937384842,1.0537763349711895,0.90132925603538749,0.85842796163633461,0.8613824986852705,1.1859891032800078,1.1387553547509015,1.0615575266070665,0.98962005842477085,1.1122713945806026,1.083437279239297,1.1649775330908596,1.032685836777091,0.91473816996440294,1.1757585193961859,0.84317416809499268,1.0331926188431679,0.966225643735379,1.0025915463455022,1.1331781878136098,1.1514002018608154,0.99118174007162452,0.93397460123524068,1.1783395055681467,0.90664042718708515,1.1482640945352613,1.0221708046272397,1.0173421417362989,0.92707849983125923,1.1372529424726963,0.94553428785875437,1.1081363593228162,0.98887922354042535,0.83186652129516003,1.112061005551368,1.1960246404632926,1.1072404218837619,0.89490551436319943,0.82868322059512134,0.92887761089950804,1.1913947644643486,1.1784353895112871,0.87291394844651227,1.1320895105600357,0.97081326618790631,1.1713976574130356,0.82182608423754577,1.0573350259102881,1.1473290420137345,0.95401498004794116,0.97067922130227091,1.0178092729300261,0.97927220053970809,1.1936903343535961,1.1703130645677446,1.0756743143312633,0.93289986019954085,0.91213301923125978,0.83864511018618937,0.85819160081446166,0.84467930998653173,1.1635556317865849,1.0856628796085714,0.83544925786554813,0.87878942815586925,1.0940134936012327,0.83035078682005403,1.0719122816808522,0.93682597512379284,0.95222184835001822,1.1673920557834208,1.1248080770485103,1.049319360870868,0.80751989148557191,1.1442256745882333,1.1289142157882452,0.87370817810297008,1.0837720701470972,0.90086306668817995,1.0703826235607266,0.91234163986518979,1.1673102288506925,1.1732529510743916,0.84154593134298916,0.96294090757146478,0.98224830655381079,1.1012405463494361,1.0394503358751535,0.94272542092949152,0.96947922948747878,1.0172471955418587,1.0796752965077758,1.0682876090519131,1.1555045936256647,1.0393929189071058,1.1619416447356343,1.0318731458857655,0.95255804359912877,1.0939258418045938,1.1935567491687835,1.1223365876823663,1.0406350545585155,1.1628247893415391,0.9869833223521709,0.84844732070341711,1.0456967275589704,0.87960525071248408,0.87915600724518295,1.1486513531766831,1.1507264280691742,1.0177278926596045,0.85294649181887505,1.04218956399709,1.1299135610461235,1.1587006651796401,0.9342489858157933,1.0033980161882936,1.1619980669580401,0.97605804083868863,1.0474914750084281,1.0850849329493939,0.89288540724664922,0.94100424731150267,1.0079080831259488,0.97833572104573252,1.0542972470633685,0.88405440887436271,1.1946622621268035,0.83168798824772239,1.1587050437927247,1.1817746166139842,1.1585768966004253,1.0555307358503341,1.1783712791278957,1.1804572185501456,0.90459220772609117,0.90989939030259848,0.92545787841081617,1.1099969049915672,1.0348316942341627,1.0543056243099271,0.813237685430795,1.1368582961149514,1.0112352057360112,0.90759802376851439,1.0609018109738826,0.90336781311780212,0.99802583931013944,0.82700092997401953,0.84240611605346205,1.0046988289803267,0.84107060423120861,1.1890000636689364,1.0524778661318124,0.83097003716975448,0.85826038829982276,1.1983411360532046,0.91509417947381733,1.0821148522198201,0.91753299003466959,0.99087237380445004,0.84015846280381079,1.0613359575159849,0.94545940188691024,0.99350376334041357,1.1470940954051911,1.0264039536938072,1.0112020805478097,1.0871458440087736,1.0868432627990843,1.1131698916666211,0.83085363069549201,1.0497706609778106,0.86536677265539763,0.93358004027977581,1.0529812895692885,1.0720080847851932,1.1056947682984173,1.1870280327275395,0.91845079995691781,1.032103489805013,0.94969841949641709,1.1744843089953065,0.89775279061868785,1.0537509538233281,1.17527744024992,1.0688604758121074,0.89939509071409707,0.90596583094447847,1.1658980472013354,0.89552756017073987,0.8758038473315537,0.93360082358121876,1.1789611220359801,1.1014357178471983,1.1573425294831394,0.98533637225627901,1.0163094136863946,0.96866014897823338,1.123557735234499,1.1640637278556825,0.91533695878461008,0.87902956623584028,0.98530280310660601,0.86862999014556408,1.0545455446466803,0.92296295342966916,1.0534920262172818,0.93981934105977416,1.139534924738109,1.0215315887704493,1.0353864126838743,0.99964424287900333,0.96505939001217489,1.0782165128737689,0.88898081192746758,1.1821366294287146,1.0757747460156679,0.8126011760905385,1.1118019298650323,1.0199908384121954,1.0164858541451394,1.0809399062767624,0.92640296723693605,1.0939387315884233,0.90182390930131073,1.1473445059731602,1.1565983708947898,1.1575702210888266,0.92241920894011853,0.8383009342476726,0.88244611257687211,0.85211227722465988,1.1008874339982868,1.1870905669406056,0.91447045011445882,1.0530637631192803,1.1152862637303769,0.90988436732441191,0.95855981335043905,1.1518788560293616,1.1154961313121021,1.0868333435617388,1.0274686818942427,1.0300076059065759,0.92739749876782296,0.95283495755866165,0.8492755807936192,1.1416666556149722,0.9013091564178467,1.0356903376989066,1.0467041221447289,0.95311065455898647,1.0402626835741102,0.89374162862077355,1.1038334880024194,0.85003806799650194,1.1295497678220272,0.92307520993053915,0.89999894481152298,1.1931517696008087,1.1118883928284049,0.93065046370029447,0.96238644104450943,0.87061429154127834,0.86508537847548728,0.96260941531509159,0.90311624249443412,1.1672261412255467,1.0574857515282929,1.0456968414597214,1.1158349806442858,0.86750450823456049,1.040594227425754,0.82537781307473779,0.91814602660015221,0.80965042281895871,0.97859973562881353,1.0428604772314429,1.0824493899010121,0.94295954462140796,1.0651218418031931,1.0727273536846043,0.90380878448486324,1.1837440988048911,1.120990864560008,0.90446040341630574,0.9188072594814003,0.81962175564840434,1.1251111971214414,0.95937904911115768,1.1991791727021337,0.93339388044551019,1.0249826179817318,1.0742423923686146,1.0501988492906094,1.0489859062246978,1.1147163558751345,0.87297524437308316,1.1267807328142225,1.142349427100271,0.99075513929128645,1.1207656030543149,1.0604338533245028,1.0080704640597105],\"text\":[\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  73.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   3.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  70.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  83.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  83.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  66.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  66.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  73.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  66.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  80.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  76.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   3.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   3.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  83.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  70.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  70.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  86.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  70.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  73.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  90.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  93.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  76.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  73.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  80.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  73.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  83.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   3.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  80.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  66.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  90.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  73.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   3.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   3.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  86.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  70.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  76.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  53.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  66.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   3.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  66.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   3.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  76.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   3.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  93.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  20.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  56.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  66.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  40.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  10.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  66.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  50.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  43.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  73.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  63.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   6.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  73.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  36.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  26.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  46.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  30.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:   0.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  16.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  66.666667<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  33.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  13.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  23.333333<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP: 100.000000<br />jc15a: Si\",\"jc15a: Si<br />IndiceASP:  60.000000<br />jc15a: Si\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"opacity\":1,\"size\":5.6692913385826778,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"Si\",\"legendgroup\":\"Si\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[57.075738992542028,53.013227668901287,60.238785336414971,20.019398465131719,83.850307637825622,32.487614817917347,2.6910195083667845,48.788183219730854,45.851826403290033,37.600329103569187,43.461549712345004,20.564128746589024,20.770954790214695,48.784515465299293,59.576736014957227,62.445276327431202,50.943006691833332,0.2925451130916672,16.055883577093482,52.39067722174029,59.517571335658431,40.801958349222936,20.375534353156883,56.036714054023221,10.089830614005526,62.67047252443929,37.835652989645794,35.727389223873615,60.771582106749214,45.617452189947166,53.789999478807054,40.123179173097014,27.802804742008448,62.359878855446972,19.123878176634513,85.628517986585706,18.859073091919225,26.775801224634051,59.830132978657879,65.795914224659398,36.176631867264703,20.508597699925303,45.743016200760998,45.59441882558167,47.743862872322396,57.894533406943076,50.589960817247629,46.921614264448479,54.072393302495286,39.883968353892364,15.673699571440617,73.364716306949646,32.067203727861241,76.49099025006096,47.541161640857652,27.374801618357498,77.328961464265987,26.290501665323973,63.080552201097206,37.71225558780133,36.275878630578518,75.813918760667249,62.18135561297337,64.218657845631242,48.73641418106854,59.908272840703525,36.806589184328914,69.575041145707175,55.708189941321812,57.046327756717801,39.897830759485565,20.716510747248925,28.883392045274377,58.964062875136733,46.520788026973605,43.250911160682641,39.113159495716296,20.538053458556533,26.039805101230744,-1.224797332659362,50.221372210731111,12.108232759560151,35.979430062075451,35.539257617046438,27.43035179624955,67.301210332661853,73.326079841703176,97.813799085095525,50.300414266685642,61.307006082187094,33.903906724726156,74.458717326944068,57.858938577895358,80.032973797991872,53.923078297947846,90.952751206234097,55.955868830904365,13.760361163566509,79.33056470813851,34.11727351446946,22.603649688884616,46.658206288392343,9.0754994216064624,50.121498476713896,56.731201230237879,33.681259881705039,29.764654903983075,37.062504695107535,42.238036241382368,33.749024815857403,57.05628483990828,24.160709244509537,9.0472080664088335,44.307901623969279,45.364762970556818,23.188108398889501,27.843296963100631,49.906854846825205,70.766967242583632,57.694841777905815,44.373253105829157,59.088271064062916,50.741201561565198,45.721743176380791,69.007618202517435,27.878969144696992,62.64037817964951,64.217547005663306,46.322153817241386,19.269075867409509,13.74176947089533,69.345468290150166,39.738610620920859,60.402835818007588,39.352833031366266,83.480539092173188,70.532805129264787,22.658159132425983,63.385526601846017,16.795734423523147,47.893856451536216,74.190392199903727,44.619742032140493,57.87978079542517,75.379716128110886,51.301806431884565,10.181043037523825,35.442216363425054,36.928770100076989,26.402359735841554,55.518069490790367,26.709053428843617,46.674481778716043,50.271444040661059,41.167455981175102,22.350450943534572,39.440550136690341,22.579329916586477,73.41040881164372,46.261566116785005,79.924172669649124,21.262426095083356,23.17820594149331,72.680067252988607,60.878607397278145,77.729686583081886,27.260825641453266,42.59027909735839,36.446224960188069,52.087620409826442,65.688042995830372,94.51126175311704,73.047726732368261,37.966540494312838,28.852758451054495,49.703486942996584,53.022308871150017,63.780880075568952,65.986404870326311,87.874406371886536,29.873588952546317,36.528566889464855,36.465448608001068,39.59301041314999,43.699059523021184,67.856042183314756,42.212491199995085,43.303119437148176,28.897669155771535,12.87629550509155,20.335889199127752,39.951023537044726,20.487391358862318,47.719058659548558,42.243955700347826,55.578457709401846,57.953952601179473,38.671426763137184,34.312084563076489,37.285050817454852,50.225693557411432,33.885699723536767,20.429987732941903,49.93394280038774,45.52444826066494,14.576311384638149,57.465944911042847,20.2703739212205,9.2686045443018283,26.82070334752401,29.856948520367343,-1.2841612820823969,54.104848434527717,26.182284548878673,80.948022976517677,47.646546481177204,79.062267956634358,69.145300543556615,41.21528641755382,64.399136476839573,44.514562577009201,51.195520307247833,59.520337541898094,38.972702320665121,90.418944674854473,43.009510099887848,55.700467767193913,21.096938668439783,17.334451497842863,52.581014384826027,40.066333817318082,56.585391882807016,65.474418549487979,14.074198527882496,51.327267380431294,27.217449406161904,53.558322440832853,69.625077705830336,15.374484661966562,42.241121018926307,42.119716505830489,53.569051162029311,40.990497862299279,55.846918212870754,10.473461634169022,35.592681590467691,39.661518186330795,67.101475517575935,31.122481860220432,46.918611992771424,36.897080304721989,48.734584219132863,22.673424234613776,12.040547068541251,9.0109117378791179,42.986683227742716,44.246494557708502,45.532296581193805,67.856802445525915,22.907081549987197,40.753483261913061,89.559149275844291,34.403115184356764,80.875272296369076,4.2536145690828553,61.018407865116991,33.571835034216441,2.3992487515012435,44.172438324739538,24.640693491945662,73.337761485949159,23.766315497457981,40.016548340519272,21.004965559889872,79.517734152575329,33.117444204166524,69.428970024610564,54.498528802767396,32.443326669434704,70.922729558621839,36.456569050128259,14.137593663608033,57.471142242352165,58.900109013542533,48.778552302469812,40.988168193027377,52.354114577795073,82.599069360022753,36.243062670032181,33.8910102037092,51.284301380316414,77.403316183015704,27.351001871128876,45.923602067554988,82.27615720902881,26.598954346651833,56.66638607531786,37.225356264660753,45.353277806813516,3.3095450413723788,47.12439621488253,53.607719803849861],\"y\":[1.8486750495620072,1.9027421889826654,1.8871908796019852,2.0904395835474134,1.9954518893733622,1.8570788398385047,2.0812850533984601,2.0615283212624491,1.9853524074889719,2.0131885562092067,2.1669675958342851,2.1337130988016724,2.1787670269608497,1.8322224126197397,2.1401040853001176,2.1560183126479386,2.0361052896827458,1.8270473225973547,2.0800511795096099,2.1988136366941036,2.0071093732491136,1.889559398777783,1.986080524045974,1.9065439999103546,2.0026963747106494,2.0459823591634629,2.1977171281352641,2.0225951721891762,1.9349291904829442,1.8882996672764421,1.9278147074393928,2.0874406209215524,1.8209674842655659,2.0189684968441726,1.808998040203005,1.9424654116854072,2.0381665068678556,1.9816866854205728,2.0815396178513765,2.1188501642085611,1.9504755021072924,1.9356264949776232,2.069649747107178,2.0179683003574609,1.860996932350099,2.0132433066144584,2.027458630502224,1.9105317484587432,2.090159252937883,2.1404660758562386,1.9350054669193923,2.1749623519368471,2.0317657648585739,1.8278775705024599,1.9595358287915587,1.8243346222676338,2.0163040828891097,2.0782329849898815,1.9972209826111793,2.1424316132441161,2.0059910298325123,1.9875560195185245,1.9298346298746765,2.0803677933290601,1.8515116804279388,1.8677512804977596,1.8739136380143464,2.1380312061868607,1.8834202012047172,2.0195891937240957,1.9089028373360635,1.971957430895418,2.1982285312376915,2.1978214015252888,2.071806967072189,1.9775174275040626,2.0623940488323571,1.8410071869380773,2.0997521253302693,1.8199564022012056,1.9213858246803284,2.03262533955276,1.8219567227177322,1.9967290345579385,1.8138527125120163,1.9851830816827714,2.1609241171739995,1.8000508676283062,2.001230850815773,2.1975543663837014,2.1524981166236103,2.1903466759249568,2.1567750835791228,1.8394160096533596,1.8430708929896356,2.1893786530941726,1.9197017639875411,1.8907632092013955,1.8337235025130212,1.814129996765405,2.1356368907727301,1.8417482949793338,2.0687072471715511,2.1666513797827065,2.0500769067555664,1.9044898641295731,1.9384519381448626,1.8615893599577249,2.0234563909471035,1.9109406300820411,1.8868951490148902,1.9931842624209821,2.045512263290584,1.9394407026469707,1.9953054476529359,1.9958485547453164,1.9332323944196106,1.9084113341756166,1.9313338840380312,1.8192977484315633,2.0292165101505817,2.0778267340734602,2.0850979045964779,2.1551785159856083,2.0986333692446353,2.1716602519154549,2.1801638059318065,2.1252185935154557,2.1785257836803793,1.9362743102014064,1.9816370395943523,2.1759085900150241,1.9198441276326776,1.8979632400907576,1.983387840166688,1.913055232167244,1.8388501389883458,2.1092356443405151,2.1704226311296226,1.8290669954381884,1.8820071760565042,2.0987183903343976,2.1501534043811263,2.0414352154359223,1.9726075974293054,2.1017655276693405,2.186852608807385,1.8339187188073993,1.896464338991791,1.9272548575885593,1.8659280966967344,1.9737390067428351,2.1508558893576266,2.1517363124527038,2.191188404522836,2.1982126817107202,1.811669247969985,2.1570635914802549,2.1998012505471705,2.0083248377777636,1.922103279735893,2.1986731404438613,1.9833358657546341,2.0025959013029935,2.1272732644341885,1.9616645555943251,2.0277044800110162,2.1741377987898884,1.8306951805017888,1.9912411640398204,2.0981290790252389,2.0326338277198372,1.9676595202647149,2.1969464742578566,1.9044286767020822,1.9408146630972625,2.0377237775363026,2.1657887124456465,1.8787090181373061,1.9699664382264017,1.9770519297569991,1.907446039840579,2.0553923862054946,2.0253148474730551,2.061383938603103,1.8186773705296218,2.0616007789969446,1.9186038881540299,2.0427512614987791,2.1831903624348343,1.8205325946211814,1.8247320231981576,1.9832789104431867,1.9699360118247569,1.8129602911882103,2.1523560520261524,1.912712076306343,2.1058964889496563,2.0743797007016838,1.9789088249206543,1.8284159107133746,2.1210052595473825,1.953118599485606,2.0274979085661471,2.0405116320587693,2.065847452171147,2.0911140287294985,1.959449983946979,2.0118157418444751,1.8517397860996425,2.1949405450373889,1.9307252269238233,2.0790205297991635,1.9045271312817931,1.8757372891530395,2.1805420152843,1.9699240328744054,2.170612844079733,1.8857582678087055,2.0702302911318839,1.8129697719588875,1.8270097115077077,1.8583027250133455,2.170782547350973,1.8413637832738459,2.1234830180183053,1.8237552972510458,1.9398915476165712,1.9044771724380554,2.1568703691475095,2.1927453462034463,2.0338708051480352,2.0793715811334552,1.9101404883898794,1.8175333930179476,1.8362614471465348,1.9616711097769439,1.8434629490599037,2.0692311952821911,1.9238268845714628,2.1993354332633315,1.8123179831542076,2.110324686858803,1.9888114796020091,2.1649125146679582,1.9811246532015503,1.9443640582263471,1.8431885684840381,2.1693348477594556,2.1123709953390062,2.1758241602219641,1.8330442222766579,2.1206130367703735,1.837018307391554,1.8692401239648462,1.9256811705417931,2.0653620311059058,2.1706994011066856,1.8826678910292685,1.8803095112554729,2.1492352892644702,1.9977507061325013,1.9440277467481792,2.146027803979814,1.9275280931033194,1.9418763669207693,1.8800240444019436,2.1244521524757145,2.0292838892899452,1.9968696723692119,2.0708142871968449,2.0355561586096882,2.014657179545611,2.1869706328026952,2.1495678414590658,2.0888095070607959,2.1482133340090512,1.9666874611750245,2.0992346351034938,2.0683175680227577,2.1310074910521508,2.0547606185078622,1.9627683277241885,1.9413414583541453,1.9204906753264368,1.9989899879321456,1.8235203311778605,1.9077718287706376,1.8260488354600966,1.8043252780102192,1.8871970394626261,1.8073307342827321,2.1632104966789485,1.8005819120444357,1.8663045947439969,1.8144473156891763,1.8393549425527453,1.8842384852468967,2.0586006461642681,2.188418410997838,2.1376206333748997,2.0770274020731447],\"text\":[\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  83.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:   3.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:   0.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  16.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  10.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  86.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  66.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  16.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  73.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  76.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  76.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  76.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  70.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  30.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:   0.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  13.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  66.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  73.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  96.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  73.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  80.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  90.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  13.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  80.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  10.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  30.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  10.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  70.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  70.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  13.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  70.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  83.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  70.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  16.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  73.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  76.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  10.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  73.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  80.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  73.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  76.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  66.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  93.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  73.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  30.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  66.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  86.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  30.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  66.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  30.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  13.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  13.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  10.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  30.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:   0.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  80.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  80.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  70.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  63.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  90.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  16.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  66.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  13.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  70.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  16.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  10.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  66.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  30.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  13.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  10.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  66.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  90.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  80.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:   3.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:   3.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  43.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  73.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  23.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  20.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  80.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  70.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  70.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  13.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  60.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  40.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  83.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  33.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  50.000000<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  76.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  83.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  26.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  56.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  36.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:   3.333333<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  46.666667<br />jc15a: No\",\"jc15a: No<br />IndiceASP:  53.333333<br />jc15a: No\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"opacity\":1,\"size\":5.6692913385826778,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"No\",\"legendgroup\":\"No\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":46.046948356807512,\"r\":7.3059360730593621,\"b\":42.46703968100843,\"l\":10.958904109589042},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"El apoyo al sistema político según el sexo\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-6.3911201637859127,105.96197523369143],\"tickmode\":\"array\",\"ticktext\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\"],\"tickvals\":[1,2.0000000000000009,3.0000000000000009,4.0000000000000009,5.0000000000000009,6.0000000000000009,7.0000000000000009,8.0000000000000036,9,10,11,12,13,14,15,16,17,18,19,20,21,21.999999999999996,23.000000000000004,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50.000000000000007,50.999999999999993,52,53.000000000000007,54,55,55.999999999999993,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100],\"categoryorder\":\"array\",\"categoryarray\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716894984},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Index\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,2.6000000000000001],\"tickmode\":\"array\",\"ticktext\":[\"Si\",\"No\"],\"tickvals\":[1,2],\"categoryorder\":\"array\",\"categoryarray\":[\"Si\",\"No\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":false,\"tickfont\":{\"color\":null,\"family\":null,\"size\":0},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716894984},\"title\":{\"text\":\"jc15a\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"61cc65de5137\":{\"x\":{},\"y\":{},\"colour\":{},\"type\":\"box\"},\"61cc16ee48b6\":{\"x\":{},\"y\":{},\"colour\":{}}},\"cur_data\":\"61cc65de5137\",\"visdat\":{\"61cc65de5137\":[\"function (y) \",\"x\"],\"61cc16ee48b6\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nFigure 1: El apoyo al sistema político según el sexo (ENDO 2020).\n:::\n:::\n\n\n**Interpretación**:\n\n\n",
    "supporting": [
      "s4-ejercicio-semana4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\r\n<script src=\"site_libs/plotly-binding-4.10.4/plotly.js\"></script>\r\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\r\n<link href=\"site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}