{
  "hash": "24a4a41a0f4499a52abafd906637b7f9",
  "result": {
    "markdown": "---\naliases:\n  - ejercicio-semana14.html\n---\n\n\n\n\n# Regresión lineal múltiple II\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#getwd() \n#setwd(\"\")\nlibrary(rio)\ndata = import(\"./data/s14/ACOSO_2019.sav\")\n```\n:::\n\n\n\n*NOTA: argumentar con datos*\n\nEjemplo 1: Determinates del acoso callejero.\n\n¿QUÉ DETERMINA LOS EVENTOS DE ACOSO CALLEJERO?\n\nACOSO CALLEJEROR -> # de eventos de acisi callejero que sufrio una persona.\n\nVD -> # de eventos de acoso callejero  -> \n\nVI -> edad (numérica) (EDAD)\n      Sexo (Dicotómica) (SEXO)\n      Nivel socioeconómico (NSEGRUP)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(data) # lectura de la base de datos\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"SERIE\"         \"NVONRO\"        \"NSEGRUP\"       \"NSE\"          \n [5] \"SEXO\"          \"GEDAD\"         \"EDAD\"          \"NIVEDU\"       \n [9] \"P10A\"          \"P10B\"          \"P10C\"          \"P11A\"         \n[13] \"P11B\"          \"P11C\"          \"P12A\"          \"P12B\"         \n[17] \"P12C\"          \"P12D\"          \"P12E\"          \"P12F\"         \n[21] \"P12G\"          \"P12H\"          \"P13A\"          \"P13B\"         \n[25] \"P13C\"          \"P13D\"          \"P13E\"          \"P13F\"         \n[29] \"P13G\"          \"P13H\"          \"indiceAC\"      \"indiceAC_dico\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(data$EDAD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"numeric\"\n```\n:::\n\n```{.r .cell-code}\nclass(data$SEXO)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"numeric\"\n```\n:::\n\n```{.r .cell-code}\nclass(data$NSEGRUP)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"numeric\"\n```\n:::\n\n```{.r .cell-code}\nstr(data$EDAD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:680] 52 48 62 37 34 60 26 18 38 39 ...\n - attr(*, \"format.spss\")= chr \"F8.2\"\n```\n:::\n\n```{.r .cell-code}\nstr(data$SEXO)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:680] 2 1 2 2 1 1 2 1 1 2 ...\n - attr(*, \"format.spss\")= chr \"F8.2\"\n```\n:::\n\n```{.r .cell-code}\nstr(data$NSEGRUP)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:680] 3 2 3 2 2 1 2 1 1 1 ...\n - attr(*, \"format.spss\")= chr \"F8.2\"\n```\n:::\n\n```{.r .cell-code}\ntable(data$EDAD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 \n20 20 19 15 19 10 13 19 11  8 19 24 27  7 14 12  8 14 15 10 18 11 16 12 17 18 \n44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 \n17 21 11 11 14  3 12  8 10 11 10  8  7  4  5  6 14  7  9  6 10  8  8  5  3  4 \n70 71 72 73 74 75 76 77 78 79 80 82 83 84 85 89 90 \n 9  3  5  1  5  7  3  3  3  2  2  2  2  2  1  1  1 \n```\n:::\n\n```{.r .cell-code}\ntable(data$SEXO)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2 \n326 354 \n```\n:::\n\n```{.r .cell-code}\ntable(data$NSEGRUP)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3 \n163 330 187 \n```\n:::\n:::\n\n\n\n    + SEXO (Está como numérica)\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$SEXO<-as.factor(data$SEXO) # NECESITAMOS CONVERTIRLO A FACTOR de numérica\nlevels(data$SEXO)<-c(\"Hombre\",\"Mujer\")\n\n# OTRO CÓDIGO PARA CORRER SI NO FUNCIONA el anterior: \n# data$SEXO=factor(data$SEXO, levels = levels(data$SEXO), \n#                  labels = c(\"Hombre\",\"Mujer\"))\n\ntable(data$SEXO)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nHombre  Mujer \n   326    354 \n```\n:::\n:::\n\n\n\n\n    + NIVEL SOCIECONÓMICO (NSEGRUP) (hacer esto en una variable categorica ordinal independiente)\nes una variable ordinal, pero la vamos a definir como una variable factor con tres niveles\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$NSEGRUP = as.factor(data$NSEGRUP)\ndata$NSEGRUP = factor(data$NSEGRUP, levels = levels(data$NSEGRUP), \n                      labels = c(\"AB\", \"C\", \"DE\"))\ntable(data$NSEGRUP)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n AB   C  DE \n163 330 187 \n```\n:::\n:::\n\n\n------------------------------------------------------------------------------------------------------------------------------\n####RECORDAR:\n\nCuando tenemos variables independientes categoricas de más de dos grupos.\nen este caso sexo -> no hay problema (solo tiene dis grupos). \n\nPero ¿qué hacer con la variable (NSEGRUP) NIVEL SOCIECONÓMICO que tiene 3 variable?\nPara la interpretación Va a ser complicado considerarla como una variable ordinal. Entonces, tenemos que dicotomizarlas.\n\nPor ej: \n\nvariable categórica Ordinal de 3 categorias:\n\n        NSEGRUP: \n--------\n1   A/B\n2   C\n3   D/D\n--------\nCONVERTIR A UNA VARIABLE EN DUMMY (1 Y 0) / DICOTOMIZACIÓN: *EN CASOS DONDE LA VARIABLE CATEGORICA TENGA MÁS DE 2 CATEGORIAS ES CONVENIENTE CONVERTIRLA EN TANTO EL NUMERO DE CATEOGRIAS TENGA COMO VARIABLES DICOTOMICAS QUE PODAMOS GENERAR* -> \n\nAHORA SON 3 VARIABLES DICOTÓMICAS:\n------------------------------\n    NSE_A/B   NSE_C   NSE_D/E\nSÍ    1         1           1\nNO    0         0           0\n------------------------------\nEs más sencillo interpretarlo así -> como dicotomica (tambien cuando es numerica)\n\n*NOTA:*\n*Cuando tenemos variables independientes categoricas de más de dos grupos, (si está en numérica) LA VOLVEMOS A FACTOR y LUEGO LA CONVERTIMOS EN VARIABLES DUMMY.*\n\n\nPor ejemplo:\n\nDiría usted que… ¿es más riesgoso para un hombre, para una mujer o es igual de riesgoso para ambos?\n\n(POLITÓMICA)\n P11A: \n--------\n1   Hombre\n2   Mujer\n3   Ambos\n--------\n\nDICOTOMIZACIÓN:\n\nAHORA SON 3 VARIABLES DICOTÓMICAS:\n------------------------------\n    P11A_Hombre   P11A_Mujer   P11A_Ambos\nSÍ    1             1           1\nNO    0             0           0\n------------------------------\n\n\n*NOTA* --> DEPENDE UTILIZAR LA DICOTOMIZACIÓN \n\nPOR EJEMPLO:\nORDINAL DE 4 CATEGORIAS\n¿Qué tan seguro(a) o inseguro(a) se siente usted caminando en la calle…\n\nP10A\n--------\n1   Muy seguro(a)\n2   Seguro(a)\n3   Inseguro(a)\n4   Muy inseguro(a)\n--------\n\nDICOTOMIZACIÓN:\n\nAHORA SON 4 VARIABLES DICOTÓMICAS:\n------------------------------------------------------------------------------------------\n    P10A_Muy seguro(a)   P10A_seguro(a)    P10A_Inseguro(a)     P10A_Muy inseguro(a) \nSÍ    1                        1                   1                   1\nNO    0                        0                   0                   0\n------------------------------------------------------------------------------------------\n\nSI LO HACEMOS ASÍ PODEMOS DISTINGUIR Y COMPARAR MEJOR LAS VARIABLES. Si nos interesa disintguir entre -> P10A_Inseguro(a) y P10A_Muy inseguro(a) *ver la base de datos si hay mucha diferencia entre las variables y así usar esta forma o la siguiente:*\n\n*PERO...* SI SOLO ME INTERESA SEGURIDAD E INSEGURIDAD -> TAMBIÉN PODEMOS CONVERTIRLOS EN 2 GRUPOS DE VARIABLES DICOTOMICAS:\n\nENTONCES:\n----------------------------------------------------------------------------------\n   |  P10A_Muy seguro(a)/P10A_seguro(a)  | P10A_Inseguro(a)/P10A_Muy inseguro(a) | \nSÍ |                 1                   |               1                       | \nNO |                 0                   |               0                       |            \n----------------------------------------------------------------------------------\n\n ###ESTO SE LLAMA TRATAMIENTO DE LA BASE.\n\n------------------------------------------------------------------------------------------------------------------------------\n\nContinuando...\n\nDicotomizaremos NSEGRUP:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fastDummies)\ndata=dummy_cols(data, select_columns = c(\"SEXO\", \"NSEGRUP\"))\nnames(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"SERIE\"         \"NVONRO\"        \"NSEGRUP\"       \"NSE\"          \n [5] \"SEXO\"          \"GEDAD\"         \"EDAD\"          \"NIVEDU\"       \n [9] \"P10A\"          \"P10B\"          \"P10C\"          \"P11A\"         \n[13] \"P11B\"          \"P11C\"          \"P12A\"          \"P12B\"         \n[17] \"P12C\"          \"P12D\"          \"P12E\"          \"P12F\"         \n[21] \"P12G\"          \"P12H\"          \"P13A\"          \"P13B\"         \n[25] \"P13C\"          \"P13D\"          \"P13E\"          \"P13F\"         \n[29] \"P13G\"          \"P13H\"          \"indiceAC\"      \"indiceAC_dico\"\n[33] \"SEXO_Hombre\"   \"SEXO_Mujer\"    \"NSEGRUP_AB\"    \"NSEGRUP_C\"    \n[37] \"NSEGRUP_DE\"   \n```\n:::\n:::\n\n\nCREAMOS LA VARIABLE DEPENDIENTE (ÍNDICE DE ACOSO):\n\n::: {.cell}\n\n```{.r .cell-code}\nACOSO <- data$P12A+data$P12B+data$P12C+data$P12D+data$P12E+data$P12F+data$P12G+data$P12H\n\ndata$ACOSO <- data$P12A+data$P12B+data$P12C+data$P12D+data$P12E+data$P12F+data$P12G+data$P12H #Para crear como variable independiente (VariablesSeleccionadas)\n\nsummary(ACOSO)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  0.000   0.000   0.000   1.465   3.000   8.000       1 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo1<-lm(ACOSO ~ EDAD + SEXO + NSEGRUP, data = data)\n\nsummary(modelo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ACOSO ~ EDAD + SEXO + NSEGRUP, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.3776 -1.2631 -0.4456  0.8324  8.1582 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.529154   0.237491  10.649   <2e-16 ***\nEDAD        -0.040254   0.004143  -9.715   <2e-16 ***\nSEXOMujer    1.653558   0.138687  11.923   <2e-16 ***\nNSEGRUPC    -0.352581   0.172819  -2.040   0.0417 *  \nNSEGRUPDE   -0.264426   0.193368  -1.367   0.1719    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.801 on 674 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.2633,\tAdjusted R-squared:  0.2589 \nF-statistic: 60.22 on 4 and 674 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nIDENTIFICAMOS:\nNSEGRUPC    -0.352581 \nNSEGRUPDE   -0.264426\n\n¿cómo interpreto de cómo influye C, D o E?\n\nSEXOMujer    1.653558\n-> CUANDO UNA Persona es mujer, en comparacion de ser hombre, aumenta el numero de eventos de acaso callejero en 1.653558 eventos (casi dos eventos).\n\n*R está tomando como referencia al valor menor (Hombre), por ello, NO aparece en la tabla*\n1: Hombre\n2: Mujer \n\nEn el caso de NSEGRUP se toma como referencia a NSEGRUP_A\n1: A\n\npor eso compara \"C\" con \"A\" y \"DE\" con \"A\"\n\n\nENTONCES, SI QUEREMOS TOMAR COMO REFERENCIA A LA MUJER -> especificamos:\n\n    REFERENCIA CON LA MUJER Y CON NIVEL SOCIOECONOMICO NSEGRUP_C + NSEGRUP_AB (O SEA, EL VALOR DE REFERENCIA ES EL QUE NO SE COLOCA EN EL CODIGO)\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo2 <- lm(ACOSO ~ EDAD + SEXO_Hombre + NSEGRUP_C + NSEGRUP_AB, data = data)\n\nsummary(modelo2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ACOSO ~ EDAD + SEXO_Hombre + NSEGRUP_C + NSEGRUP_AB, \n    data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.3776 -1.2631 -0.4456  0.8324  8.1582 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.918286   0.228369  17.158   <2e-16 ***\nEDAD        -0.040254   0.004143  -9.715   <2e-16 ***\nSEXO_Hombre -1.653558   0.138687 -11.923   <2e-16 ***\nNSEGRUP_C   -0.088155   0.165477  -0.533    0.594    \nNSEGRUP_AB   0.264426   0.193368   1.367    0.172    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.801 on 674 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.2633,\tAdjusted R-squared:  0.2589 \nF-statistic: 60.22 on 4 and 674 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nLA DIFERENCIA ENTRE EL MODELO 1 Y modelo2 es la interpretacion:\n\nSEXO_Hombre -1.653558   \nNSEGRUP_C   -0.088155      \nNSEGRUP_AB   0.264426\n\n + CUANDO UNA Persona es hombre, en comparación de ser mujer, disminuye el numero de eventos de acaso callejero en 1.653558 eventos (casi dos eventos).\n \n LA DOS NO SON SIGNIFICATIVAS (P-value mayor a 0.05), pero vemos el sentido:\n\n + Cuando una persona es hombre, en comparación de ser mujer, y es parte del grupo socioeconomico C, disminuye el numero de eventos de acaso callejero en 0.088155 eventos.\n \n  + Cuando una persona es hombre, en comparación de ser mujer, y es parte del grupo socioeconomico A/B, aumenta el numero de eventos de acaso callejero en 0.264426 eventos.\n\n-------------------------------------------------------------------------------\n\n + ¿Qué sucede si aumento la variable caminar en la noche (seguridad)¿ -> P10B\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data$P10B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4 \n  4  28 289 359 \n```\n:::\n:::\n\n1 = muy seguro \n4 = muy inseguro \n-------------------------------------------------------------------------------\n*NO HACER * -> si lo considramos como numerica, cuando interpretamos sería dificil \n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo3 <- lm(ACOSO ~ P10B, data = data)\n\nsummary(modelo3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ACOSO ~ P10B, data = data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-1.594 -1.594 -1.349  1.406  6.651 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)  \n(Intercept)   0.6133     0.4666   1.314   0.1891  \nP10B          0.2453     0.1323   1.854   0.0642 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.089 on 677 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.005051,\tAdjusted R-squared:  0.003582 \nF-statistic: 3.437 on 1 and 677 DF,  p-value: 0.06419\n```\n:::\n:::\n\n¿CÓMO SE INTERPRETARÍA?\n  + POR CADA NIVEL QUE UNA PERSONA AUMENTA SU SENSACIÓN DE INSEGURIDAD, EL NUMERO DE EVENTOS DE ACASO AUMENTA EN 0.2453     \n-------------------------------------------\n\nENTONCES, MEJOR DICOTOMIZAR:\n\n    en este caso,dicotimizar agrupando\n1 -> Formateamos\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(data$P10B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:680] 4 3 3 4 4 4 1 3 2 4 ...\n - attr(*, \"format.spss\")= chr \"F8.2\"\n```\n:::\n\n```{.r .cell-code}\ndata$P10B = as.numeric(data$P10B)\n```\n:::\n\n - Recodificando\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\ndata$seguridad = recode(data$P10B, \"c(1,2) = 'Seguro'; c(3,4) = 'Inseguro'\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo4 <- lm(ACOSO ~ seguridad, data = data)\n\nsummary(modelo4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ACOSO ~ seguridad, data = data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-1.504 -1.504 -1.504  1.496  6.496 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      1.50386    0.08205   18.33   <2e-16 ***\nseguridadSeguro -0.81636    0.37794   -2.16   0.0311 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.087 on 677 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.006845,\tAdjusted R-squared:  0.005378 \nF-statistic: 4.666 on 1 and 677 DF,  p-value: 0.03112\n```\n:::\n:::\n\nseguridadSeguro -0.81636 \n\nINTERPRETACIÓN:\n\ncuando una persona se siente segura, en comparación de una persona que se siente insegura, disminuye el numero de eventos de acoso callejero en 0.81636. \n\n*Más fácil de interpretar*\n\n\n*La recomendación es que las variables independientes sean numerica o dicotomicas.* si no son dictomicas, debemos convertirlas.\n\n-------------------------------------------\n\n + Ahora agregamos EDAD y SEXO:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo5 <- lm(ACOSO ~ seguridad + EDAD + SEXO, data = data)\nsummary(modelo5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ACOSO ~ seguridad + EDAD + SEXO, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1415 -1.2696 -0.4685  0.8080  8.0048 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      2.305609   0.201179  11.461   <2e-16 ***\nseguridadSeguro -0.567257   0.326975  -1.735   0.0832 .  \nEDAD            -0.039834   0.004135  -9.634   <2e-16 ***\nSEXOMujer        1.632584   0.138712  11.770   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.802 on 675 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.262,\tAdjusted R-squared:  0.2587 \nF-statistic: 79.87 on 3 and 675 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\n- el modelo sí es valido (p-value: < 2.2e-16)\n\n- explica el 26% de la variabilidad de los datos\n\n- si cada variable independiente influye:\n\nseguridadSeguro 0.0832 .  \nEDAD            <2e-16 ***\nSEXOMujer       <2e-16\n\nAhora seguridad ya no es tan relevante. las otras dos sí.\n\n*RECORDAR: hay una relacion espurea y al incorporar otras variables, esa relacion desaparece* -> como en este caso: en el modelo4, hay una relacion entre seguridad y numero de eventos. Pero al incorporar las nuevas variables en el nuevo modelo 5, dicha relación desaparece.   \n\n\n- Por cada año que una persona aumenta su edad, el numero de eventos de acosos callejero disminuye en 0.039834 eventos.\n\n- VIENDO LOS COEFICIENTES ESTANDARIZADOS\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#lm.beta(modelo5)\n```\n:::\n\n#Conlusión: (las variables que impactan más son EDAD y luego SEXO)\n\n#INTERPRETACIÓN:\n  + Entonces, la violencia no ocurre por igual entre hombres y mujeres. eN EFECTO, CUANDO HABLAMOS de acoso callejero, hay evidencia que corrobora que la muejres registra mayor numero de eventos de acoso callejero. Aun solamente por la condicion de ser mujer se incrementa en al menos (1.632584) 2 eventos de acoso callejero más que sus pares hombres. En lo que refiere a edad, son las muejeres más jovenes las que reciben mayor cantidad de eventos de acoso callejero. En suma, Mientras mas jóvenes y sean mujeres, son más propensas a sufrir MAYOR NUMERo de eventos de acoso callejero.\n\n  + Tambien se ha indagado si el nivel sociecnomico es un factor, pero se ha encontrado de que no hay evidencia suficiente de que ocurra dependiendo el nivel sociecomonico. Es decor, estos acosos callejeros ocurre sin importar el numero de eventos de caso callejero. \n\n  + Aun se ha evidenciado en el modelo4 una relacion espurea entre el sensación de seguridad de caminar en la calle y el numero de eventos de acoso callejeros. pero está relacion deja de exisitir cuando se agragan las variables EDAD y SEXO.\n\n\n-----------------------------------------------------------------------------------------------------------\n\n## ¿Qué hacer en estas situaciones en las que tenemos varias variables y no sabemos cual influye más en otra?\n  - ¿Cuál de estas variables puede ayudarnos a explicar mejor la variable dependiente?\n  - En general se suele decir, que impacta más las variables sociodemograficas (edad, sexo, Nivel sociecnomica...). Pero también pueden impactar otras variables.\n\n  + *RECORDAR* -> SI PARTIMOS DESDE CERO -> CUANDO NO SE NOS DA NINGUNA VARIABLE INDEPENDIENTE, TENEMOS QUE BUSCARLAS.\n  \n  - ENTONCES,\n1. Realizar el analisis bivariado\n2. ensayar cuales serian las variables independientes.\n...\n\nHAY MÉTODOS PARA SELECCIONAR QUÉ VARIABLES INDEPENDIENTES SON MEJORES. ADEMÁS NO DEBEN ESTAR RELACIONADAS ENTRE SI. \n    FORWARD (IR CONSTRUYENDO) COLOCANDO VARIABLES POR VARIABLE\n    BACKWARD (COLOCAS TODAS LAS VARAIBLES Y LUEGO VAN ELIMINANDO LAS QUE NO SON SIGNFICATIVAS)\n\n\n## 1. UTILIZANDO EL MÉTODO \n  + Filtrando y creando nueva base:\n\n::: {.cell}\n\n```{.r .cell-code}\nVariablesSeleccionadas = c(\"ACOSO\", \"SEXO_Mujer\", \"NIVEDU\", \"NSEGRUP\", \n                           \"NSEGRUP_AB\", \"NSEGRUP_DE\", \"seguridad\", \"EDAD\")\n\nsubdata = data[VariablesSeleccionadas]\n```\n:::\n\n\n  + INSTALAR y definimos el modelo\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\n\n#ModeloCompleto -> Con todas las variables\nfull.model <- lm(ACOSO ~ ., data = subdata)\nsummary(full.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ACOSO ~ ., data = subdata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1780 -1.2673 -0.4725  0.8406  8.0352 \n\nCoefficients: (2 not defined because of singularities)\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      2.00002    0.48747   4.103 4.58e-05 ***\nSEXO_Mujer       1.65965    0.13964  11.886  < 2e-16 ***\nNIVEDU           0.06269    0.04683   1.339   0.1811    \nNSEGRUPC        -0.22737    0.19813  -1.148   0.2516    \nNSEGRUPDE       -0.06188    0.24797  -0.250   0.8030    \nNSEGRUP_AB            NA         NA      NA       NA    \nNSEGRUP_DE            NA         NA      NA       NA    \nseguridadSeguro -0.57372    0.32631  -1.758   0.0792 .  \nEDAD            -0.03874    0.00429  -9.030  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.798 on 672 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.2687,\tAdjusted R-squared:  0.2621 \nF-statistic: 41.14 on 6 and 672 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## 2. MODELO HACIA ADELANTE  (Forward) + summary\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.hacia.delante <- stepAIC(full.model, direction = \"forward\", \n                      trace = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStart:  AIC=803.31\nACOSO ~ SEXO_Mujer + NIVEDU + NSEGRUP + NSEGRUP_AB + NSEGRUP_DE + \n    seguridad + EDAD\n```\n:::\n\n```{.r .cell-code}\nsummary(model.hacia.delante)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ACOSO ~ SEXO_Mujer + NIVEDU + NSEGRUP + NSEGRUP_AB + \n    NSEGRUP_DE + seguridad + EDAD, data = subdata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1780 -1.2673 -0.4725  0.8406  8.0352 \n\nCoefficients: (2 not defined because of singularities)\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      2.00002    0.48747   4.103 4.58e-05 ***\nSEXO_Mujer       1.65965    0.13964  11.886  < 2e-16 ***\nNIVEDU           0.06269    0.04683   1.339   0.1811    \nNSEGRUPC        -0.22737    0.19813  -1.148   0.2516    \nNSEGRUPDE       -0.06188    0.24797  -0.250   0.8030    \nNSEGRUP_AB            NA         NA      NA       NA    \nNSEGRUP_DE            NA         NA      NA       NA    \nseguridadSeguro -0.57372    0.32631  -1.758   0.0792 .  \nEDAD            -0.03874    0.00429  -9.030  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.798 on 672 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.2687,\tAdjusted R-squared:  0.2621 \nF-statistic: 41.14 on 6 and 672 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## 3. HACIA ATRÁS (Backward)+ summary\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.hacia.atras <- stepAIC(full.model, direction = \"backward\", \n                      trace = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStart:  AIC=803.31\nACOSO ~ SEXO_Mujer + NIVEDU + NSEGRUP + NSEGRUP_AB + NSEGRUP_DE + \n    seguridad + EDAD\n\n\nStep:  AIC=803.31\nACOSO ~ SEXO_Mujer + NIVEDU + NSEGRUP + NSEGRUP_AB + seguridad + \n    EDAD\n\n\nStep:  AIC=803.31\nACOSO ~ SEXO_Mujer + NIVEDU + NSEGRUP + seguridad + EDAD\n\n             Df Sum of Sq    RSS    AIC\n- NSEGRUP     2      6.39 2177.7 801.30\n- NIVEDU      1      5.79 2177.1 803.12\n<none>                    2171.3 803.31\n- seguridad   1      9.99 2181.3 804.43\n- EDAD        1    263.48 2434.8 879.08\n- SEXO_Mujer  1    456.45 2627.8 930.87\n\nStep:  AIC=801.3\nACOSO ~ SEXO_Mujer + NIVEDU + seguridad + EDAD\n\n             Df Sum of Sq    RSS    AIC\n<none>                    2177.7 801.30\n- seguridad   1      9.79 2187.5 802.35\n- NIVEDU      1     13.45 2191.1 803.49\n- EDAD        1    263.76 2441.4 876.93\n- SEXO_Mujer  1    462.11 2639.8 929.97\n```\n:::\n\n```{.r .cell-code}\nsummary(model.hacia.atras)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = ACOSO ~ SEXO_Mujer + NIVEDU + seguridad + EDAD, \n    data = subdata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.0796 -1.2638 -0.4384  0.8233  7.9170 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      1.772577   0.329427   5.381 1.02e-07 ***\nSEXO_Mujer       1.667982   0.139472  11.959  < 2e-16 ***\nNIVEDU           0.074118   0.036323   2.041   0.0417 *  \nseguridadSeguro -0.567958   0.326212  -1.741   0.0821 .  \nEDAD            -0.038075   0.004214  -9.035  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.797 on 674 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.2665,\tAdjusted R-squared:  0.2622 \nF-statistic: 61.22 on 4 and 674 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n  - ¿CUAL SERIA EL MEJOR MODELO EN BASE A LAS VARIABLES INDEPENDIENTES?\n\nEl mejor modelo que explica:\n  - CON ESTE CÓDIGO NO NECESITAMOS CREAR UNA SUBDATA\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(leaps)\nmodelo = regsubsets(\n  ACOSO ~ SEXO + EDAD + seguridad + NIVEDU + NSEGRUP_AB + NSEGRUP_DE,\n  data = data, nbest = 1, nvmax = 10) \nsummary(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSubset selection object\nCall: regsubsets.formula(ACOSO ~ SEXO + EDAD + seguridad + NIVEDU + \n    NSEGRUP_AB + NSEGRUP_DE, data = data, nbest = 1, nvmax = 10)\n6 Variables  (and intercept)\n                Forced in Forced out\nSEXOMujer           FALSE      FALSE\nEDAD                FALSE      FALSE\nseguridadSeguro     FALSE      FALSE\nNIVEDU              FALSE      FALSE\nNSEGRUP_AB          FALSE      FALSE\nNSEGRUP_DE          FALSE      FALSE\n1 subsets of each size up to 6\nSelection Algorithm: exhaustive\n         SEXOMujer EDAD seguridadSeguro NIVEDU NSEGRUP_AB NSEGRUP_DE\n1  ( 1 ) \"*\"       \" \"  \" \"             \" \"    \" \"        \" \"       \n2  ( 1 ) \"*\"       \"*\"  \" \"             \" \"    \" \"        \" \"       \n3  ( 1 ) \"*\"       \"*\"  \" \"             \"*\"    \" \"        \" \"       \n4  ( 1 ) \"*\"       \"*\"  \"*\"             \"*\"    \" \"        \" \"       \n5  ( 1 ) \"*\"       \"*\"  \"*\"             \"*\"    \"*\"        \" \"       \n6  ( 1 ) \"*\"       \"*\"  \"*\"             \"*\"    \"*\"        \"*\"       \n```\n:::\n:::\n\n  - *fijarnos en el asterisco:* \n   + Por ejemplo, la variable SEXO es significativo en todos los modelos\n\n\nCódigo para el gráfico \n\n::: {.cell}\n\n```{.r .cell-code}\n#plot(x, labels=obj$xnames, main=NULL, \n     #scale=c(\"bic\", \"Cp\", \"adjr2\", \"r2\"),\n     #col=gray(seq(0, 0.9, length = 10)),...)\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}