{
  "hash": "dd0ab1db56d97598e8fd857de8fe982e",
  "result": {
    "markdown": "---\naliases:\n  - ejercicio-semana7b.html\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#getwd() \n#setwd(\"\")\n#dir()\n\nlibrary(rio)\ndfbaro <-import(\"./data/s7/b-Latinobarometro_2018_Esp_Spss_v20190303.sav\")\n#names(dfbaro)\n#str(dfbaro)\n#class(dfbaro) \n```\n:::\n\n\n\n**<b style = 'color : #50D050;'>ANALISIS DE VARIABLES CATEGORICAS</b>**\n============================================================\n\n- Co-author: Luis Valverde\n\n## **SELECCIONAR (un subconjunto de la) DATA** <- funcion subset\n  \n  - Subsetear data:\n\n::: {.cell}\n\n```{.r .cell-code}\ndfbaro = subset(dfbaro, IDENPA == 68 | IDENPA == 170 | IDENPA == 604 | IDENPA == 218)\ntable(dfbaro$IDENPA) # | <- signfica o\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  68  170  218  604 \n1200 1200 1200 1200 \n```\n:::\n:::\n\n\n  - Recodificar (cambiar los valores) numeros por paises\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\ndfbaro$pais <- recode(dfbaro$IDENPA, \"68 = 'Bolivia'; 170 = 'Colombia'; 604 = 'Peru'; 218 = 'Ecuador'\")\n\ntable(dfbaro$pais)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Bolivia Colombia  Ecuador     Peru \n    1200     1200     1200     1200 \n```\n:::\n:::\n\n\n## **Descripción de la base**\n\n  - ***Sexo***\n\n::: {.cell}\n\n```{.r .cell-code}\ndfbaro$SEXO = as.factor(dfbaro$SEXO)\nlevels(dfbaro$SEXO) = c(\"Hombre\",\"Mujer\")\n```\n:::\n\n\n  - ***Autoubicación en escala de pobreza-riqueza: Personal***\n\n::: {.cell}\n\n```{.r .cell-code}\ndfbaro$pobr_riq = as.numeric(dfbaro$P10STC.A)\n```\n:::\n\n\n  - ***En términos generales ¿Diría usted que (PAÍS) está gobernado por unos cuantos grupos poderosos en su propio beneficio, o que está gobernado para el bien de todo el pueblo? (ESPERE RESPUESTA Y MARQUE UNA SOLA)***\n\n::: {.cell}\n\n```{.r .cell-code}\ndfbaro$pode_pueblo = as.factor(dfbaro$P14ST)\nlevels(dfbaro$pode_pueblo) = c(\"Poderosos\",\"Pueblo\")\n```\n:::\n\n\n  - ***¿Y en los próximos doce meses, cree que su situación económica y la de su familia será mucho mejor, un poco mejor, igual, un poco peor, o mucho peor qu e la que tiene hoy? (ORDINAL) 5 Mucho peor / 1 Mucho mejor***\n\n::: {.cell}\n\n```{.r .cell-code}\ndfbaro$situ_eco = as.factor(dfbaro$P9STGBSC)\nlevels(dfbaro$situ_eco) = c(\"Mucho mejor\", \"Un poco mejor\", \"Igual\", \"Un poco peor\", \"Mucho peor\")\n```\n:::\n\n\n  - ***¿Diría Ud. que este país… progresado 1, estancado 2, esta retroceso 3?***\n\n::: {.cell}\n\n```{.r .cell-code}\ndfbaro$pais_pro = as.factor(dfbaro$P2STC)\ndfbaro$pais_pro = factor(dfbaro$pais_pro, \n                         levels = levels(dfbaro$pais_pro),  \n                         labels = c(\"Progreso\",\"Estancado\",\"Retrocedio\"),\n                         ordered = T)\ntable(dfbaro$pais_pro)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  Progreso  Estancado Retrocedio \n      1336       2375        948 \n```\n:::\n:::\n\n\n  - ***En general, ¿Diría Ud. que está muy satisfecho, más bien satisfecho, no muy satisfecho o nada satisfecho con el funcionamiento de la democracia en (PAÍS)?*** -> 4 niveles: muy satisfecho, mas bien satisfecho, no muy satisfecho, nada satisfecho\n  \n  - En este caso pasaremos de 4 niveles a 2: \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\ntable(dfbaro$P13STGBS.A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3    4 \n 271  899 2383 1015 \n```\n:::\n\n```{.r .cell-code}\ndfbaro$satis_democracia = as.factor(dfbaro$P13STGBS.A)\ndfbaro$satis_democracia <- recode(dfbaro$P13STGBS.A, \"1:2 = 1; 3:4 =2\")\ntable(dfbaro$satis_democracia)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2 \n1170 3398 \n```\n:::\n\n```{.r .cell-code}\ndfbaro$satis_democracia = as.factor(dfbaro$satis_democracia)\nlevels(dfbaro$satis_democracia) = c(\"Satisfecho\",\"No Satisfecho\")\ntable(dfbaro$satis_democracia)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Satisfecho No Satisfecho \n         1170          3398 \n```\n:::\n:::\n\n\n  - ***¿Cuán justa cree Ud. que es la distribución del ingreso en (PAÍS)?***\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dfbaro$P23ST)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n num [1:4800] 1 3 3 3 4 2 2 NA 3 3 ...\n```\n:::\n\n```{.r .cell-code}\ndfbaro$justo = as.factor(dfbaro$P23ST)\nlevels(dfbaro$justo) = c(\"Muy justa\",\"Justa\",\"Injusta\",\"Muy injusta\")\n```\n:::\n\n\n\n## **DESCRIPCIÓN DE VARIABLES**\n\n  - Calcular las tablas de frecuencias y de frecuencias acumuladas en porcentajes (variables categoricas)\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(jmv) # Para calcular tablas \n\ndescriptives(dfbaro, vars = vars(justo, pode_pueblo, pobr_riq, situ_eco, pais_pro, satis_democracia), freq = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n DESCRIPTIVES\n\n Descriptives                                                                                           \n ────────────────────────────────────────────────────────────────────────────────────────────────────── \n                         justo    pode_pueblo    pobr_riq    situ_eco    pais_pro    satis_democracia   \n ────────────────────────────────────────────────────────────────────────────────────────────────────── \n   N                      4588           4623        4752        4562        4659                4568   \n   Missing                 212            177          48         238         141                 232   \n   Mean                                          4.258628                                               \n   Median                                        5.000000                                               \n   Standard deviation                            1.880180                                               \n   Minimum                                       1.000000                                               \n   Maximum                                       10.00000                                               \n ────────────────────────────────────────────────────────────────────────────────────────────────────── \n\n\n FREQUENCIES\n\n Frequencies of justo                                    \n ─────────────────────────────────────────────────────── \n   justo          Counts    % of Total    Cumulative %   \n ─────────────────────────────────────────────────────── \n   Muy justa          81       1.76548         1.76548   \n   Justa             916      19.96513        21.73060   \n   Injusta          2500      54.48997        76.22058   \n   Muy injusta      1091      23.77942       100.00000   \n ─────────────────────────────────────────────────────── \n\n\n Frequencies of pode_pueblo                              \n ─────────────────────────────────────────────────────── \n   pode_pueblo    Counts    % of Total    Cumulative %   \n ─────────────────────────────────────────────────────── \n   Poderosos        3693      79.88319        79.88319   \n   Pueblo            930      20.11681       100.00000   \n ─────────────────────────────────────────────────────── \n\n\n Frequencies of situ_eco                                   \n ───────────────────────────────────────────────────────── \n   situ_eco         Counts    % of Total    Cumulative %   \n ───────────────────────────────────────────────────────── \n   Mucho mejor         663      14.53310        14.53310   \n   Un poco mejor      1647      36.10259        50.63569   \n   Igual              1662      36.43139        87.06708   \n   Un poco peor        433       9.49145        96.55853   \n   Mucho peor          157       3.44147       100.00000   \n ───────────────────────────────────────────────────────── \n\n\n Frequencies of pais_pro                                \n ────────────────────────────────────────────────────── \n   pais_pro      Counts    % of Total    Cumulative %   \n ────────────────────────────────────────────────────── \n   Progreso        1336      28.67568        28.67568   \n   Estancado       2375      50.97660        79.65229   \n   Retrocedio       948      20.34771       100.00000   \n ────────────────────────────────────────────────────── \n\n\n Frequencies of satis_democracia                              \n ──────────────────────────────────────────────────────────── \n   satis_democracia    Counts    % of Total    Cumulative %   \n ──────────────────────────────────────────────────────────── \n   Satisfecho            1170      25.61296        25.61296   \n   No Satisfecho         3398      74.38704       100.00000   \n ──────────────────────────────────────────────────────────── \n```\n:::\n:::\n\n\n\n\n## TABLA DE CONTINGENCIA\n\nUNIDAD DE ANALISIS: Personas entrevistadas\n  \n  -  Para obtener las frecuencias observadas, solo con la funcion table\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dfbaro$pais, dfbaro$satis_democracia) #tabla cruzada\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          \n           Satisfecho No Satisfecho\n  Bolivia         314           816\n  Colombia        304           841\n  Ecuador         426           740\n  Peru            126          1001\n```\n:::\n:::\n\n\n  - Totales marginales: de filas y columnas\n\n::: {.cell}\n\n```{.r .cell-code}\naddmargins(table(dfbaro$pais, dfbaro$satis_democracia))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          \n           Satisfecho No Satisfecho  Sum\n  Bolivia         314           816 1130\n  Colombia        304           841 1145\n  Ecuador         426           740 1166\n  Peru            126          1001 1127\n  Sum            1170          3398 4568\n```\n:::\n:::\n\n  - Total general de esta tabla: 4568\n\n\n## ***Distribución conjunta***: Porcentaje en relación al total general\n\n  - Bolivia & Satisfechos = 314/4568 = 0.068\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(dfbaro$pais, dfbaro$satis_democracia)) # Para obetner las proporciones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          \n           Satisfecho No Satisfecho\n  Bolivia  0.06873905    0.17863398\n  Colombia 0.06654991    0.18410683\n  Ecuador  0.09325744    0.16199650\n  Peru     0.02758319    0.21913310\n```\n:::\n:::\n\n\n## ***Distribución Marginal***: Porcentaje en relación al total de las filas\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(dfbaro$pais, dfbaro$satis_democracia), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          \n           Satisfecho No Satisfecho\n  Bolivia   0.2778761     0.7221239\n  Colombia  0.2655022     0.7344978\n  Ecuador   0.3653516     0.6346484\n  Peru      0.1118012     0.8881988\n```\n:::\n:::\n\n  - Los peruanos están mas insatisfechos con la democracia 88%\n  \n\n\n  - Porcentaje en relación al total de las columnas\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(dfbaro$pais, dfbaro$satis_democracia), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          \n           Satisfecho No Satisfecho\n  Bolivia   0.2683761     0.2401413\n  Colombia  0.2598291     0.2474985\n  Ecuador   0.3641026     0.2177752\n  Peru      0.1076923     0.2945851\n```\n:::\n\n```{.r .cell-code}\n# Otro modo de ver, cambiando el lugar de las variables:\nprop.table(table(dfbaro$satis_democracia, dfbaro$pais), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               \n                  Bolivia  Colombia   Ecuador      Peru\n  Satisfecho    0.2778761 0.2655022 0.3653516 0.1118012\n  No Satisfecho 0.7221239 0.7344978 0.6346484 0.8881988\n```\n:::\n:::\n\n  - Del total de personas satisfechas con la democracia, los mas satisfechos son los ecuatorianos 36%.\n\n\n## **GRÁFICO**\n\n::: {.cell}\n\n```{.r .cell-code}\ncuadro = prop.table(table(dfbaro$satis_democracia, \n                          dfbaro$pais), 2)\nbarplot(cuadro, legend = rownames(cuadro), axis.lty = 2)\n```\n\n::: {.cell-output-display}\n![](s7-ejercicio-semana7b_files/figure-html/unnamed-chunk-18-1.png){width=100%}\n:::\n:::\n\n\n\n# **<b style = 'color : #50D050;'>FRECUENCIAS ESPERADAS</b>**\n  - Para esto, necesitamos calcular la prueba chi cuadrado + $expected\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dfbaro$satis_democracia, dfbaro$pais)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               \n                Bolivia Colombia Ecuador Peru\n  Satisfecho        314      304     426  126\n  No Satisfecho     816      841     740 1001\n```\n:::\n:::\n\n  - CHI CUADRADO: frecuencias esperadas (si la distribicion es proporcional entre las casillas: si no habria ninguna relacion entre la satisfaccion de la democracia y el pais de procedencia.\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ntablaFesperadas <- chisq.test(dfbaro$satis_democracia, dfbaro$pais)$expected\ntablaFesperadas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                       dfbaro$pais\ndfbaro$satis_democracia  Bolivia Colombia  Ecuador     Peru\n          Satisfecho    289.4264 293.2684 298.6471 288.6581\n          No Satisfecho 840.5736 851.7316 867.3529 838.3419\n```\n:::\n:::\n\n\n\n## **<b style = 'color : #50D050;'>CHI CUADRADO</b>**\n\ngrados de libertad = (filas-1)(columnas-1) \ngrados de libertad = (2-1)(4-1) \ngrados de libertad = 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Con la funcion qchisq se indica el nivel de confianza y el numeros de los grados de libertad (df) para obetener el chi cuadrado teorico:\nqchisq(0.95, 3) # Valor de la tabla\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.814728\n```\n:::\n:::\n\n\n  - Ahora sí con CHI CUADRADO\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(dfbaro$pais, dfbaro$satis_democracia)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  dfbaro$pais and dfbaro$satis_democracia\nX-squared = 199.56, df = 3, p-value < 2.2e-16\n```\n:::\n:::\n\n  \n  - El chi cuadrado observado es 199.56.\n  \n  - Grados de libertad (df) = 3\n\nhipotesis de la prueba chi cuadrado:\n\nH0: NO HAY ASOCIACIÓN ENTRE LA SATISFACCIÓN DE LA DEMOCRACIA Y EL PAÍS. / LAS VARIABLES SON INDEPENDIENTES.\n\nP-VALOR = 0.00000000000000022 (< 2.2e-16). Por tanto, Rechazo la hipotesis nula. a um 95% del nivel de confianza Si es posible una relación entre la satisfacción de la democracia y el país de procedencia.\n\n\n\n  - Entonces, si sale significativo: Lo que sigue son dos casos para dos variables categoricas.\n\n**<b style = 'color : #50D050;'>CASO 1: MEDIDAS DE ASOCIACIÓN PARA AL MENOS UNA VARIABLE NOMINAL</b>**\n============================================================\n  - ***En este caso solo mediremos intensidad***\n\n**MEDIDAS SIMETRICAS**\n\n¿Existe o no relacion entre el pais y su satisfaccion con la democracia?\n\n::: {.cell}\n\n```{.r .cell-code}\ncuadro = table(dfbaro$satis_democracia, dfbaro$pais)\n#install.packages(\"vcd\")\n\nlibrary(vcd)\nassocstats(cuadro) # Calcula las medidas de asociacion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    X^2 df P(> X^2)\nLikelihood Ratio 216.99  3        0\nPearson          199.56  3        0\n\nPhi-Coefficient   : NA \nContingency Coeff.: 0.205 \nCramer's V        : 0.209 \n```\n:::\n:::\n\n\n  - Contingency Coeff.: 0.205 <- el coeficiente de contingencia nos indica que es una relacion de intensidad debil. \n\n**MEDIDAS ASIMETRICAS**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"DescTools\")\nlibrary(DescTools)\n\nPhi(cuadro, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2090112\n```\n:::\n\n```{.r .cell-code}\nUncertCoef(cuadro, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        uc     lwr.ci     upr.ci \n0.02429518 0.01824672 0.03034365 \n```\n:::\n\n```{.r .cell-code}\nLambda(cuadro, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    lambda     lwr.ci     upr.ci \n0.05708661 0.03969189 0.07448134 \n```\n:::\n:::\n\n  - Advertimos que el lambda es debil. 0.057\n  - El (uc) coeficiente de incertidumbre es 0.024, tambien es debil\n\n\n**<b style = 'color : #50D050;'>CASO 2: MEDIDAS DE ASOCIACIÓN PARA RELACIÓN ENTRE DOS VARIABLES ORDINALES</b>**\n============================================================\n  - En este caso mediremos intensidad y dirección\n\n\n***¿Existe o no relacion entre si se considera justa la distribucion de ingresos y el nivel de progreso del país?***\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dfbaro$justo,dfbaro$pais_pro)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             \n              Progreso Estancado Retrocedio\n  Muy justa         32        28         21\n  Justa            439       353        104\n  Injusta          615      1347        478\n  Muy injusta      196       561        308\n```\n:::\n:::\n\n\n  - Estadisticos marginales \n\n::: {.cell}\n\n```{.r .cell-code}\ntabla = prop.table(table(dfbaro$justo,dfbaro$pais_pro),1)*100\naddmargins(tabla)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             \n               Progreso Estancado Retrocedio       Sum\n  Muy justa    39.50617  34.56790   25.92593 100.00000\n  Justa        48.99554  39.39732   11.60714 100.00000\n  Injusta      25.20492  55.20492   19.59016 100.00000\n  Muy injusta  18.40376  52.67606   28.92019 100.00000\n  Sum         132.11038 181.84620   86.04342 400.00000\n```\n:::\n:::\n\n\n  - Chi2 \n\n::: {.cell}\n\n```{.r .cell-code}\ncuadro2 = table(dfbaro$justo,dfbaro$pais_pro)\nchisq.test(cuadro2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  cuadro2\nX-squared = 293.26, df = 6, p-value < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Medidas de asociación para variables ordinales\nGoodmanKruskalGamma(cuadro2, conf.level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    gamma    lwr.ci    upr.ci \n0.3208106 0.2796476 0.3619736 \n```\n:::\n\n```{.r .cell-code}\nKendallTauB(cuadro2, conf.level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    tau_b    lwr.ci    upr.ci \n0.2005291 0.1740476 0.2270107 \n```\n:::\n:::\n\n  - Segun el gamma esa relacion es media. En este caso la direccion es positiva. Es decir, las personas que consideran que el pais ha retrocedido, tambien consideran que la distribucion de ingresos es mas injusta. Las personas que consideran que el pais ha progresado más, tienden  a pensar que la distribucion de ingresos es mas injusta.\n\n  - En este caso nos interesa calcular el TauC, pues no es una matriz cuadrada.\n\n::: {.cell}\n\n```{.r .cell-code}\nStuartTauC(cuadro2, conf.level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     tauc    lwr.ci    upr.ci \n0.1839186 0.1593666 0.2084706 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Medidas asimetricas\ncuadro2 = table(dfbaro$pais_pro, dfbaro$justo)\ncuadro2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            \n             Muy justa Justa Injusta Muy injusta\n  Progreso          32   439     615         196\n  Estancado         28   353    1347         561\n  Retrocedio        21   104     478         308\n```\n:::\n\n```{.r .cell-code}\nSomersDelta(cuadro2, direction = \"row\") #fila = variable dependiente #row reemplazar por col si es que la variable esta en columnas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2020387\n```\n:::\n:::\n\n\n  -SomersDelta: 0.2020387. relacion directa y debil\n\n  + DIRECTA: \n  \n  A medida que se cree que la distribución de ingresos es muy injusta, se considera que el país retrocedio. \n  \n  A medida que se cree que la distribución de ingresos es muy justa, se considera que el país progreso\n\n  + INTENSIDAD: BAJA 0 a 0.3 es relación baja.\n\n\n\n  - Para una mejor compresion de la tabla:\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(dfbaro$pais_pro, dfbaro$justo),1)*100 # En este caso por filas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            \n             Muy justa     Justa   Injusta Muy injusta\n  Progreso    2.496100 34.243370 47.971919   15.288612\n  Estancado   1.223242 15.421581 58.846658   24.508519\n  Retrocedio  2.305159 11.416026 52.469813   33.809001\n```\n:::\n:::\n\n  - Los que consideran que el pais ha retorcedido, son los que consideran que la distribucion de ingresos es muy injusta. (33.809001)\n  - Los que consideran que el pais se ha Estancado, son los que consideran que la distribucion de ingresos es Injusta. (58.846658 )\n  - Los que consideran que el pais ha Progresado, son los que consideran que la distribucion de ingresos es injusta. (47.971919)\n  \n  - Ahora por columnas:\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(dfbaro$pais_pro, dfbaro$justo),2)*100 # En este caso por filas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            \n             Muy justa    Justa  Injusta Muy injusta\n  Progreso    39.50617 48.99554 25.20492    18.40376\n  Estancado   34.56790 39.39732 55.20492    52.67606\n  Retrocedio  25.92593 11.60714 19.59016    28.92019\n```\n:::\n:::\n\n  - Los que consideran que el pais ha Progresado, son los que consideran que la distribucion de ingresos es muy justa. (39.50617 ).  Del mismo modo con justa (48.99554)\n  \n  - Los que consideran que el pais se ha Estancado, son los que consideran que la distribucion de ingresos es muy injusta. (52.67606). Del mismo modo con Injusta(55.20492)\n\n\n",
    "supporting": [
      "s7-ejercicio-semana7b_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}